// AUTO-GENERATED by scripts/gen-tokens.mjs from src/styles/tokens.css.
// DO NOT EDIT. Run `npm run tokens` after changing tokens.css.
// CI fails if this file is stale (see design.md §15).
//
// 107 tokens, mirrored verbatim as strings. var() aliases are resolved to
// their literal here so JS consumers get a usable value; tokens.css keeps the
// indirection for CSS consumers.
export const token = Object.freeze({
  surface: Object.freeze({
    canvas: '#080A0E',
    panel: '#0F1117',
    raised: '#151821',
    inset: '#1A202C',
    overlay: 'rgba(8, 10, 14, 0.88)',
  }),
  line: Object.freeze({
    subtle: '#141922',
    default: '#1E2530',
    strong: '#2A3441',
  }),
  content: Object.freeze({
    primary: '#F0F2F5',
    secondary: '#8B95A5',
    muted: '#5A6578',
    inverse: '#080A0E',
  }),
  brand: Object.freeze({
    base: '#00D4FF',
    hover: '#33E0FF',
    wash: 'rgba(0, 212, 255, 0.10)',
  }),
  status: Object.freeze({
    live: Object.freeze({
      fg: '#26A69A',
      wash: 'rgba(38, 166, 154, 0.12)',
    }),
    connected: Object.freeze({
      fg: '#26A69A',
      wash: 'rgba(38, 166, 154, 0.12)',
    }),
    profit: Object.freeze({
      fg: '#26A69A',
      wash: 'rgba(38, 166, 154, 0.12)',
    }),
    loss: Object.freeze({
      fg: '#EF5350',
      wash: 'rgba(239, 83, 80, 0.12)',
    }),
    error: Object.freeze({
      fg: '#EF5350',
      wash: 'rgba(239, 83, 80, 0.12)',
    }),
    warning: Object.freeze({
      fg: '#F59E0B',
      wash: 'rgba(245, 158, 11, 0.12)',
    }),
    guidance: Object.freeze({
      fg: '#F59E0B',
      wash: 'rgba(245, 158, 11, 0.12)',
    }),
    neutral: Object.freeze({
      fg: '#8B95A5',
      wash: 'rgba(139, 149, 165, 0.10)',
    }),
  }),
  env: Object.freeze({
    live: Object.freeze({
      fg: '#EF5350',
      wash: 'rgba(239, 83, 80, 0.12)',
    }),
    paper: Object.freeze({
      fg: '#818CF8',
      wash: 'rgba(99, 102, 241, 0.12)',
    }),
    backtest: Object.freeze({
      fg: '#8B95A5',
      wash: 'rgba(139, 149, 165, 0.10)',
    }),
  }),
  font: Object.freeze({
    sans: "'Inter', system-ui, -apple-system, sans-serif",
    mono: "'JetBrains Mono', 'IBM Plex Mono', 'Fira Code', 'SF Mono', Menlo, Consolas, monospace",
  }),
  text: Object.freeze({
    micro: '0.625rem',
    small: '0.6875rem',
    body: '0.8125rem',
    title: '0.875rem',
    section: '1.125rem',
    page: '1.5rem',
    figure: '1.75rem',
    lineHeight: Object.freeze({
      micro: '1rem',
      small: '1.125rem',
      body: '1.25rem',
      title: '1.25rem',
      section: '1.5rem',
      page: '2rem',
      figure: '2rem',
    }),
  }),
  space: Object.freeze({
    '1': '0.25rem',
    '2': '0.5rem',
    '3': '0.75rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '8': '2rem',
    '10': '2.5rem',
    '12': '3rem',
  }),
  radius: Object.freeze({
    xs: '2px',
    sm: '4px',
    md: '6px',
    lg: '8px',
    xl: '12px',
    full: '9999px',
  }),
  shadow: Object.freeze({
    panel: '0 1px 2px rgba(0, 0, 0, 0.30)',
    raised: '0 4px 12px rgba(0, 0, 0, 0.35)',
    overlay: '0 16px 48px rgba(0, 0, 0, 0.60)',
  }),
  transition: Object.freeze({
    fast: '120ms cubic-bezier(0.4, 0, 0.2, 1)',
    base: '180ms cubic-bezier(0.4, 0, 0.2, 1)',
  }),
  breakpoint: Object.freeze({
    tablet: '768px',
    laptop: '1024px',
    desktop: '1440px',
    wide: '1920px',
  }),
  zIndex: Object.freeze({
    base: '0',
    sticky: '10',
    dropdown: '100',
    drawer: '200',
    modal: '300',
    toast: '400',
    devtool: '500',
  }),
  focusRing: Object.freeze({
    width: '2px',
    offset: '2px',
    color: '#00D4FF',
  }),
  compat: Object.freeze({
    accent: Object.freeze({
      cyan: '#00D4FF',
      profit: '#26A69A',
      loss: '#EF5350',
      gold: '#F59E0B',
      cyanDim: 'rgba(0, 212, 255, 0.10)',
      profitDim: 'rgba(38, 166, 154, 0.12)',
      lossDim: 'rgba(239, 83, 80, 0.12)',
      goldDim: 'rgba(245, 158, 11, 0.12)',
    }),
    text: Object.freeze({
      primary: '#F0F2F5',
      muted: '#5A6578',
      secondary: '#8B95A5',
      inverse: '#080A0E',
    }),
    border: Object.freeze({
      default: '#1E2530',
      active: '#2A3441',
      subtle: '#141922',
      base: '#1E2530',
    }),
    bg: Object.freeze({
      '3': '#1A202C',
      elevated: '#151821',
      surface: '#0F1117',
      primary: '#080A0E',
    }),
  }),
});

/**
 * CSS custom-property reference, for inline styles during migration.
 *
 * The path is the CSS custom-property path with dots for dashes, not a path
 * into `token` above: cssVar('color.status.profit') → 'var(--color-status-profit)'.
 */
export const cssVar = (path) => `var(--${path.replace(/\./g, '-')})`;
