"""tests/test_websocket_upgrade_gate.py

The frontend deploy's WebSocket gate fails when the realtime layer is broken, and
passes when it is not.

THE GAP THIS CLOSES
-------------------
``06-frontend-deploy.yml``'s last step probes ``/ws/telemetry`` with a real HTTP/1.1 upgrade
and is BLOCKING, so it is the only thing standing between a silently-dead socket layer and a
green deploy. It is also the only step in that workflow whose verdict depends on a fact about
the ASGI server rather than on a fact about the bundle, and it got that fact wrong: it required
``server: uvicorn`` on the upgrade response as proof the origin had answered.

uvicorn does not emit a ``server`` header on that path. ``backend_app/api_ws/ws_routes.py``
closes before ``accept()`` when the ``ticket`` query parameter is absent, and uvicorn renders
that as a bare 403 with ``Content-Type: text/plain``, ``Content-Length: 0`` and no ``server``
header at all - reproduced on a local uvicorn running a minimal ASGI app with no CDN and no ALB
in the path, and identical in shape to what a raw upgrade straight to the ALB returns with
CloudFront bypassed. So the discriminator could never be satisfied: the gate failed every run,
run 37035482811 among them, and the state it reported as its failure ("403 with no origin
header") is the healthy one. The live frontend bundle went stale because no frontend change
could ship.

A FALSE-POSITIVE GATE IS A SPECIFIC KIND OF REGRESSION RISK
-----------------------------------------------------------
The obvious repair - drop the header condition and pass on any 403 - inverts into the opposite
defect, because a 403 generated by the CDN and a 403 from the application's WebSocket router are
the same status with the same headers. The gate has to keep BOTH probes to stay sound:

    A  genuine HTTP/1.1 upgrade  -> 403 (or 101); only reachable if the upgrade headers
                                    survived to the origin
    B  the same URL, no upgrade  -> 404 with ``server: uvicorn``; the origin's own fingerprint,
                                    which is what makes A's 403 attributable

and ``404`` on probe A has to stay a FAILURE, because that is what the regression looks like:
a stripped upgrade arrives at the origin as a plain GET and gets HTTP-routed.

WHAT THIS FILE PINS
-------------------
1. The TEXT of the step, so it cannot regress to the inverted form: two probes, ``404`` on the
   upgrade probe treated as failure, and no ``server``-header condition on the upgrade
   response's pass.
2. The step's actual BEHAVIOUR, by extracting its bash out of the YAML and running it with
   ``curl`` stubbed to canned header blocks. The workflow cannot be run locally, so this is the
   strongest cover available: it exercises the real shipped script, not a transcription of it.

Companion to ``tests/test_security_gate_blocks_deploy.py`` (task 13.10), which pins the other
blocking CI gate in this repository.
"""

import io
import os
import shutil
import subprocess
import tempfile

import pytest
import yaml

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
FRONTEND_YML = os.path.join(REPO, ".github", "workflows", "06-frontend-deploy.yml")

STEP_NAME = "Verify the WebSocket upgrade reaches the origin"


# ──────────────────────────────────────────────────────────────────────────────
#  Reading the workflow
# ──────────────────────────────────────────────────────────────────────────────

def _workflow():
    return yaml.safe_load(io.open(FRONTEND_YML, encoding="utf-8").read())


def _steps():
    return _workflow()["jobs"]["deploy-frontend"]["steps"]


def _gate_step():
    matches = [s for s in _steps() if (s.get("name") or "") == STEP_NAME]
    assert matches, "06-frontend-deploy.yml has no %r step; the realtime layer is ungated" % STEP_NAME
    return matches[0]


def _gate_body():
    return _gate_step()["run"]


def _workflow_text():
    return io.open(FRONTEND_YML, encoding="utf-8").read()


# ──────────────────────────────────────────────────────────────────────────────
#  The step's text, so the inverted form cannot come back
# ──────────────────────────────────────────────────────────────────────────────

class TestTheGateRunsBothProbes:
    def test_it_sends_a_genuine_upgrade_and_a_request_with_no_upgrade(self):
        body = _gate_body()

        assert body.count("curl ") >= 2, (
            "the gate issues fewer than two curl requests; one probe cannot tell a "
            "CDN-generated 403 from an application refusal, because both are 403"
        )
        assert "Upgrade: websocket" in body, "no probe attempts a WebSocket upgrade at all"
        assert "Sec-WebSocket-Key" in body, "the upgrade probe is missing Sec-WebSocket-Key"

        # The no-upgrade probe must exist and must NOT carry upgrade headers: it is the
        # corroborating half, and it only corroborates if it is a plain GET.
        invocations = _curl_invocations(body)
        assert len(invocations) >= 2, "expected two curl invocations, found %d" % len(invocations)
        with_upgrade = [c for c in invocations if "Upgrade: websocket" in c]
        without_upgrade = [c for c in invocations if "Upgrade: websocket" not in c]
        assert with_upgrade, "no curl invocation carries the upgrade headers"
        assert without_upgrade, (
            "every curl invocation carries upgrade headers, so there is no probe B; probe A's "
            "403 cannot be attributed to the origin without it"
        )

    def test_both_probes_pin_http_1_1(self):
        """h2 forbids Connection, so curl silently drops the upgrade headers over h2."""
        for invocation in _curl_invocations(_gate_body()):
            assert "--http1.1" in invocation, (
                "a curl probe omits --http1.1: over h2 curl drops Connection/Upgrade and sends "
                "a plain GET, which makes probe A degenerate into probe B -- %s" % invocation
            )

    def test_both_probes_hit_the_same_url(self):
        body = _gate_body()
        assert body.count('"$PROBE_URL"') >= 2, (
            "the two probes must target the same URL; the asymmetry is only attributable to "
            "the upgrade headers if nothing else differs"
        )


class TestAStrippedUpgradeIsStillAFailure:
    def test_404_on_the_upgrade_probe_fails_the_gate(self):
        """This is the regression the gate exists to catch; it must not become a pass."""
        body = _gate_body()
        assert '"$CODE_A" = "404"' in body, (
            "the gate does not branch on a 404 from the upgrade probe. A stripped upgrade "
            "reaches the origin as a plain GET and is HTTP-routed to 404 -- that is exactly "
            "the CloudFront misconfiguration this step exists to catch"
        )
        assert "exit 1" in _stripped_header_branch(body), (
            "the 404-on-probe-A branch does not exit non-zero, so a stripped upgrade would "
            "deploy green"
        )

    def test_only_101_and_403_count_as_reaching_the_origin(self):
        accepted = _accepted_upgrade_statuses(_gate_body())
        assert "101|403)" in accepted, (
            "the upgrade probe's accepted statuses are not the pair that can only come from "
            "the ASGI WebSocket router (101 accepted, 403 refused unauthenticated): %r"
            % accepted
        )
        assert "404" not in accepted, (
            "404 is treated as the upgrade reaching the origin; it means the opposite -- the "
            "handshake arrived as a plain GET and was HTTP-routed: %r" % accepted
        )

    def test_the_pass_requires_both_probes(self):
        _pass_condition(_gate_body())

    def test_the_cloudfront_advice_is_printed_only_on_the_stripped_header_branch(self):
        """Different failure, different message: advice that does not follow from the evidence
        sends the next reader to reconfigure infrastructure that is already correct."""
        body = _gate_body()
        assert body.count("AllViewer") == 1, (
            "the CloudFront header-forwarding remediation appears %d times; it is correct advice "
            "for a stripped upgrade and misleading for anything else" % body.count("AllViewer")
        )
        stripped_branch = _stripped_header_branch(body)
        assert "AllViewer" in stripped_branch, (
            "the AllViewer remediation is not inside the 404-on-probe-A branch"
        )


class TestThePassDoesNotRestOnTheFalsePremise:
    def test_the_upgrade_response_is_not_required_to_carry_an_origin_server_header(self):
        """uvicorn emits no `server` header when it closes before accept. Conditioning the
        pass on one is what made this gate fail on every green deploy."""
        body = _gate_body()
        server_greps = [
            line.strip() for line in body.splitlines()
            if "server:" in line.lower() and "grep" in line
        ]
        assert server_greps, "the gate no longer checks for an origin server header anywhere"
        for line in server_greps:
            assert "HEADERS_PLAIN" in line, (
                "a server-header check is applied to something other than the no-upgrade "
                "probe's headers: %s\nuvicorn does not emit `server` on the close-before-accept "
                "path, so requiring it on the UPGRADE response can never be satisfied" % line
            )
            assert "HEADERS_UPGRADE" not in line, (
                "the server-header check reads the upgrade probe's headers: %s" % line
            )

    def test_the_comment_no_longer_claims_the_upgrade_403_carries_server_uvicorn(self):
        text = _workflow_text()
        assert "a PASS, because it proves the upgrade reached the application — `server: uvicorn` is the" not in text, (
            "the step's comment still asserts that `server: uvicorn` is the evidence an upgrade "
            "reached the origin; it is not emitted on that path"
        )
        assert "A passing response carries 'server: uvicorn'." not in text, (
            "the step still tells the next operator to confirm the fix by looking for "
            "`server: uvicorn` on an upgrade response"
        )
        assert "NO `server` header" in text, (
            "the step no longer records WHY the header cannot be used as the discriminator, so "
            "the next reader is free to reintroduce it"
        )

    def test_the_comment_records_why_one_probe_is_not_enough(self):
        text = _workflow_text()
        assert "SAME STATUS CODE" in text or "same status" in text, (
            "the step does not record that a CDN-generated 403 and an application refusal are "
            "the same status, which is the whole reason two probes are needed"
        )

    def test_the_comment_states_what_the_gate_cannot_prove(self):
        text = _workflow_text()
        assert "does not prove a socket actually carries data" in text, (
            "the step no longer states that it cannot prove a socket carries data"
        )
        assert "require a ticket" in text and "credential in a workflow" in text, (
            "the step no longer gives the reason it does not authenticate (every /ws/* endpoint "
            "needs a ticket, and minting one in CI puts a production credential in a workflow)"
        )


class TestTheGateStaysAGate:
    def test_it_is_the_last_step_and_it_blocks(self):
        steps = _steps()
        assert (steps[-1].get("name") or "") == STEP_NAME, (
            "the WebSocket gate is no longer the last step; it must run after the S3 sync and "
            "the invalidation, so a failure reports a broken realtime layer rather than "
            "aborting a half-finished deploy"
        )

        step = _gate_step()
        assert not step.get("continue-on-error"), (
            "continue-on-error turns the gate into a warning; a trading terminal that cannot "
            "open a socket is a product-down condition"
        )
        assert "exit 1" in step["run"], "the gate never exits non-zero, so it cannot block"

    def test_the_bundle_host_derivation_and_the_empty_guard_are_intact(self):
        body = _gate_body()
        assert "dist/assets/index-*.js" in body, (
            "the gate no longer reads the host out of the deployed bundle; the secret is not "
            "the authority on what the browser will dial"
        )
        assert "wss?://" in body, "the bundle WebSocket-base extraction is gone"
        assert '[ -z "$WS_BASE" ]' in body, (
            "the empty-WS_BASE guard is gone; with no host the gate would probe https:///..."
        )


# ──────────────────────────────────────────────────────────────────────────────
#  The step's behaviour, by running its real bash against stubbed curl
# ──────────────────────────────────────────────────────────────────────────────

def _curl_invocations(body):
    """Each real `curl` invocation as one logical line, backslash continuations joined.

    Both probes are of the form `VAR=$(curl ... || true)`, so matching on `$(curl ` picks up
    the invocations and skips the `curl -i ...` reproduction command the failure branch echoes
    for a human.
    """
    joined = body.replace("\\\n", " ")
    out = []
    for line in joined.splitlines():
        stripped = " ".join(line.split())
        if stripped.startswith("#") or stripped.startswith("echo "):
            continue
        if "$(curl " in stripped:
            out.append(stripped)
    return out


def _pass_condition(body):
    """The gate's pass test must be the CONJUNCTION of the two probes' inferences."""
    marker = 'if [ "$A_REACHED_ORIGIN" -eq 1 ] && [ "$B_ORIGIN_ANSWERED" -eq 1 ]; then'
    assert marker in body, (
        "the gate's pass condition is not the conjunction of both probes' inferences; either "
        "probe alone is insufficient"
    )
    return marker


def _accepted_upgrade_statuses(body):
    """The `case` that decides whether probe A reached the ASGI WebSocket router."""
    marker = 'case "$CODE_A" in'
    assert marker in body, "the gate does not classify the upgrade probe's status"
    return body.split(marker, 1)[1].split("esac", 1)[0]


def _stripped_header_branch(body):
    """The whole `if CODE_A = 404` branch, up to and including its closing `fi`."""
    marker = 'if [ "$CODE_A" = "404" ]; then'
    assert marker in body, (
        "no 404-on-probe-A branch: a stripped upgrade arrives at the origin as a plain GET and "
        "is HTTP-routed to 404, so this is the shape of the failure the gate exists to catch"
    )
    tail = body.split(marker, 1)[1]
    end = tail.find("\nfi\n")
    assert end != -1, "the 404-on-probe-A branch is never closed"
    return tail[:end]


def _bash_candidates():
    candidates = []
    explicit = os.environ.get("BASH_FOR_TESTS")
    if explicit:
        candidates.append(explicit)
    # Git for Windows ships a bash that understands Windows working directories natively.
    git = shutil.which("git")
    if git:
        git_root = os.path.dirname(os.path.dirname(os.path.abspath(git)))
        candidates.append(os.path.join(git_root, "bin", "bash.exe"))
    candidates.append(r"C:\Program Files\Git\bin\bash.exe")
    found = shutil.which("bash")
    if found:
        candidates.append(found)
    seen = set()
    ordered = []
    for c in candidates:
        if c and c not in seen and os.path.exists(c):
            seen.add(c)
            ordered.append(c)
    return ordered


def _bash_works(path):
    """The harness needs a bash that can run a relative script in a given cwd and that has the
    coreutils the step uses."""
    try:
        with tempfile.TemporaryDirectory() as tmp:
            with open(os.path.join(tmp, "probe.sh"), "wb") as fh:
                fh.write(b'printf "x 7 y\\n" | head -1 | tr -d "\\r" | awk "{print \\$2}"\n'
                         b'echo "wss://h" | sed -E "s#^wss?://##"\n'
                         b'echo ok | grep -qiE "^ok" && echo FINE\n')
            proc = subprocess.run([path, "probe.sh"], cwd=tmp, capture_output=True, timeout=60)
            return proc.returncode == 0 and b"FINE" in proc.stdout and b"7" in proc.stdout
    except Exception:
        return False


def _pick_bash():
    for candidate in _bash_candidates():
        if _bash_works(candidate):
            return candidate
    return None


BASH = _pick_bash()

needs_bash = pytest.mark.skipif(
    BASH is None,
    reason="no bash able to run the step's script was found; the text assertions above still "
           "pin the gate's logic (CI runs this job on ubuntu-latest, where bash is native)",
)

CRLF = chr(13) + chr(10)

# Measured, not invented. `UPGRADE_403` is the byte shape a local uvicorn returns for a
# minimal ASGI app that sends websocket.close before websocket.accept, with no CDN and no ALB;
# it is also what a raw upgrade to the ALB returns with CloudFront bypassed. Note the absence
# of a `server` header -- that absence is the whole point of this file.
UPGRADE_403 = [
    "HTTP/1.1 403 Forbidden",
    "Date: Fri, 02 Oct 2026 18:23:46 GMT",
    "Content-Type: text/plain",
    "Content-Length: 0",
    "Connection: close",
    "X-Cache: Error from cloudfront",
    "Via: 1.1 77a9d226db7a6fccf3907a64ecc724b4.cloudfront.net (CloudFront)",
]

# The no-upgrade GET, as observed through CloudFront against the live host. `X-Cache: Error
# from cloudfront` is on this one too, which is why it is not usable as a discriminator.
PLAIN_404_UVICORN = [
    "HTTP/1.1 404 Not Found",
    "Content-Type: application/json",
    "Content-Length: 22",
    "Connection: close",
    "x-request-id: 54ed67b32df640d99eeebbef2a58d6d1",
    "server: uvicorn",
    "X-Cache: Error from cloudfront",
]

UPGRADE_101 = [
    "HTTP/1.1 101 Switching Protocols",
    "Upgrade: websocket",
    "Connection: Upgrade",
    "Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=",
]

# What a stripped upgrade looks like: the handshake arrived as a plain GET and was HTTP-routed.
UPGRADE_STRIPPED_404 = list(PLAIN_404_UVICORN)

UPGRADE_502_CDN = [
    "HTTP/1.1 502 Bad Gateway",
    "Content-Type: text/html",
    "X-Cache: Error from cloudfront",
]

PLAIN_403_NO_ORIGIN = [
    "HTTP/1.1 403 Forbidden",
    "Content-Type: text/html",
    "Content-Length: 919",
    "X-Cache: Error from cloudfront",
]

# `curl` is shadowed by a shell function rather than a file on PATH: no chmod, no PATH
# rewriting, no path translation, and the real step body is left completely untouched.
HARNESS_PREAMBLE = """\
curl() {
  for _arg in "$@"; do
    if [ "$_arg" = "Upgrade: websocket" ]; then
      cat ./stub_upgrade.txt
      return 0
    fi
  done
  cat ./stub_plain.txt
  return 0
}
"""


def _write_headers(path, lines):
    with open(path, "wb") as fh:
        if lines:
            fh.write((CRLF.join(lines) + CRLF + CRLF).encode("ascii"))


def run_gate(upgrade_headers, plain_headers, bundle='connect("wss://app.vyomquant.in/ws/telemetry")'):
    """Run the shipped step body with curl stubbed. Returns (returncode, combined output)."""
    body = _gate_body()
    with tempfile.TemporaryDirectory() as tmp:
        assets = os.path.join(tmp, "dist", "assets")
        os.makedirs(assets)
        with open(os.path.join(assets, "index-a1b2c3d4.js"), "wb") as fh:
            fh.write(bundle.encode("utf-8"))

        _write_headers(os.path.join(tmp, "stub_upgrade.txt"), upgrade_headers)
        _write_headers(os.path.join(tmp, "stub_plain.txt"), plain_headers)

        with open(os.path.join(tmp, "gate.sh"), "wb") as fh:
            fh.write((HARNESS_PREAMBLE + body).replace("\r\n", "\n").encode("utf-8"))

        # `-e` is what GitHub Actions uses for a `run:` step on Linux.
        proc = subprocess.run(
            [BASH, "-e", "gate.sh"], cwd=tmp, capture_output=True, timeout=180
        )
    output = (proc.stdout + proc.stderr).decode("utf-8", "replace")
    return proc.returncode, output


@needs_bash
class TestTheGatePassesWhenTheRealtimeLayerIsHealthy:
    def test_a_403_with_no_server_header_plus_a_404_uvicorn_passes(self):
        """The production state of run 37035482811. The gate used to fail here."""
        code, out = run_gate(UPGRADE_403, PLAIN_404_UVICORN)
        assert code == 0, "the gate failed on a healthy realtime layer:\n%s" % out
        assert "✅" in out
        assert "Corroborated by probe B" in out

    def test_an_accepted_handshake_passes(self):
        code, out = run_gate(UPGRADE_101, PLAIN_404_UVICORN)
        assert code == 0, out
        assert "101 Switching Protocols" in out

    def test_the_pass_still_says_what_it_has_not_proven(self):
        code, out = run_gate(UPGRADE_403, PLAIN_404_UVICORN)
        assert code == 0, out
        assert "NOT PROVEN" in out, (
            "a passing run should not leave a reader believing a socket was shown to carry data"
        )


@needs_bash
class TestTheGateFailsWhenItShould:
    def test_a_stripped_upgrade_fails_and_names_the_cloudfront_misconfiguration(self):
        """Probe A degenerates into probe B: the regression this gate exists to catch."""
        code, out = run_gate(UPGRADE_STRIPPED_404, PLAIN_404_UVICORN)
        assert code == 1, "a stripped upgrade passed the gate:\n%s" % out
        assert "STRIPPED" in out
        assert "AllViewer" in out, "the correct remediation was not printed for this failure"

    def test_an_unreachable_origin_fails_without_blaming_cloudfront_headers(self):
        """Probe A looks fine but probe B cannot corroborate it. Different failure, different
        message -- and crucially NOT the header-forwarding advice."""
        code, out = run_gate(UPGRADE_403, PLAIN_403_NO_ORIGIN)
        assert code == 1, "the gate passed with no corroboration from probe B:\n%s" % out
        assert "could not be confirmed reachable" in out
        assert "AllViewer" not in out, (
            "the CloudFront header-forwarding remediation was printed for a failure whose "
            "evidence does not point there; that sends the next reader to reconfigure "
            "infrastructure that is already correct"
        )

    def test_a_missing_server_header_on_probe_b_alone_is_not_enough(self):
        plain_no_server = [h for h in PLAIN_404_UVICORN if not h.lower().startswith("server:")]
        code, out = run_gate(UPGRADE_403, plain_no_server)
        assert code == 1, "a 404 without `server: uvicorn` corroborated nothing:\n%s" % out
        assert "AllViewer" not in out

    def test_a_cdn_error_is_reported_as_itself(self):
        code, out = run_gate(UPGRADE_502_CDN, PLAIN_404_UVICORN)
        assert code == 1, out
        assert "cannot read as a handshake outcome" in out
        assert "AllViewer" not in out, (
            "a 502 is not evidence of stripped headers; the remediation must not be printed"
        )

    def test_an_empty_ws_base_in_the_bundle_still_fails(self):
        code, out = run_gate(UPGRADE_403, PLAIN_404_UVICORN, bundle="var x=1;// no socket url")
        assert code == 1, "the empty-WS_BASE guard no longer holds:\n%s" % out
        assert "No WebSocket base URL" in out


@needs_bash
def test_the_two_probes_are_both_actually_issued():
    """A gate that silently stopped sending one probe would still pass the text assertions if
    the dead code were left in place. Count the stub's invocations instead."""
    body = _gate_body()
    counting_preamble = """\
curl() {
  for _arg in "$@"; do
    if [ "$_arg" = "Upgrade: websocket" ]; then
      echo "PROBE_A_ISSUED" >> ./calls.txt
      cat ./stub_upgrade.txt
      return 0
    fi
  done
  echo "PROBE_B_ISSUED" >> ./calls.txt
  cat ./stub_plain.txt
  return 0
}
"""
    with tempfile.TemporaryDirectory() as tmp:
        assets = os.path.join(tmp, "dist", "assets")
        os.makedirs(assets)
        with open(os.path.join(assets, "index-a1b2c3d4.js"), "wb") as fh:
            fh.write(b'u="wss://app.vyomquant.in/ws"')
        _write_headers(os.path.join(tmp, "stub_upgrade.txt"), UPGRADE_403)
        _write_headers(os.path.join(tmp, "stub_plain.txt"), PLAIN_404_UVICORN)
        with open(os.path.join(tmp, "gate.sh"), "wb") as fh:
            fh.write((counting_preamble + body).replace("\r\n", "\n").encode("utf-8"))
        proc = subprocess.run([BASH, "-e", "gate.sh"], cwd=tmp, capture_output=True, timeout=180)
        calls_path = os.path.join(tmp, "calls.txt")
        calls = io.open(calls_path, encoding="utf-8").read() if os.path.exists(calls_path) else ""

    out = (proc.stdout + proc.stderr).decode("utf-8", "replace")
    assert "PROBE_A_ISSUED" in calls, "the upgrade probe was never sent:\n%s" % out
    assert "PROBE_B_ISSUED" in calls, "the no-upgrade probe was never sent:\n%s" % out
    assert proc.returncode == 0, out
