"""
backend/strategy_dag/block_specs.py - DATA, MATH, LOGIC and ACTION block descriptors.

The four block families that have no engine module of their own. INDICATOR descriptors
live in ``indicators_backend.INDICATOR_SPECS``, FEATURE_ENGINEERING in
``feature_engineering.FEATURE_SPECS`` and ML_DL in ``ml_models.MODEL_SPECS``; the
remaining four are declared here so ``registry.build_registry()`` can assemble all seven
categories from real descriptors instead of a hand-maintained palette list (SB-03/SB-04).

Exposes
-------
``ParamSpec`` / ``BlockSpec``   descriptor contract, field-for-field with
                                ``design.md`` -> Descriptor contract
``MATH_SPECS``                  18 arithmetic blocks
``LOGIC_SPECS``                 14 boolean / comparison / signal blocks
``DATA_SPECS``                  ``ohlcv_feed``, ``live_ticker``, ``orderbook_imbalance``
``action_descriptors_for(ot)``  the ACTION factory, one order type in
``action_specs()``              every ACTION descriptor, generated from
                                ``exchange_executor.OrderType``
``all_block_specs()``           the four families concatenated
``resolve_block_runtime(ref)``  ``runtime_ref`` -> callable, raises when it cannot
``validate_block_params(...)``  declarative + cross-field parameter checks

Design rules this module encodes
--------------------------------
* **SB-06.** ``ohlcv_feed`` declares no ``exchange`` parameter, and ``symbol`` /
  ``timeframe`` are required with ``default=None``. There is no silent ``"BTC/USDT"`` and
  no silent ``"15m"``. Exchange identity exists only on a deployment binding.
* **Requirement 12.8.** No ACTION descriptor carries a traded-asset parameter. The traded
  symbol is resolved by the compiler from the DATA node in the action's upstream closure.
* **Requirement 5.4 / financial safety.** ``quantity_type`` and ``quantity`` are required
  with no default on every ACTION descriptor, as are ``price`` / ``trigger_price`` /
  ``limit_price`` where the order type uses them. A silent default position size is a
  financial-safety defect, so a graph that omits one cannot be saved.
* **Requirement 4.10.** ACTION descriptors are generated by iterating the real
  ``exchange_executor.OrderType``. Adding an order type to the executor without adding a
  descriptor variant here fails loudly (``_assert_order_type_coverage``); the palette can
  never advertise an order type the execution layer cannot place, nor silently omit one.
* **Terminal actions.** Every ACTION descriptor has no output ports and an empty
  ``allowed_successor_categories``, so nothing can be chained after an order.

Runtime references
------------------
Every ``runtime_ref`` resolves to a callable that exists today - the registry asserts this
at startup and refuses to advertise a block it cannot run:

* MATH / LOGIC / order-book imbalance -> the kernels defined in this module. They are pure
  array functions with the numeric firewall from ``design.md`` -> Math blocks applied
  (NaN propagates, division by zero / negative roots / non-positive logs yield NaN, and no
  infinity ever leaves a kernel). ``MathExecutor`` and ``LogicExecutor`` delegate to them
  rather than reimplementing arithmetic, exactly as ``IndicatorExecutor`` delegates to
  ``indicators_backend``.
* DATA -> ``data_seeking_engine.DataEngine`` methods, the platform's real market data
  access. ``streaming_runtime_ref`` names the stream counterpart of a block whose primary
  reference is the historical or snapshot call; both are asserted callable.
* ACTION -> ``exchange_executor.CCXTExchangeExecutor.place_order``, the real order path.
  Order parameters are advisory intent only: ``execution_guard``, ``risk_engine`` and
  ``execution_engine`` re-validate quantity, notional, precision, balance, position and
  risk limits at execution time and can refuse any intent.

Purity
------
Importing this module pulls in nothing heavier than NumPy. ``data_seeking_engine`` and
``exchange_executor`` are imported lazily, inside the resolver and the ACTION factory, so
declaring a descriptor never drags CCXT into a process that only needs the schema.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Mapping, Optional, Sequence, Tuple

import numpy as np

from backend_app.backend.strategy_dag.schema import BlockCategory, Port, PortType

MODULE_REF = "block_specs"

#: Anything with magnitude below this is treated as zero by the numeric firewall.
EPSILON = 1e-12

#: Float equality tolerance for the ``eq`` / ``neq`` comparators. Exact float equality on
#: a computed indicator series is a defect, not a feature.
EQ_TOLERANCE = 1e-9


# ---------------------------------------------------------------------------
# Vocabularies
# ---------------------------------------------------------------------------


class ParamType(str, Enum):
    """Control type of a block parameter, as read by the UI form generator."""

    NUMBER = "NUMBER"
    INTEGER = "INTEGER"
    TEXT = "TEXT"
    SELECT = "SELECT"
    MULTISELECT = "MULTISELECT"
    BOOLEAN = "BOOLEAN"
    DATE = "DATE"
    SYMBOL = "SYMBOL"
    TIMEFRAME = "TIMEFRAME"


class ExecutionSemantics(str, Enum):
    """How the runtime must drive the block."""

    SERIES_MAP = "SERIES_MAP"
    WINDOWED = "WINDOWED"
    STATEFUL = "STATEFUL"
    TERMINAL = "TERMINAL"


class LeakageRisk(str, Enum):
    """Leakage classification. Every block here reads bar ``t`` and earlier only."""

    NONE = "NONE"
    LOW = "LOW"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class Serialization(str, Enum):
    """Artifact format a trained block persists in. None of these families train."""

    NONE = "NONE"
    JOBLIB = "JOBLIB"
    KERAS = "KERAS"
    TORCH = "TORCH"


#: ``quantity_type`` option set, from ``design.md`` -> Action blocks.
QUANTITY_TYPES: Tuple[str, ...] = (
    "base_amount",
    "quote_notional",
    "percent_of_equity",
    "percent_of_free_balance",
    "fixed_notional",
)

#: ``action_close_position`` can additionally size as a portion of the open position.
CLOSE_QUANTITY_TYPES: Tuple[str, ...] = QUANTITY_TYPES + ("percent_of_position",)

#: Market shapes a DATA block can read. This is market *shape*, not exchange identity.
MARKET_TYPES: Tuple[str, ...] = ("spot", "swap", "future")

#: Parameters that materially change trading behaviour. Requirement 5.4: these are
#: published as required with no default, on every block that declares them.
NO_DEFAULT_PARAMS: Tuple[str, ...] = (
    "symbol",
    "timeframe",
    "quantity",
    "quantity_type",
    "price",
    "trigger_price",
    "limit_price",
    "confidence_threshold",
    "direction",
)

#: Never a parameter of any block in this module (SB-06 / Requirement 12.2).
FORBIDDEN_PARAM_KEYS: Tuple[str, ...] = ("exchange", "exchange_id", "api_key", "secret")

#: Never a parameter of an ACTION block (Requirement 12.8). The traded symbol comes from
#: the DATA node the action path descends from.
FORBIDDEN_ACTION_PARAM_KEYS: Tuple[str, ...] = (
    "symbol",
    "asset",
    "pair",
    "market",
    "ticker",
) + FORBIDDEN_PARAM_KEYS


# ---------------------------------------------------------------------------
# Descriptor contract
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ParamSpec:
    """Declarative parameter contract.

    The UI form generator and the backend validator read this same object, so a form can
    never offer a value the backend rejects and the backend never assumes the form checked
    (Requirements 5.1, 5.7).

    ``forward_to_runtime`` is False for parameters the runtime callable does not take as a
    keyword argument - ``mode`` selects which ``DataEngine`` call the executor makes, it is
    not an argument to it.
    """

    key: str
    label: str
    type: ParamType
    required: bool = True
    default: Any = None
    min: Optional[float] = None
    max: Optional[float] = None
    step: Optional[float] = None
    options: Optional[Tuple[Any, ...]] = None
    unit: Optional[str] = None
    example: Any = None
    help: str = ""
    depends_on: Tuple[str, ...] = ()
    affects_warmup: bool = False
    forward_to_runtime: bool = True
    #: Where a SELECT / MULTISELECT option set comes from when it cannot be enumerated
    #: at declaration time, because it depends on the graph rather than on the block -
    #: ``feat_select``'s columns are the upstream feature matrix's columns. A declared
    #: source is the only way to omit ``options``, so "resolved from the graph" stays
    #: distinguishable from "option set forgotten".
    options_source: Optional[str] = None

    def __post_init__(self) -> None:
        if self.key in FORBIDDEN_PARAM_KEYS:
            raise ValueError(
                f"Param '{self.key}' is forbidden in a strategy definition (SB-06); "
                "exchange identity belongs to the deployment binding"
            )
        if (
            self.type in (ParamType.SELECT, ParamType.MULTISELECT)
            and not self.options
            and not self.options_source
        ):
            raise ValueError(
                f"Param '{self.key}' is {self.type.value} but declares neither options "
                "nor an options_source"
            )
        if self.min is not None and self.max is not None and self.min > self.max:
            raise ValueError(f"Param '{self.key}' declares min > max")
        if self.key in NO_DEFAULT_PARAMS:
            if self.default is not None:
                raise ValueError(
                    f"Param '{self.key}' changes trading behaviour and must be published "
                    "with no default (Requirement 5.4)"
                )
            if not self.required:
                raise ValueError(
                    f"Param '{self.key}' changes trading behaviour and must be published "
                    "as required (Requirement 5.4)"
                )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "key": self.key,
            "label": self.label,
            "type": self.type.value,
            "required": self.required,
            "default": self.default,
            "min": self.min,
            "max": self.max,
            "step": self.step,
            "options": list(self.options) if self.options else None,
            "options_source": self.options_source,
            "unit": self.unit,
            "example": self.example,
            "help": self.help,
            "depends_on": list(self.depends_on),
            "affects_warmup": self.affects_warmup,
        }


@dataclass(frozen=True)
class BlockSpec:
    """Machine-readable descriptor for one DATA, MATH, LOGIC or ACTION block.

    Field names mirror ``BlockDescriptor`` in ``design.md`` so ``registry.py`` can adapt a
    ``BlockSpec`` without renaming anything, exactly as it adapts ``IndicatorSpec``,
    ``FeatureSpec`` and ``ModelSpec``.
    """

    block_id: str
    display_name: str
    category: BlockCategory
    description: str
    inputs: Tuple[Port, ...]
    outputs: Tuple[Port, ...]
    params: Tuple[ParamSpec, ...]
    warmup_fn: Callable[[Mapping[str, Any]], int]
    runtime_ref: str
    allowed_predecessor_categories: Tuple[BlockCategory, ...] = ()
    allowed_successor_categories: Tuple[BlockCategory, ...] = ()
    execution_semantics: ExecutionSemantics = ExecutionSemantics.SERIES_MAP
    #: Stream counterpart of ``runtime_ref`` for a block whose primary reference is the
    #: historical or snapshot call. Asserted callable alongside ``runtime_ref``.
    streaming_runtime_ref: Optional[str] = None
    serialization: Serialization = Serialization.NONE
    leakage_risk: LeakageRisk = LeakageRisk.NONE
    version: str = "1.0.0"
    capability_flags: Tuple[str, ...] = ()
    #: Cross-field rules that ranges and enums cannot express.
    validate: Optional[Callable[[Mapping[str, Any]], List[str]]] = None
    #: Non-contractual extras the compiler and executor need: ``order_type``, ``side``,
    #: ``intent``, ``operator``. Excluded from parameter validation.
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        _reject_duplicates(self.block_id, "input port", [p.name for p in self.inputs])
        _reject_duplicates(self.block_id, "output port", [p.name for p in self.outputs])
        _reject_duplicates(self.block_id, "param", [p.key for p in self.params])

        terminal = self.execution_semantics is ExecutionSemantics.TERMINAL
        if terminal and self.outputs:
            raise ValueError(
                f"Block '{self.block_id}' is TERMINAL and must declare no output ports"
            )
        if terminal and self.allowed_successor_categories:
            raise ValueError(
                f"Block '{self.block_id}' is TERMINAL and must declare an empty successor "
                "set; nothing can be chained after an order"
            )
        if not terminal and not self.outputs:
            raise ValueError(
                f"Block '{self.block_id}' declares no output ports but is not TERMINAL"
            )
        if self.category is BlockCategory.ACTION:
            if not terminal:
                raise ValueError(f"ACTION block '{self.block_id}' must be TERMINAL")
            offenders = [p.key for p in self.params if p.key in FORBIDDEN_ACTION_PARAM_KEYS]
            if offenders:
                raise ValueError(
                    f"ACTION block '{self.block_id}' declares traded-asset params "
                    f"{offenders}; the traded symbol is resolved from the DATA node in the "
                    "action's upstream closure (Requirement 12.8)"
                )

    # -- derived views ----------------------------------------------------
    @property
    def is_terminal(self) -> bool:
        return self.execution_semantics is ExecutionSemantics.TERMINAL

    def input_port(self, name: str) -> Optional[Port]:
        return next((p for p in self.inputs if p.name == name), None)

    def output_port(self, name: str) -> Optional[Port]:
        return next((p for p in self.outputs if p.name == name), None)

    def param(self, key: str) -> Optional[ParamSpec]:
        return next((p for p in self.params if p.key == key), None)

    def required_params(self) -> Tuple[ParamSpec, ...]:
        return tuple(p for p in self.params if p.required)

    def defaults(self) -> Dict[str, Any]:
        """Parameter map a freshly dropped node starts with.

        Keys whose declared default is ``None`` are present and empty on purpose: the
        inspector renders them blank and blocking until the author sets them.
        """
        return {p.key: p.default for p in self.params}

    def runtime_kwargs(self, params: Optional[Mapping[str, Any]] = None) -> Dict[str, Any]:
        """The subset of params the runtime callable actually accepts."""
        supplied = dict(params or {})
        resolved: Dict[str, Any] = {}
        for spec in self.params:
            if not spec.forward_to_runtime:
                continue
            if spec.key in supplied and supplied[spec.key] is not None:
                resolved[spec.key] = supplied[spec.key]
            elif spec.default is not None:
                resolved[spec.key] = spec.default
        return resolved

    def runtime_refs(self) -> Tuple[str, ...]:
        """Every runtime reference this descriptor advertises."""
        refs = [self.runtime_ref]
        if self.streaming_runtime_ref:
            refs.append(self.streaming_runtime_ref)
        return tuple(refs)

    def resolve_runtime(self) -> Callable[..., Any]:
        return resolve_block_runtime(self.runtime_ref)

    def warmup(self, params: Optional[Mapping[str, Any]] = None) -> int:
        resolved = self.defaults()
        if params:
            resolved.update({k: v for k, v in params.items() if v is not None})
        return int(self.warmup_fn(resolved))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "block_id": self.block_id,
            "display_name": self.display_name,
            "category": self.category.value,
            "description": self.description,
            "inputs": [p.to_dict() for p in self.inputs],
            "outputs": [p.to_dict() for p in self.outputs],
            "params": [p.to_dict() for p in self.params],
            "allowed_predecessor_categories": [
                c.value for c in self.allowed_predecessor_categories
            ],
            "allowed_successor_categories": [
                c.value for c in self.allowed_successor_categories
            ],
            "execution_semantics": self.execution_semantics.value,
            "runtime_ref": self.runtime_ref,
            "streaming_runtime_ref": self.streaming_runtime_ref,
            "serialization": self.serialization.value,
            "leakage_risk": self.leakage_risk.value,
            "version": self.version,
            "capability_flags": list(self.capability_flags),
            "metadata": dict(self.metadata),
        }


def _reject_duplicates(block_id: str, kind: str, names: Sequence[str]) -> None:
    seen = set()
    for name in names:
        if name in seen:
            raise ValueError(f"Block '{block_id}' declares duplicate {kind} '{name}'")
        seen.add(name)


# ---------------------------------------------------------------------------
# Runtime reference resolution
# ---------------------------------------------------------------------------


def _data_engine_attr(attribute: str) -> Any:
    from backend_app.backend.data_seeking_engine import DataEngine

    return getattr(DataEngine, attribute, None)


def _ccxt_executor_attr(attribute: str) -> Any:
    from backend_app.backend.exchange_executor import CCXTExchangeExecutor

    return getattr(CCXTExchangeExecutor, attribute, None)


#: ``runtime_ref`` owner -> lookup. Engine owners are imported lazily so that declaring a
#: descriptor never drags CCXT into a process that only needs the schema.
_RUNTIME_OWNERS: Dict[str, Callable[[str], Any]] = {
    MODULE_REF: lambda attribute: globals().get(attribute),
    "DataEngine": _data_engine_attr,
    "CCXTExchangeExecutor": _ccxt_executor_attr,
}


def resolve_block_runtime(runtime_ref: str) -> Callable[..., Any]:
    """Resolve ``"block_specs.math_add"`` / ``"DataEngine.fetch_historical_ohlcv"`` etc.

    Raises ``AttributeError`` naming the offender so ``build_registry()`` fails startup
    rather than advertising a block it cannot run (Requirements 4.7, 4.8).
    """
    owner, _, attribute = str(runtime_ref).rpartition(".")
    lookup = _RUNTIME_OWNERS.get(owner)
    if lookup is None:
        raise AttributeError(
            f"runtime_ref '{runtime_ref}' names unknown owner '{owner}'; known owners are "
            f"{sorted(_RUNTIME_OWNERS)}"
        )
    target = lookup(attribute)
    if not callable(target):
        raise AttributeError(f"runtime_ref does not resolve to a callable: {runtime_ref}")
    return target


# ---------------------------------------------------------------------------
# Numeric firewall - design.md -> Math blocks
# ---------------------------------------------------------------------------


def _as_float_array(value: Any) -> np.ndarray:
    if value is None:
        raise ValueError("math operand is None; the compiler guarantees a wired input")
    if isinstance(value, bool):
        return np.asarray(1.0 if value else 0.0, dtype=np.float64)
    if isinstance(value, np.ndarray):
        return value.astype(np.float64, copy=False)
    return np.asarray(value, dtype=np.float64)


def _align(operands: Sequence[Any], node_id: Optional[str]) -> List[np.ndarray]:
    """Broadcast scalars onto the common series length; reject mismatched lengths.

    Timestamp alignment itself is a compile-time guarantee - by the time a series reaches a
    kernel it is already bar-aligned - so length equality is what remains checkable here.
    """
    arrays = [_as_float_array(operand) for operand in operands]
    lengths = {int(a.shape[0]) for a in arrays if a.ndim > 0}
    if len(lengths) > 1:
        where = f" at node '{node_id}'" if node_id else ""
        raise ValueError(
            f"math operands have mismatched lengths {sorted(lengths)}{where}; series must "
            "be equal-length and timestamp-aligned"
        )
    length = lengths.pop() if lengths else 1
    return [
        a if a.ndim > 0 else np.full(length, float(a), dtype=np.float64) for a in arrays
    ]


def _finite_or_nan(values: np.ndarray) -> np.ndarray:
    """Replace every non-finite value with NaN. No infinity leaves a kernel."""
    out = np.asarray(values, dtype=np.float64).copy()
    out[~np.isfinite(out)] = np.nan
    return out


def _record(
    issues: Optional[List[Dict[str, Any]]],
    node_id: Optional[str],
    code: str,
    mask: np.ndarray,
) -> None:
    if issues is None or not bool(np.any(mask)):
        return
    bars = np.flatnonzero(mask)
    issues.append(
        {
            "node_id": node_id,
            "code": code,
            "bar": int(bars[0]),
            "bars_affected": int(bars.size),
        }
    )


def _reduce(binary_op: Callable[..., np.ndarray], arrays: Sequence[np.ndarray]) -> np.ndarray:
    out = arrays[0]
    for array in arrays[1:]:
        out = binary_op(out, array)
    return out


_LOG_BASES: Dict[str, float] = {"e": math.e, "2": 2.0, "10": 10.0}


def safe_math_apply(
    op: str,
    operands: Sequence[Any],
    options: Optional[Mapping[str, Any]] = None,
    node_id: Optional[str] = None,
    issues: Optional[List[Dict[str, Any]]] = None,
) -> np.ndarray:
    """Apply ``op`` to ``operands`` under the design's numeric-safety contract.

    Preconditions
        Operand series are equal-length and timestamp-aligned; scalars broadcast.

    Postconditions
        The result contains only finite values or NaN - never ``+Inf``, ``-Inf`` or an
        overflowed value. Division by zero, negative roots and non-positive logarithms
        yield NaN with an issue recorded rather than an exception or a poisoned number. NaN
        propagates within the series so a warmup region stays NaN; the action boundary is
        what stops NaN from reaching an order.

    This is the vectorised equivalent of the per-bar loop in ``design.md`` -> Math blocks.
    The loop invariant there ("every already-written bar is finite-or-NaN") holds here
    because the terminal ``_finite_or_nan`` sweep is applied to the whole array before it
    is returned.
    """
    op = str(op).upper()
    opts = dict(options or {})

    # SHIFT is handled before operand-NaN propagation: shifting *creates* leading NaNs by
    # design, and a source bar's NaN state belongs to the source bar, not the target.
    if op == "SHIFT":
        (series,) = _align(operands, node_id)
        bars = int(opts.get("bars", 1))
        if bars < 0:
            raise ValueError(
                f"shift bars must be >= 0 (backward only); got {bars} at node '{node_id}'"
            )
        out = np.full(series.shape[0], np.nan, dtype=np.float64)
        if bars == 0:
            out[:] = series
        elif bars < series.shape[0]:
            out[bars:] = series[:-bars]
        return _finite_or_nan(out)

    arrays = _align(operands, node_id)
    nan_mask = np.zeros(arrays[0].shape[0], dtype=bool)
    for array in arrays:
        nan_mask |= np.isnan(array)

    with np.errstate(all="ignore"):
        if op == "ADD":
            raw = _reduce(np.add, arrays)
        elif op == "SUBTRACT":
            raw = arrays[0] - arrays[1]
        elif op == "MULTIPLY":
            raw = _reduce(np.multiply, arrays)
        elif op == "DIVIDE":
            numerator, denominator = arrays[0], arrays[1]
            unsafe = np.abs(denominator) < EPSILON
            _record(issues, node_id, "DIVISION_BY_ZERO", unsafe & ~nan_mask)
            raw = numerator / np.where(unsafe, np.nan, denominator)
        elif op == "MODULO":
            left, right = arrays[0], arrays[1]
            unsafe = np.abs(right) < EPSILON
            _record(issues, node_id, "MODULO_BY_ZERO", unsafe & ~nan_mask)
            raw = np.fmod(left, np.where(unsafe, np.nan, right))
        elif op == "MIN":
            raw = _reduce(np.minimum, arrays)
        elif op == "MAX":
            raw = _reduce(np.maximum, arrays)
        elif op == "ABS":
            raw = np.abs(arrays[0])
        elif op == "NEGATE":
            raw = -arrays[0]
        elif op == "ROUND":
            raw = np.round(arrays[0], int(opts.get("decimals", 2)))
        elif op == "FLOOR":
            raw = np.floor(arrays[0])
        elif op == "CEIL":
            raw = np.ceil(arrays[0])
        elif op == "SQRT":
            negative = arrays[0] < 0
            _record(issues, node_id, "NEGATIVE_ROOT", negative & ~nan_mask)
            raw = np.sqrt(np.where(negative, np.nan, arrays[0]))
        elif op == "LOG":
            base = opts.get("base", "e")
            divisor = _LOG_BASES.get(str(base))
            if divisor is None:
                raise ValueError(f"unsupported log base {base!r} at node '{node_id}'")
            non_positive = arrays[0] <= 0
            _record(issues, node_id, "NON_POSITIVE_LOG", non_positive & ~nan_mask)
            raw = np.log(np.where(non_positive, np.nan, arrays[0]))
            if divisor != math.e:
                raw = raw / math.log(divisor)
        elif op == "EXP":
            raw = np.exp(arrays[0])
        elif op == "CLAMP":
            lower, upper = opts.get("lower"), opts.get("upper")
            if lower is None or upper is None:
                raise ValueError(f"clamp needs lower and upper at node '{node_id}'")
            if float(lower) > float(upper):
                raise ValueError(
                    f"clamp lower ({lower}) exceeds upper ({upper}) at node '{node_id}'"
                )
            raw = np.clip(arrays[0], float(lower), float(upper))
        elif op == "IDENTITY":
            raw = arrays[0]
        else:
            raise ValueError(f"unknown math op '{op}' at node '{node_id}'")

    # Requirement 20.4 lists "an arithmetic overflow" alongside division by zero, the
    # negative root and the non-positive logarithm: all four write NaN for the bar AND
    # record the condition. The three named cases are recorded at their own branch
    # because only that branch knows why the bar was undefined; an overflow has no
    # branch of its own - ``exp(800)``, ``1e300 * 1e300`` and a runaway ``ADD`` all reach
    # here as an infinity - so it is detected once, on the result, for every op. A bar
    # already NaN'd by a named branch is not an infinity by the time it arrives, so the
    # two never double-report the same bar.
    raw = np.asarray(raw, dtype=np.float64)
    _record(issues, node_id, "ARITHMETIC_OVERFLOW", np.isinf(raw) & ~nan_mask)

    result = _finite_or_nan(raw)
    result[nan_mask] = np.nan
    return result


# ---------------------------------------------------------------------------
# MATH kernels - what MathExecutor delegates to
# ---------------------------------------------------------------------------


def math_add(*operands: Any, node_id: Optional[str] = None, issues=None) -> np.ndarray:
    """Element-wise sum of 2..N aligned series."""
    return safe_math_apply("ADD", operands, node_id=node_id, issues=issues)


def math_subtract(a: Any, b: Any, node_id: Optional[str] = None, issues=None) -> np.ndarray:
    """Element-wise ``a - b``."""
    return safe_math_apply("SUBTRACT", (a, b), node_id=node_id, issues=issues)


def math_multiply(*operands: Any, node_id: Optional[str] = None, issues=None) -> np.ndarray:
    """Element-wise product of 2..N aligned series."""
    return safe_math_apply("MULTIPLY", operands, node_id=node_id, issues=issues)


def math_divide(
    numerator: Any, denominator: Any, node_id: Optional[str] = None, issues=None
) -> np.ndarray:
    """Division with a zero-denominator firewall: the bar becomes NaN, never an infinity."""
    return safe_math_apply(
        "DIVIDE", (numerator, denominator), node_id=node_id, issues=issues
    )


def math_modulo(a: Any, b: Any, node_id: Optional[str] = None, issues=None) -> np.ndarray:
    """Remainder; a zero divisor yields NaN for that bar."""
    return safe_math_apply("MODULO", (a, b), node_id=node_id, issues=issues)


def math_min(*operands: Any, node_id: Optional[str] = None, issues=None) -> np.ndarray:
    """Element-wise minimum across 2..N aligned series."""
    return safe_math_apply("MIN", operands, node_id=node_id, issues=issues)


def math_max(*operands: Any, node_id: Optional[str] = None, issues=None) -> np.ndarray:
    """Element-wise maximum across 2..N aligned series."""
    return safe_math_apply("MAX", operands, node_id=node_id, issues=issues)


def math_abs(a: Any, node_id: Optional[str] = None, issues=None) -> np.ndarray:
    """Magnitude of each bar."""
    return safe_math_apply("ABS", (a,), node_id=node_id, issues=issues)


def math_negate(a: Any, node_id: Optional[str] = None, issues=None) -> np.ndarray:
    """Flip the sign of each bar."""
    return safe_math_apply("NEGATE", (a,), node_id=node_id, issues=issues)


def math_round(
    a: Any, decimals: int = 2, node_id: Optional[str] = None, issues=None
) -> np.ndarray:
    """Round each bar to ``decimals`` places."""
    return safe_math_apply(
        "ROUND", (a,), options={"decimals": decimals}, node_id=node_id, issues=issues
    )


def math_floor(a: Any, node_id: Optional[str] = None, issues=None) -> np.ndarray:
    """Largest integer not greater than each bar."""
    return safe_math_apply("FLOOR", (a,), node_id=node_id, issues=issues)


def math_ceil(a: Any, node_id: Optional[str] = None, issues=None) -> np.ndarray:
    """Smallest integer not less than each bar."""
    return safe_math_apply("CEIL", (a,), node_id=node_id, issues=issues)


def math_sqrt(a: Any, node_id: Optional[str] = None, issues=None) -> np.ndarray:
    """Square root; a negative bar yields NaN with a recorded issue, not an exception."""
    return safe_math_apply("SQRT", (a,), node_id=node_id, issues=issues)


def math_log(
    a: Any, base: str = "e", node_id: Optional[str] = None, issues=None
) -> np.ndarray:
    """Logarithm; a bar at or below zero yields NaN with a recorded issue."""
    return safe_math_apply(
        "LOG", (a,), options={"base": base}, node_id=node_id, issues=issues
    )


def math_exp(a: Any, node_id: Optional[str] = None, issues=None) -> np.ndarray:
    """Exponential; an overflow yields NaN rather than ``+Inf``."""
    return safe_math_apply("EXP", (a,), node_id=node_id, issues=issues)


def math_clamp(
    a: Any, lower: float, upper: float, node_id: Optional[str] = None, issues=None
) -> np.ndarray:
    """Constrain each bar to the closed interval ``[lower, upper]``."""
    return safe_math_apply(
        "CLAMP",
        (a,),
        options={"lower": lower, "upper": upper},
        node_id=node_id,
        issues=issues,
    )


def math_constant(value: float, node_id: Optional[str] = None, issues=None) -> float:
    """A single finite constant. A non-finite constant is refused at authoring time."""
    resolved = float(value)
    if not math.isfinite(resolved):
        raise ValueError(f"constant must be finite; got {value!r} at node '{node_id}'")
    return resolved


def math_shift(
    a: Any, bars: int = 1, node_id: Optional[str] = None, issues=None
) -> np.ndarray:
    """Backward shift only: ``out[t] = a[t - bars]``, leading bars NaN.

    A forward shift would read the future, so a negative ``bars`` is refused rather than
    quietly reinterpreted.
    """
    return safe_math_apply(
        "SHIFT", (a,), options={"bars": bars}, node_id=node_id, issues=issues
    )


# ---------------------------------------------------------------------------
# LOGIC kernels - what LogicExecutor delegates to
# ---------------------------------------------------------------------------


def _as_bool_array(value: Any) -> np.ndarray:
    """Coerce to a boolean series. NaN is not true: an undefined bar never signals."""
    if isinstance(value, np.ndarray) and value.dtype == np.bool_:
        return value
    array = _as_float_array(value)
    if array.ndim == 0:
        array = np.asarray([float(array)], dtype=np.float64)
    out = np.zeros(array.shape[0], dtype=bool)
    defined = ~np.isnan(array)
    out[defined] = array[defined] != 0.0
    return out


def _align_bool(operands: Sequence[Any], node_id: Optional[str]) -> List[np.ndarray]:
    arrays = [_as_bool_array(operand) for operand in operands]
    lengths = {int(a.shape[0]) for a in arrays}
    if len(lengths) > 1:
        where = f" at node '{node_id}'" if node_id else ""
        raise ValueError(
            f"boolean operands have mismatched lengths {sorted(lengths)}{where}"
        )
    return arrays


def _compare(
    op: Callable[..., np.ndarray], left: Any, right: Any, node_id: Optional[str]
) -> np.ndarray:
    """Comparator core: an undefined bar on either side reports False, never True."""
    a, b = _align((left, right), node_id)
    undefined = np.isnan(a) | np.isnan(b)
    with np.errstate(all="ignore"):
        out = op(np.where(undefined, 0.0, a), np.where(undefined, 0.0, b))
    out = np.asarray(out, dtype=bool)
    out[undefined] = False
    return out


def logic_and(*operands: Any, node_id: Optional[str] = None) -> np.ndarray:
    """True where every input is true on the same bar."""
    return _reduce(np.logical_and, _align_bool(operands, node_id))


def logic_or(*operands: Any, node_id: Optional[str] = None) -> np.ndarray:
    """True where at least one input is true on the same bar."""
    return _reduce(np.logical_or, _align_bool(operands, node_id))


def logic_not(a: Any, node_id: Optional[str] = None) -> np.ndarray:
    """Invert a condition."""
    return np.logical_not(_as_bool_array(a))


def logic_gt(left: Any, right: Any, node_id: Optional[str] = None) -> np.ndarray:
    """True where ``left > right``."""
    return _compare(np.greater, left, right, node_id)


def logic_lt(left: Any, right: Any, node_id: Optional[str] = None) -> np.ndarray:
    """True where ``left < right``."""
    return _compare(np.less, left, right, node_id)


def logic_gte(left: Any, right: Any, node_id: Optional[str] = None) -> np.ndarray:
    """True where ``left >= right``."""
    return _compare(np.greater_equal, left, right, node_id)


def logic_lte(left: Any, right: Any, node_id: Optional[str] = None) -> np.ndarray:
    """True where ``left <= right``."""
    return _compare(np.less_equal, left, right, node_id)


def logic_eq(left: Any, right: Any, node_id: Optional[str] = None) -> np.ndarray:
    """Equality within ``EQ_TOLERANCE``.

    Exact float equality on a computed series would essentially never fire, which reads as
    a silently dead strategy rather than a bug.
    """
    a, b = _align((left, right), node_id)
    undefined = np.isnan(a) | np.isnan(b)
    delta = np.abs(np.where(undefined, 0.0, a) - np.where(undefined, 0.0, b))
    out = delta <= EQ_TOLERANCE
    out[undefined] = False
    return out


def logic_neq(left: Any, right: Any, node_id: Optional[str] = None) -> np.ndarray:
    """Inequality outside ``EQ_TOLERANCE``; an undefined bar reports False."""
    a, b = _align((left, right), node_id)
    undefined = np.isnan(a) | np.isnan(b)
    delta = np.abs(np.where(undefined, 0.0, a) - np.where(undefined, 0.0, b))
    out = delta > EQ_TOLERANCE
    out[undefined] = False
    return out


def _cross(fast: Any, slow: Any, node_id: Optional[str], above: bool) -> np.ndarray:
    a, b = _align((fast, slow), node_id)
    out = np.zeros(a.shape[0], dtype=bool)
    if a.shape[0] < 2:
        return out
    defined = ~(np.isnan(a[:-1]) | np.isnan(b[:-1]) | np.isnan(a[1:]) | np.isnan(b[1:]))
    with np.errstate(all="ignore"):
        if above:
            crossed = (a[:-1] <= b[:-1]) & (a[1:] > b[1:])
        else:
            crossed = (a[:-1] >= b[:-1]) & (a[1:] < b[1:])
    out[1:] = defined & crossed
    return out


def logic_cross_above(fast: Any, slow: Any, node_id: Optional[str] = None) -> np.ndarray:
    """True only where ``fast`` strictly crossed above ``slow`` between ``t-1`` and ``t``.

    Closed bars only. A bar whose current or previous value is NaN reports False, so the
    warmup region never signals and a strategy never fires a trade on the first bar merely
    because an indicator was undefined before it.
    """
    return _cross(fast, slow, node_id, above=True)


def logic_cross_below(fast: Any, slow: Any, node_id: Optional[str] = None) -> np.ndarray:
    """Mirror of :func:`logic_cross_above`; closed bars only, silent through warmup."""
    return _cross(fast, slow, node_id, above=False)


def logic_between(
    value: Any,
    lower: Any,
    upper: Any,
    inclusive: bool = True,
    node_id: Optional[str] = None,
) -> np.ndarray:
    """True where ``value`` sits inside the band; an undefined bar reports False."""
    v, low, high = _align((value, lower, upper), node_id)
    undefined = np.isnan(v) | np.isnan(low) | np.isnan(high)
    safe_v = np.where(undefined, 0.0, v)
    safe_low = np.where(undefined, 0.0, low)
    safe_high = np.where(undefined, 0.0, high)
    if inclusive:
        out = (safe_v >= safe_low) & (safe_v <= safe_high)
    else:
        out = (safe_v > safe_low) & (safe_v < safe_high)
    out = np.asarray(out, dtype=bool)
    out[undefined] = False
    return out


def logic_if_then_else(
    condition: Any, then_value: Any, else_value: Any, node_id: Optional[str] = None
) -> np.ndarray:
    """Pick one of two series per bar according to ``condition``."""
    then_series, else_series = _align((then_value, else_value), node_id)
    mask = _as_bool_array(condition)
    if mask.shape[0] != then_series.shape[0]:
        raise ValueError(
            f"if_then_else condition length {mask.shape[0]} does not match value length "
            f"{then_series.shape[0]} at node '{node_id}'"
        )
    return _finite_or_nan(np.where(mask, then_series, else_series))


def logic_to_signal(
    condition: Any,
    direction: str,
    strength: float = 1.0,
    node_id: Optional[str] = None,
) -> np.ndarray:
    """Turn a boolean series into a SIGNAL series within ``[-1, 1]``.

    ``direction`` has no default in the descriptor: a silent "long" would trade the exact
    opposite of a short strategy.
    """
    normalised = str(direction).lower()
    if normalised not in ("long", "short"):
        raise ValueError(
            f"to_signal direction must be 'long' or 'short'; got {direction!r} at node "
            f"'{node_id}'"
        )
    magnitude = float(strength)
    if not math.isfinite(magnitude) or not 0.0 <= magnitude <= 1.0:
        raise ValueError(
            f"to_signal strength must be within [0, 1]; got {strength!r} at node "
            f"'{node_id}'"
        )
    mask = _as_bool_array(condition)
    out = np.zeros(mask.shape[0], dtype=np.float64)
    out[mask] = magnitude if normalised == "long" else -magnitude
    return out


# ---------------------------------------------------------------------------
# DATA kernel
# ---------------------------------------------------------------------------


def order_book_imbalance(
    order_book: Mapping[str, Any], depth: int = 10
) -> Dict[str, float]:
    """Top-of-book volume imbalance from one L2 order book snapshot.

    ``order_book`` is a CCXT-shaped mapping with ``bids`` and ``asks`` as
    ``[[price, amount], ...]`` sorted best-first, which is what
    ``DataEngine.stream_order_book`` and ``DataEngine.fetch_order_book_snapshot`` yield.

    Returns one entry per output port. ``imbalance`` is
    ``(bid_volume - ask_volume) / (bid_volume + ask_volume)`` over the top ``depth``
    levels, so it lies in ``[-1, 1]``, and is NaN when both sides are empty - an empty book
    is unknown, not balanced.
    """
    levels = max(1, int(depth))
    bid_volume = _sum_levels(order_book.get("bids"), levels)
    ask_volume = _sum_levels(order_book.get("asks"), levels)
    total = bid_volume + ask_volume
    imbalance = float("nan") if total < EPSILON else (bid_volume - ask_volume) / total
    return {
        "imbalance": imbalance,
        "bid_volume": bid_volume,
        "ask_volume": ask_volume,
    }


def _sum_levels(levels: Any, depth: int) -> float:
    if not levels:
        return 0.0
    total = 0.0
    for level in list(levels)[:depth]:
        try:
            amount = float(level[1])
        except (TypeError, ValueError, IndexError):
            continue
        if math.isfinite(amount) and amount > 0:
            total += amount
    return total


# ---------------------------------------------------------------------------
# Shared port shapes, warmup functions and category adjacency
# ---------------------------------------------------------------------------


def _port(
    name: str,
    port_type: PortType,
    *,
    required: bool = True,
    variadic: bool = False,
    description: str = "",
) -> Port:
    return Port(
        name=name,
        type=port_type,
        required=required,
        variadic=variadic,
        description=description,
    )


def _series_in(name: str, description: str = "", *, variadic: bool = False) -> Port:
    return _port(
        name, PortType.SCALAR_SERIES, required=True, variadic=variadic, description=description
    )


def _bool_in(name: str, description: str = "", *, variadic: bool = False) -> Port:
    return _port(
        name, PortType.BOOLEAN_SERIES, required=True, variadic=variadic, description=description
    )


def _warmup_zero(params: Mapping[str, Any]) -> int:
    return 0


def _warmup_one(params: Mapping[str, Any]) -> int:
    """One previous closed bar is consumed before the first comparison is meaningful."""
    return 1


def _warmup_shift_bars(params: Mapping[str, Any]) -> int:
    return int(params.get("bars") or 0)


def _warmup_declared_bars(params: Mapping[str, Any]) -> int:
    """A DATA node's own warmup is only what the author explicitly asked to prefetch.

    Blank means "use the compiler's computed warmup", which is the composed figure over the
    whole downstream path and is not knowable from this node's params alone.
    """
    return int(params.get("warmup_bars") or 0)


# Category adjacency (rule R5). Port types remain the primary gate (R4); these sets stop a
# structurally meaningless neighbour before the type check has to explain it.
_SERIES_PRODUCERS: Tuple[BlockCategory, ...] = (
    BlockCategory.DATA,
    BlockCategory.INDICATOR,
    BlockCategory.MATH,
    BlockCategory.ML_DL,
)
_SERIES_CONSUMERS: Tuple[BlockCategory, ...] = (
    BlockCategory.INDICATOR,
    BlockCategory.MATH,
    BlockCategory.LOGIC,
    BlockCategory.FEATURE_ENGINEERING,
    BlockCategory.ML_DL,
)
_BOOLEAN_PRODUCERS: Tuple[BlockCategory, ...] = _SERIES_PRODUCERS + (BlockCategory.LOGIC,)
_BOOLEAN_CONSUMERS: Tuple[BlockCategory, ...] = (
    BlockCategory.LOGIC,
    BlockCategory.MATH,
    BlockCategory.ACTION,
)
_DATA_SUCCESSORS: Tuple[BlockCategory, ...] = (
    BlockCategory.INDICATOR,
    BlockCategory.MATH,
    BlockCategory.LOGIC,
    BlockCategory.FEATURE_ENGINEERING,
    BlockCategory.ML_DL,
)


# ---------------------------------------------------------------------------
# MATH_SPECS - design.md -> Math blocks
# ---------------------------------------------------------------------------


def _math_spec(
    block_id: str,
    display_name: str,
    operator: str,
    description: str,
    inputs: Tuple[Port, ...],
    *,
    runtime: str,
    params: Tuple[ParamSpec, ...] = (),
    outputs: Optional[Tuple[Port, ...]] = None,
    predecessors: Tuple[BlockCategory, ...] = _SERIES_PRODUCERS,
    successors: Tuple[BlockCategory, ...] = _SERIES_CONSUMERS,
    warmup_fn: Callable[[Mapping[str, Any]], int] = _warmup_zero,
    validate: Optional[Callable[[Mapping[str, Any]], List[str]]] = None,
) -> BlockSpec:
    return BlockSpec(
        block_id=block_id,
        display_name=display_name,
        category=BlockCategory.MATH,
        description=description,
        inputs=inputs,
        outputs=outputs or (_port("out", PortType.SCALAR_SERIES, description="Result series"),),
        params=params,
        warmup_fn=warmup_fn,
        runtime_ref=f"{MODULE_REF}.{runtime}",
        allowed_predecessor_categories=predecessors,
        allowed_successor_categories=successors,
        execution_semantics=ExecutionSemantics.SERIES_MAP,
        validate=validate,
        metadata={"operator": operator},
    )


def _validate_clamp(params: Mapping[str, Any]) -> List[str]:
    """Ranges cannot express "lower < upper"; this hook can."""
    lower, upper = params.get("lower"), params.get("upper")
    if lower is None or upper is None:
        return []
    if float(lower) >= float(upper):
        return [f"lower ({lower}) must be less than upper ({upper})"]
    return []


MATH_SPECS: Tuple[BlockSpec, ...] = (
    # -- arity 2, some variadic --------------------------------------------
    _math_spec(
        "add",
        "Add",
        "+",
        "Element-wise sum of two or more aligned series.",
        (_series_in("a", "First operand", variadic=True), _series_in("b", "Second operand")),
        runtime="math_add",
    ),
    _math_spec(
        "subtract",
        "Subtract",
        "-",
        "Element-wise a minus b.",
        (_series_in("a", "Minuend"), _series_in("b", "Subtrahend")),
        runtime="math_subtract",
    ),
    _math_spec(
        "multiply",
        "Multiply",
        "*",
        "Element-wise product of two or more aligned series.",
        (_series_in("a", "First factor", variadic=True), _series_in("b", "Second factor")),
        runtime="math_multiply",
    ),
    _math_spec(
        "divide",
        "Divide",
        "/",
        "Element-wise division. A zero denominator yields NaN for that bar, never an "
        "infinity, and the bar is reported as DIVISION_BY_ZERO.",
        (
            _series_in("numerator", "Dividend"),
            _series_in("denominator", "Divisor; a zero bar yields NaN"),
        ),
        runtime="math_divide",
    ),
    _math_spec(
        "modulo",
        "Modulo",
        "%",
        "Element-wise remainder. A zero divisor yields NaN for that bar.",
        (_series_in("a", "Dividend"), _series_in("b", "Divisor")),
        runtime="math_modulo",
    ),
    _math_spec(
        "min",
        "Minimum",
        "min",
        "Element-wise minimum across two or more aligned series.",
        (_series_in("a", "First operand", variadic=True), _series_in("b", "Second operand")),
        runtime="math_min",
    ),
    _math_spec(
        "max",
        "Maximum",
        "max",
        "Element-wise maximum across two or more aligned series.",
        (_series_in("a", "First operand", variadic=True), _series_in("b", "Second operand")),
        runtime="math_max",
    ),
    # -- arity 1 -----------------------------------------------------------
    _math_spec(
        "abs",
        "Absolute value",
        "abs",
        "Magnitude of each bar, sign discarded.",
        (_series_in("a", "Input series"),),
        runtime="math_abs",
    ),
    _math_spec(
        "round",
        "Round",
        "round",
        "Round each bar to a fixed number of decimal places.",
        (_series_in("a", "Input series"),),
        runtime="math_round",
        params=(
            ParamSpec(
                key="decimals",
                label="Decimal places",
                type=ParamType.INTEGER,
                required=True,
                default=2,
                min=0,
                max=8,
                step=1,
                unit="places",
                example=2,
                help="Number of decimal places kept. 0 rounds to whole numbers.",
            ),
        ),
    ),
    _math_spec(
        "floor",
        "Floor",
        "floor",
        "Largest integer not greater than each bar.",
        (_series_in("a", "Input series"),),
        runtime="math_floor",
    ),
    _math_spec(
        "ceil",
        "Ceiling",
        "ceil",
        "Smallest integer not less than each bar.",
        (_series_in("a", "Input series"),),
        runtime="math_ceil",
    ),
    _math_spec(
        "sqrt",
        "Square root",
        "sqrt",
        "Square root of each bar. A negative bar yields NaN and is reported as "
        "NEGATIVE_ROOT rather than raising.",
        (_series_in("a", "Input series"),),
        runtime="math_sqrt",
    ),
    _math_spec(
        "log",
        "Logarithm",
        "log",
        "Logarithm of each bar. A bar at or below zero yields NaN and is reported as "
        "NON_POSITIVE_LOG.",
        (_series_in("a", "Input series"),),
        runtime="math_log",
        params=(
            ParamSpec(
                key="base",
                label="Base",
                type=ParamType.SELECT,
                required=True,
                default="e",
                options=("e", "2", "10"),
                example="e",
                help="Natural log by default, which is what log returns use.",
            ),
        ),
    ),
    _math_spec(
        "exp",
        "Exponential",
        "exp",
        "e raised to each bar. An overflow yields NaN rather than an infinity.",
        (_series_in("a", "Input series"),),
        runtime="math_exp",
    ),
    _math_spec(
        "negate",
        "Negate",
        "neg",
        "Flip the sign of each bar.",
        (_series_in("a", "Input series"),),
        runtime="math_negate",
    ),
    _math_spec(
        "clamp",
        "Clamp",
        "clamp",
        "Constrain each bar to a closed interval.",
        (_series_in("a", "Input series"),),
        runtime="math_clamp",
        params=(
            ParamSpec(
                key="lower",
                label="Lower bound",
                type=ParamType.NUMBER,
                required=True,
                default=None,
                example=0,
                help="Bars below this are raised to it. No default: the interval is the "
                "whole point of the block.",
            ),
            ParamSpec(
                key="upper",
                label="Upper bound",
                type=ParamType.NUMBER,
                required=True,
                default=None,
                example=100,
                depends_on=("lower",),
                help="Bars above this are lowered to it. Must exceed the lower bound.",
            ),
        ),
        validate=_validate_clamp,
    ),
    # -- constants and shifts ---------------------------------------------
    _math_spec(
        "constant",
        "Constant",
        "const",
        "A single fixed value usable anywhere a series or scalar is accepted.",
        (),
        runtime="math_constant",
        outputs=(_port("value", PortType.SCALAR, description="The constant"),),
        params=(
            ParamSpec(
                key="value",
                label="Value",
                type=ParamType.NUMBER,
                required=True,
                default=None,
                example=70,
                help="The constant itself. No default: a silent zero would be a different "
                "strategy.",
            ),
        ),
        predecessors=(),
    ),
    _math_spec(
        "shift",
        "Shift (lag)",
        "shift",
        "Read the value of a series N closed bars ago. Backward only - a forward shift "
        "would read the future.",
        (_series_in("a", "Input series"),),
        runtime="math_shift",
        params=(
            ParamSpec(
                key="bars",
                label="Bars back",
                type=ParamType.INTEGER,
                required=True,
                default=1,
                min=1,
                max=500,
                step=1,
                unit="bars",
                example=1,
                help="How many closed bars back to read. Past only; negative is refused.",
                affects_warmup=True,
            ),
        ),
        warmup_fn=_warmup_shift_bars,
    ),
)


# ---------------------------------------------------------------------------
# LOGIC_SPECS - design.md -> Logic blocks
# ---------------------------------------------------------------------------


_BOOL_OUT: Tuple[Port, ...] = (
    _port("out", PortType.BOOLEAN_SERIES, description="Per-bar truth series"),
)


def _logic_spec(
    block_id: str,
    display_name: str,
    description: str,
    inputs: Tuple[Port, ...],
    outputs: Tuple[Port, ...],
    *,
    runtime: str,
    params: Tuple[ParamSpec, ...] = (),
    predecessors: Tuple[BlockCategory, ...] = _SERIES_PRODUCERS,
    successors: Tuple[BlockCategory, ...] = _BOOLEAN_CONSUMERS,
    warmup_fn: Callable[[Mapping[str, Any]], int] = _warmup_zero,
) -> BlockSpec:
    return BlockSpec(
        block_id=block_id,
        display_name=display_name,
        category=BlockCategory.LOGIC,
        description=description,
        inputs=inputs,
        outputs=outputs,
        params=params,
        warmup_fn=warmup_fn,
        runtime_ref=f"{MODULE_REF}.{runtime}",
        allowed_predecessor_categories=predecessors,
        allowed_successor_categories=successors,
        execution_semantics=ExecutionSemantics.SERIES_MAP,
    )


def _comparator_spec(
    block_id: str, display_name: str, symbol: str, runtime: str
) -> BlockSpec:
    return _logic_spec(
        block_id,
        display_name,
        f"True on each bar where left {symbol} right. A bar whose either side is undefined "
        "reports False, so the warmup region never signals.",
        (
            _series_in("left", "Left-hand series"),
            _series_in("right", "Right-hand series or constant"),
        ),
        _BOOL_OUT,
        runtime=runtime,
    )


LOGIC_SPECS: Tuple[BlockSpec, ...] = (
    # -- boolean gates -----------------------------------------------------
    _logic_spec(
        "and",
        "AND",
        "True where every input is true on the same bar.",
        (_bool_in("a", "First condition", variadic=True), _bool_in("b", "Second condition")),
        _BOOL_OUT,
        runtime="logic_and",
        predecessors=_BOOLEAN_PRODUCERS,
    ),
    _logic_spec(
        "or",
        "OR",
        "True where at least one input is true on the same bar.",
        (_bool_in("a", "First condition", variadic=True), _bool_in("b", "Second condition")),
        _BOOL_OUT,
        runtime="logic_or",
        predecessors=_BOOLEAN_PRODUCERS,
    ),
    _logic_spec(
        "not",
        "NOT",
        "Invert a condition. An undefined bar is false, so NOT of it is true only where the "
        "source is defined and false.",
        (_bool_in("a", "Condition to invert"),),
        _BOOL_OUT,
        runtime="logic_not",
        predecessors=_BOOLEAN_PRODUCERS,
    ),
    # -- comparators -------------------------------------------------------
    _comparator_spec("gt", "Greater than", ">", "logic_gt"),
    _comparator_spec("lt", "Less than", "<", "logic_lt"),
    _comparator_spec("gte", "Greater than or equal", ">=", "logic_gte"),
    _comparator_spec("lte", "Less than or equal", "<=", "logic_lte"),
    _comparator_spec("eq", "Equal", "==", "logic_eq"),
    _comparator_spec("neq", "Not equal", "!=", "logic_neq"),
    # -- crosses -----------------------------------------------------------
    _logic_spec(
        "cross_above",
        "Crosses above",
        "True only on the bar where fast strictly crossed above slow. Closed bars only, and "
        "silent while either series is undefined.",
        (
            _series_in("fast", "Series expected to cross up"),
            _series_in("slow", "Series being crossed"),
        ),
        _BOOL_OUT,
        runtime="logic_cross_above",
        warmup_fn=_warmup_one,
    ),
    _logic_spec(
        "cross_below",
        "Crosses below",
        "True only on the bar where fast strictly crossed below slow. Closed bars only, and "
        "silent while either series is undefined.",
        (
            _series_in("fast", "Series expected to cross down"),
            _series_in("slow", "Series being crossed"),
        ),
        _BOOL_OUT,
        runtime="logic_cross_below",
        warmup_fn=_warmup_one,
    ),
    # -- range and selection ----------------------------------------------
    _logic_spec(
        "between",
        "Between",
        "True where a value sits inside a band.",
        (
            _series_in("value", "Series under test"),
            _series_in("lower", "Lower bound series or constant"),
            _series_in("upper", "Upper bound series or constant"),
        ),
        _BOOL_OUT,
        runtime="logic_between",
        params=(
            ParamSpec(
                key="inclusive",
                label="Inclusive bounds",
                type=ParamType.BOOLEAN,
                required=True,
                default=True,
                example=True,
                help="Whether a value exactly on a bound counts as inside the band.",
            ),
        ),
    ),
    _logic_spec(
        "if_then_else",
        "If / then / else",
        "Pick one of two series per bar according to a condition.",
        (
            _bool_in("condition", "Which branch to take on each bar"),
            _series_in("then_value", "Value used where the condition is true"),
            _series_in("else_value", "Value used where the condition is false"),
        ),
        (_port("out", PortType.SCALAR_SERIES, description="Selected value per bar"),),
        runtime="logic_if_then_else",
        predecessors=_BOOLEAN_PRODUCERS,
        successors=_SERIES_CONSUMERS,
    ),
    # -- signal conversion -------------------------------------------------
    _logic_spec(
        "to_signal",
        "To signal",
        "Convert a condition into a directional trading signal an ACTION block accepts.",
        (_bool_in("condition", "Condition that should trade"),),
        (_port("out", PortType.SIGNAL, description="Signed intent strength within [-1, 1]"),),
        runtime="logic_to_signal",
        params=(
            ParamSpec(
                key="direction",
                label="Direction",
                type=ParamType.SELECT,
                required=True,
                default=None,
                options=("long", "short"),
                example="long",
                help="Which way to trade when the condition holds. No default: a silent "
                "'long' would trade the opposite of a short strategy.",
            ),
            ParamSpec(
                key="strength",
                label="Signal strength",
                type=ParamType.NUMBER,
                required=True,
                default=1.0,
                min=0.0,
                max=1.0,
                step=0.05,
                example=1.0,
                help="Magnitude of the emitted signal. 1.0 is full conviction.",
            ),
        ),
        predecessors=_BOOLEAN_PRODUCERS,
        successors=(BlockCategory.ACTION,),
    ),
)


# ---------------------------------------------------------------------------
# DATA descriptors - exchange-agnostic (SB-06)
# ---------------------------------------------------------------------------


def _symbol_param() -> ParamSpec:
    """The traded market. Required, never defaulted - this is the SB-06 fix.

    ``handleSaveStrategy`` previously substituted ``"BTC/USDT"`` whenever its DATA-node
    lookup missed, which it always did, so a strategy was silently saved against a market
    the author never chose.
    """
    return ParamSpec(
        key="symbol",
        label="Symbol",
        type=ParamType.SYMBOL,
        required=True,
        default=None,
        example="BTC/USDT",
        help="Market to read, chosen from the asset universe. No default: a strategy must "
        "never trade a market the author did not choose.",
    )


def _timeframe_param() -> ParamSpec:
    return ParamSpec(
        key="timeframe",
        label="Timeframe",
        type=ParamType.TIMEFRAME,
        required=True,
        default=None,
        example="15m",
        help="Bar interval, from the platform's supported timeframes. No default: the "
        "timeframe changes every downstream calculation.",
    )


def _market_type_param() -> ParamSpec:
    return ParamSpec(
        key="market_type",
        label="Market type",
        type=ParamType.SELECT,
        required=True,
        default="spot",
        options=MARKET_TYPES,
        example="spot",
        help="Market shape to read. This is not an exchange: exchange identity is bound at "
        "deployment, never saved in the strategy.",
    )


def _validate_ohlcv_history(params: Mapping[str, Any]) -> List[str]:
    """Historical mode needs a coherent window; ranges alone cannot say that."""
    issues: List[str] = []
    mode = params.get("mode")
    start, end = params.get("history_start"), params.get("history_end")
    if mode == "historical" and not start:
        issues.append("history_start is required when mode is 'historical'")
    if start and end and str(end) < str(start):
        issues.append(f"history_end ({end}) precedes history_start ({start})")
    return issues


def ohlcv_feed_descriptor() -> BlockSpec:
    """The canonical candle source.

    Deliberately declares **no** ``exchange`` parameter - not now, not ever. Market
    identity is ``symbol`` + ``timeframe`` + ``market_type``; the venue those are read from
    is a property of the deployment binding, which is what lets one saved strategy run on a
    second account without being rewritten (Requirements 12.1, 12.2, 12.3).

    Multi-output on purpose: ``frame`` for blocks that need whole candles, and one port per
    series so an indicator can be wired to ``close`` without a magic index.
    """
    return BlockSpec(
        block_id="ohlcv_feed",
        display_name="OHLCV Feed",
        category=BlockCategory.DATA,
        description="Validated candles for one market and timeframe. The exchange is bound "
        "at deployment, never stored in the strategy.",
        inputs=(),
        outputs=(
            _port("frame", PortType.OHLCV_FRAME, description="Full candle frame"),
            _port("open", PortType.PRICE_SERIES, description="Bar open"),
            _port("high", PortType.PRICE_SERIES, description="Bar high"),
            _port("low", PortType.PRICE_SERIES, description="Bar low"),
            _port("close", PortType.PRICE_SERIES, description="Bar close"),
            _port("volume", PortType.SCALAR_SERIES, description="Base volume"),
        ),
        params=(
            _symbol_param(),
            _timeframe_param(),
            _market_type_param(),
            ParamSpec(
                key="mode",
                label="Mode",
                type=ParamType.SELECT,
                required=True,
                default="streaming",
                options=("streaming", "historical"),
                example="streaming",
                help="Streaming follows live closed bars; historical reads a fixed window.",
                forward_to_runtime=False,
            ),
            ParamSpec(
                key="warmup_bars",
                label="Warmup bars",
                type=ParamType.INTEGER,
                required=False,
                default=None,
                min=0,
                max=100000,
                step=1,
                unit="bars",
                example=500,
                help="Blank = use the compiler's computed warmup, which composes every "
                "downstream lookback. Set this only to prefetch more.",
                affects_warmup=True,
                forward_to_runtime=False,
            ),
            ParamSpec(
                key="history_start",
                label="History start",
                type=ParamType.DATE,
                required=False,
                default=None,
                example="2024-01-01",
                help="First bar to read in historical mode.",
                depends_on=("mode",),
                forward_to_runtime=False,
            ),
            ParamSpec(
                key="history_end",
                label="History end",
                type=ParamType.DATE,
                required=False,
                default=None,
                example="2024-06-30",
                help="Last bar to read in historical mode. Blank runs to the latest bar.",
                depends_on=("mode", "history_start"),
                forward_to_runtime=False,
            ),
        ),
        warmup_fn=_warmup_declared_bars,
        runtime_ref="DataEngine.fetch_historical_ohlcv",
        streaming_runtime_ref="DataEngine.stream_live_ohlcv",
        allowed_predecessor_categories=(),
        allowed_successor_categories=_DATA_SUCCESSORS,
        execution_semantics=ExecutionSemantics.SERIES_MAP,
        capability_flags=("streaming", "historical"),
        validate=_validate_ohlcv_history,
        metadata={"source": "candles"},
    )


def live_ticker_descriptor() -> BlockSpec:
    """Rolling ticker for one market: last, bid, ask and 24h volume.

    No ``timeframe``: a ticker is not bar-aligned, so publishing a timeframe parameter here
    would be a control the platform cannot honour. Blocks that need bars use ``ohlcv_feed``.
    """
    return BlockSpec(
        block_id="live_ticker",
        display_name="Live Ticker",
        category=BlockCategory.DATA,
        description="Live top-of-book and 24h rolling statistics for one market. Exchange "
        "bound at deployment.",
        inputs=(),
        outputs=(
            _port("last", PortType.PRICE_SERIES, description="Last traded price"),
            _port("bid", PortType.PRICE_SERIES, description="Best bid"),
            _port("ask", PortType.PRICE_SERIES, description="Best ask"),
            _port("volume", PortType.SCALAR_SERIES, description="24h base volume"),
        ),
        params=(
            _symbol_param(),
            _market_type_param(),
        ),
        warmup_fn=_warmup_zero,
        runtime_ref="DataEngine.fetch_ticker_snapshot",
        streaming_runtime_ref="DataEngine.stream_ticker",
        allowed_predecessor_categories=(),
        allowed_successor_categories=_DATA_SUCCESSORS,
        execution_semantics=ExecutionSemantics.STATEFUL,
        capability_flags=("streaming",),
        metadata={"source": "ticker"},
    )


def orderbook_imbalance_descriptor() -> BlockSpec:
    """Top-of-book volume imbalance for one market.

    ``imbalance`` is bounded in ``[-1, 1]`` and is NaN while the book is empty on both
    sides, so a missing book reads as unknown rather than as balanced.
    """
    return BlockSpec(
        block_id="orderbook_imbalance",
        display_name="Order Book Imbalance",
        category=BlockCategory.DATA,
        description="Signed bid/ask volume imbalance over the top N levels of the L2 book.",
        inputs=(),
        outputs=(
            _port(
                "imbalance",
                PortType.SCALAR_SERIES,
                description="(bid - ask) / (bid + ask) over the sampled depth, in [-1, 1]",
            ),
            _port("bid_volume", PortType.SCALAR_SERIES, description="Summed bid depth"),
            _port("ask_volume", PortType.SCALAR_SERIES, description="Summed ask depth"),
        ),
        params=(
            _symbol_param(),
            _market_type_param(),
            ParamSpec(
                key="depth",
                label="Book depth",
                type=ParamType.INTEGER,
                required=True,
                default=10,
                min=1,
                max=50,
                step=1,
                unit="levels",
                example=10,
                help="How many price levels per side are summed.",
            ),
        ),
        warmup_fn=_warmup_zero,
        runtime_ref=f"{MODULE_REF}.order_book_imbalance",
        streaming_runtime_ref="DataEngine.stream_order_book",
        allowed_predecessor_categories=(),
        allowed_successor_categories=_DATA_SUCCESSORS,
        execution_semantics=ExecutionSemantics.STATEFUL,
        capability_flags=("streaming",),
        metadata={"source": "order_book"},
    )


DATA_SPECS: Tuple[BlockSpec, ...] = (
    ohlcv_feed_descriptor(),
    live_ticker_descriptor(),
    orderbook_imbalance_descriptor(),
)


# ---------------------------------------------------------------------------
# ACTION descriptors - generated from exchange_executor.OrderType
# ---------------------------------------------------------------------------


def _signal_input() -> Port:
    """The only input an ACTION block has.

    Declared ``SIGNAL``; ``BOOLEAN_SERIES`` is compatible with ``SIGNAL`` in the port
    compatibility matrix, so a bare comparator can feed an action directly - which is what
    makes the common two-block strategy possible without ceremony. Stage 9
    (``ACTION_INPUT_PROVENANCE``) still rejects an action fed straight from an indicator or a
    model.
    """
    return _port(
        "signal",
        PortType.SIGNAL,
        required=True,
        description="Signal or condition that triggers the order",
    )


def _quantity_type_param(options: Tuple[str, ...] = QUANTITY_TYPES) -> ParamSpec:
    return ParamSpec(
        key="quantity_type",
        label="Size expressed as",
        type=ParamType.SELECT,
        required=True,
        default=None,
        options=options,
        example="percent_of_equity",
        help="How the order size is expressed. No default: a silent sizing convention is a "
        "financial-safety defect.",
    )


def _quantity_param() -> ParamSpec:
    return ParamSpec(
        key="quantity",
        label="Size",
        type=ParamType.NUMBER,
        required=True,
        default=None,
        min=0,
        unit="depends on quantity_type",
        example=0.25,
        depends_on=("quantity_type",),
        help="Order size in the unit chosen above. No default: a silent default position "
        "size is a financial-safety defect, so the builder refuses to save without it.",
    )


def _price_param() -> ParamSpec:
    return ParamSpec(
        key="price",
        label="Limit price",
        type=ParamType.NUMBER,
        required=True,
        default=None,
        min=0,
        example=65000,
        depends_on=("price_mode",),
        help="Absolute price, or offset in basis points, per the price mode.",
    )


def _price_mode_param() -> ParamSpec:
    return ParamSpec(
        key="price_mode",
        label="Price mode",
        type=ParamType.SELECT,
        required=True,
        default="absolute",
        options=("absolute", "offset_bps"),
        example="absolute",
        help="Whether the limit price is an absolute level or an offset from the reference "
        "price in basis points.",
    )


def _trigger_price_param() -> ParamSpec:
    return ParamSpec(
        key="trigger_price",
        label="Trigger price",
        type=ParamType.NUMBER,
        required=True,
        default=None,
        min=0,
        example=61000,
        depends_on=("trigger_price_mode",),
        help="Price at which the order activates. No default: the trigger is the order.",
    )


def _trigger_price_mode_param() -> ParamSpec:
    return ParamSpec(
        key="trigger_price_mode",
        label="Trigger price mode",
        type=ParamType.SELECT,
        required=True,
        default="absolute",
        options=("absolute", "offset_bps"),
        example="absolute",
        help="Whether the trigger price is an absolute level or an offset from the reference "
        "price in basis points.",
    )


def _limit_price_param() -> ParamSpec:
    return ParamSpec(
        key="limit_price",
        label="Limit price after trigger",
        type=ParamType.NUMBER,
        required=True,
        default=None,
        min=0,
        example=60800,
        depends_on=("trigger_price",),
        help="Price the resting order is placed at once the trigger fires.",
    )


def _time_in_force_param(default: Optional[str] = None) -> ParamSpec:
    return ParamSpec(
        key="time_in_force",
        label="Time in force",
        type=ParamType.SELECT,
        required=False,
        default=default,
        options=("GTC", "IOC", "FOK", "PO"),
        example="GTC",
        help="How long the order stays live. Blank uses the venue default resolved at "
        "execution.",
    )


def _reduce_only_param(default: bool = False) -> ParamSpec:
    return ParamSpec(
        key="reduce_only",
        label="Reduce only",
        type=ParamType.BOOLEAN,
        required=False,
        default=default,
        example=default,
        help="When set, the order can only shrink an open position, never open exposure.",
    )


def _post_only_param() -> ParamSpec:
    return ParamSpec(
        key="post_only",
        label="Post only",
        type=ParamType.BOOLEAN,
        required=False,
        default=False,
        example=False,
        help="Reject the order rather than take liquidity.",
    )


def _client_tag_param() -> ParamSpec:
    return ParamSpec(
        key="client_tag",
        label="Client tag",
        type=ParamType.TEXT,
        required=False,
        default=None,
        example="breakout-entry",
        help="Free-text label carried on the order for your own reporting.",
    )


def _action_spec(
    block_id: str,
    display_name: str,
    description: str,
    order_type_value: str,
    params: Tuple[ParamSpec, ...],
    *,
    side: Optional[str],
    intent: str,
    reduce_only_forced: bool = False,
) -> BlockSpec:
    """Assemble one ACTION descriptor.

    Every ACTION descriptor produced here is TERMINAL with no outputs and an empty successor
    set, carries no traded-asset parameter, and declares ``quantity_type`` / ``quantity`` as
    required with no default. ``BlockSpec.__post_init__`` enforces the first two structurally
    and ``ParamSpec.__post_init__`` the third, so a future edit cannot quietly relax them.
    """
    return BlockSpec(
        block_id=block_id,
        display_name=display_name,
        category=BlockCategory.ACTION,
        description=description,
        inputs=(_signal_input(),),
        outputs=(),
        params=params,
        warmup_fn=_warmup_zero,
        runtime_ref="CCXTExchangeExecutor.place_order",
        allowed_predecessor_categories=(BlockCategory.LOGIC,),
        allowed_successor_categories=(),
        execution_semantics=ExecutionSemantics.TERMINAL,
        capability_flags=("places_order",),
        metadata={
            "order_type": order_type_value,
            # None means the side is resolved from the open position at execution time:
            # these are exit orders, and an exit's side is the inverse of what is held.
            "side": side,
            "intent": intent,
            "reduce_only_forced": reduce_only_forced,
        },
    )


def action_descriptors_for(order_type: Any) -> Tuple[BlockSpec, ...]:
    """The ACTION descriptors for one ``exchange_executor.OrderType`` member.

    Keyed on the enum's *value* so a caller may pass the member or the string. An order type
    with no variant table entry raises, which is what makes
    :func:`_assert_order_type_coverage` a real guard rather than a comment.
    """
    value = getattr(order_type, "value", order_type)
    try:
        builders = _ACTION_VARIANTS[str(value)]
    except KeyError:
        raise ValueError(
            f"order type '{value}' has no ACTION descriptor variant. exchange_executor "
            "supports it, so the palette must expose it: add a variant to _ACTION_VARIANTS."
        ) from None
    specs: List[BlockSpec] = []
    for build in builders:
        specs.extend(build())
    return tuple(specs)


def _market_actions() -> Tuple[BlockSpec, ...]:
    common: Tuple[ParamSpec, ...] = (
        _quantity_type_param(),
        _quantity_param(),
        _time_in_force_param(),
        _reduce_only_param(False),
        _client_tag_param(),
    )
    return (
        _action_spec(
            "action_buy_market",
            "Buy (market)",
            "Buy immediately at the best available price when the signal fires.",
            "market",
            common,
            side="buy",
            intent="entry",
        ),
        _action_spec(
            "action_sell_market",
            "Sell (market)",
            "Sell immediately at the best available price when the signal fires.",
            "market",
            common,
            side="sell",
            intent="entry",
        ),
        _action_spec(
            "action_close_position",
            "Close position",
            "Reduce or flatten the open position for the traded market. Never opens "
            "exposure: the order is always reduce-only and its side is the inverse of what "
            "is held.",
            "market",
            (
                _quantity_type_param(CLOSE_QUANTITY_TYPES),
                _quantity_param(),
                _client_tag_param(),
            ),
            side=None,
            intent="exit",
            reduce_only_forced=True,
        ),
    )


def _limit_actions() -> Tuple[BlockSpec, ...]:
    common: Tuple[ParamSpec, ...] = (
        _quantity_type_param(),
        _quantity_param(),
        _price_mode_param(),
        _price_param(),
        _time_in_force_param("GTC"),
        _post_only_param(),
        _reduce_only_param(False),
        _client_tag_param(),
    )
    return (
        _action_spec(
            "action_buy_limit",
            "Buy (limit)",
            "Rest a buy order at your price when the signal fires.",
            "limit",
            common,
            side="buy",
            intent="entry",
        ),
        _action_spec(
            "action_sell_limit",
            "Sell (limit)",
            "Rest a sell order at your price when the signal fires.",
            "limit",
            common,
            side="sell",
            intent="entry",
        ),
    )


def _stop_market_actions() -> Tuple[BlockSpec, ...]:
    return (
        _action_spec(
            "action_stop_market",
            "Stop (market)",
            "Exit at market once price reaches the trigger. Defaults to reduce-only so a "
            "protective stop cannot open new exposure.",
            "stop_market",
            (
                _quantity_type_param(),
                _quantity_param(),
                _trigger_price_mode_param(),
                _trigger_price_param(),
                _reduce_only_param(True),
                _client_tag_param(),
            ),
            side=None,
            intent="exit",
        ),
    )


def _stop_limit_actions() -> Tuple[BlockSpec, ...]:
    return (
        _action_spec(
            "action_stop_limit",
            "Stop (limit)",
            "Place a limit order once price reaches the trigger. Defaults to reduce-only.",
            "stop_limit",
            (
                _quantity_type_param(),
                _quantity_param(),
                _trigger_price_mode_param(),
                _trigger_price_param(),
                _limit_price_param(),
                _time_in_force_param("GTC"),
                _reduce_only_param(True),
                _client_tag_param(),
            ),
            side=None,
            intent="exit",
        ),
    )


def _take_profit_market_actions() -> Tuple[BlockSpec, ...]:
    return (
        _action_spec(
            "action_take_profit_market",
            "Take profit (market)",
            "Exit at market once price reaches the profit trigger. Defaults to reduce-only.",
            "take_profit_market",
            (
                _quantity_type_param(),
                _quantity_param(),
                _trigger_price_mode_param(),
                _trigger_price_param(),
                _reduce_only_param(True),
                _client_tag_param(),
            ),
            side=None,
            intent="exit",
        ),
    )


def _take_profit_limit_actions() -> Tuple[BlockSpec, ...]:
    return (
        _action_spec(
            "action_take_profit_limit",
            "Take profit (limit)",
            "Place a limit order once price reaches the profit trigger. Defaults to "
            "reduce-only.",
            "take_profit_limit",
            (
                _quantity_type_param(),
                _quantity_param(),
                _trigger_price_mode_param(),
                _trigger_price_param(),
                _limit_price_param(),
                _time_in_force_param("GTC"),
                _reduce_only_param(True),
                _client_tag_param(),
            ),
            side=None,
            intent="exit",
        ),
    )


#: order type value -> the descriptor variants it produces. Keyed by the *value* of the
#: real ``exchange_executor.OrderType`` members; coverage is asserted, never assumed.
_ACTION_VARIANTS: Dict[str, Tuple[Callable[[], Tuple[BlockSpec, ...]], ...]] = {
    "market": (_market_actions,),
    "limit": (_limit_actions,),
    "stop_market": (_stop_market_actions,),
    "stop_limit": (_stop_limit_actions,),
    "take_profit_market": (_take_profit_market_actions,),
    "take_profit_limit": (_take_profit_limit_actions,),
}


def supported_order_types() -> Tuple[Any, ...]:
    """The real ``exchange_executor.OrderType`` members, imported lazily.

    Imported here rather than at module scope so that declaring a descriptor does not drag
    CCXT into a process that only needs the schema, and so this module stays importable in
    an environment where CCXT is absent.
    """
    from backend_app.backend.exchange_executor import OrderType

    return tuple(OrderType)


def _assert_order_type_coverage(order_types: Sequence[Any]) -> None:
    """Every supported order type must produce at least one descriptor, and vice versa.

    This is the structural guard behind Requirement 4.10: the palette cannot advertise an
    order type the execution layer cannot place, and cannot silently omit one the execution
    layer gained.
    """
    supported = {str(getattr(item, "value", item)) for item in order_types}
    declared = set(_ACTION_VARIANTS)
    missing = sorted(supported - declared)
    if missing:
        raise ValueError(
            f"exchange_executor.OrderType supports {missing} but no ACTION descriptor "
            "variant is declared for them; the palette would silently omit a placeable "
            "order type"
        )
    extra = sorted(declared - supported)
    if extra:
        raise ValueError(
            f"ACTION descriptor variants {extra} name order types exchange_executor does "
            "not support; the palette would advertise an unplaceable order"
        )


def action_specs(order_types: Optional[Sequence[Any]] = None) -> Tuple[BlockSpec, ...]:
    """Every ACTION descriptor, generated from the real ``OrderType`` enum.

    Order types are read from ``exchange_executor`` rather than restated here, so an order
    type the executor does not support cannot appear in the palette (Requirement 4.10).
    """
    resolved = tuple(order_types) if order_types is not None else supported_order_types()
    _assert_order_type_coverage(resolved)
    specs: List[BlockSpec] = []
    for order_type in resolved:
        specs.extend(action_descriptors_for(order_type))
    return tuple(specs)


# ---------------------------------------------------------------------------
# Assembly, lookup and parameter validation
# ---------------------------------------------------------------------------

#: The three families that need no engine import, indexed for cheap lookup. ACTION is not
#: included because generating it reads ``exchange_executor.OrderType``; use
#: :func:`all_block_specs` or :func:`action_specs` for the full set.
STATIC_SPECS: Tuple[BlockSpec, ...] = DATA_SPECS + MATH_SPECS + LOGIC_SPECS

STATIC_SPECS_BY_ID: Dict[str, BlockSpec] = {spec.block_id: spec for spec in STATIC_SPECS}

if len(STATIC_SPECS_BY_ID) != len(STATIC_SPECS):
    _seen: Dict[str, int] = {}
    for _spec in STATIC_SPECS:
        _seen[_spec.block_id] = _seen.get(_spec.block_id, 0) + 1
    raise ValueError(
        "duplicate block_id in block_specs: "
        f"{sorted(block_id for block_id, count in _seen.items() if count > 1)}"
    )


def all_block_specs(order_types: Optional[Sequence[Any]] = None) -> Tuple[BlockSpec, ...]:
    """DATA + MATH + LOGIC + ACTION, in palette order.

    ``registry.build_registry()`` consumes this alongside ``INDICATOR_SPECS``,
    ``FEATURE_SPECS`` and ``MODEL_SPECS``. Every ``block_id`` is unique across the four
    families; the assertion below fails loudly rather than letting one family shadow
    another's block.
    """
    specs = DATA_SPECS + MATH_SPECS + LOGIC_SPECS + action_specs(order_types)
    seen: Dict[str, BlockSpec] = {}
    for spec in specs:
        if spec.block_id in seen:
            raise ValueError(
                f"duplicate block_id '{spec.block_id}' across block_specs families"
            )
        seen[spec.block_id] = spec
    return specs


def get_block_spec(block_id: str) -> BlockSpec:
    """Look up one descriptor. Raises ``KeyError`` for an unknown block.

    ACTION descriptors are generated on demand, so this consults the static index first and
    falls back to the generated ACTION set.
    """
    spec = STATIC_SPECS_BY_ID.get(block_id)
    if spec is not None:
        return spec
    for candidate in action_specs():
        if candidate.block_id == block_id:
            return candidate
    raise KeyError(block_id)


def specs_in_category(category: BlockCategory) -> Tuple[BlockSpec, ...]:
    """Every descriptor this module declares for ``category``."""
    if category is BlockCategory.ACTION:
        return action_specs()
    return tuple(spec for spec in STATIC_SPECS if spec.category is category)


def validate_block_params(spec: BlockSpec, params: Mapping[str, Any]) -> List[str]:
    """Check one node's params against its descriptor.

    Returns human-readable problems; an empty list means the params are acceptable. Required
    flags, option sets and ranges come from the same ``ParamSpec`` objects the UI form was
    generated from, so the form and the backend cannot diverge (Requirement 5.7). Each
    message names the field, the expected constraint and the received value (Requirement
    5.8).
    """
    issues: List[str] = []

    for param in spec.params:
        value = params.get(param.key)

        if value is None:
            if param.required and param.default is None:
                issues.append(
                    f"{spec.block_id}.{param.key} is required and has no default; "
                    f"received {value!r}"
                )
            continue

        values = list(value) if isinstance(value, (list, tuple)) else [value]

        if param.options is not None:
            unknown = [item for item in values if item not in param.options]
            if unknown:
                issues.append(
                    f"{spec.block_id}.{param.key} expects one of {list(param.options)}; "
                    f"received {unknown}"
                )

        if param.type in (ParamType.NUMBER, ParamType.INTEGER, ParamType.MULTISELECT):
            for item in values:
                if isinstance(item, bool) or not isinstance(item, (int, float)):
                    if param.type is not ParamType.MULTISELECT:
                        issues.append(
                            f"{spec.block_id}.{param.key} expects a "
                            f"{param.type.value.lower()}; received {item!r}"
                        )
                    continue
                if param.type is ParamType.INTEGER and float(item) != int(item):
                    issues.append(
                        f"{spec.block_id}.{param.key} expects a whole number; "
                        f"received {item!r}"
                    )
                if param.min is not None and item < param.min:
                    issues.append(
                        f"{spec.block_id}.{param.key} expects at least {param.min}; "
                        f"received {item!r}"
                    )
                if param.max is not None and item > param.max:
                    issues.append(
                        f"{spec.block_id}.{param.key} expects at most {param.max}; "
                        f"received {item!r}"
                    )

        if param.type is ParamType.BOOLEAN and not isinstance(value, bool):
            issues.append(
                f"{spec.block_id}.{param.key} expects a boolean; received {value!r}"
            )

    unknown_keys = sorted(
        key for key in params if spec.param(key) is None
    )
    if unknown_keys:
        issues.append(
            f"{spec.block_id} received parameters it does not declare: {unknown_keys}"
        )

    if spec.validate is not None:
        issues.extend(f"{spec.block_id}: {problem}" for problem in spec.validate(params))

    return issues
