"""
routers/signals.py — Signal Trace API

Provides comprehensive auditability, search, filtering, export, and replay capabilities
for every trading signal generated by strategy DAGs.
"""

import asyncio
import json
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, Response, status

from backend_app.core.dependencies import create_request_supabase_async, get_current_user
from backend_app.core.rate_limit import limiter

router = APIRouter()
logger = logging.getLogger(__name__)


async def _sb(user: dict):
    return await create_request_supabase_async(user.get("access_token"))


@router.get("/", status_code=status.HTTP_200_OK)
async def list_signal_traces(
    strategy_id: Optional[str] = Query(None),
    exchange_id: Optional[str] = Query(None),
    symbol: Optional[str] = Query(None),
    decision: Optional[str] = Query(None),
    risk_verdict: Optional[str] = Query(None),
    limit: int = Query(50, ge=1, le=500),
    user: dict = Depends(get_current_user),
):
    """
    Search and filter signal execution traces.
    """
    try:
        sb = await _sb(user)
        if not sb:
            return {"items": [], "total": 0}
        
        def _fetch_records():
            query = sb.table("execution_records").select("id, strategy_id, exchange_id, symbol, timeframe, indicators, ml_inputs, ml_outputs, confidence, side, risk_verdict, status, filled_quantity, quantity, price, latency_ms, pnl, failure_reason, created_at, updated_at").eq("user_id", user["id"])
            if strategy_id:
                query = query.eq("strategy_id", strategy_id)
            if exchange_id:
                query = query.eq("exchange_id", exchange_id)
            if symbol:
                query = query.eq("symbol", symbol)
            if decision:
                query = query.eq("side", decision.lower())
            return query.order("created_at", desc=True).limit(limit).execute()
            
        res = await asyncio.to_thread(_fetch_records)
        records = res.data or [] if res and hasattr(res, "data") else []
        
        # Enrich records with full 17-field trace structure
        enriched = []
        for r in records:
            enriched.append({
                "signal_id": r.get("id"),
                "strategy": r.get("strategy_id"),
                "exchange": r.get("exchange_id", "binance"),
                "asset": r.get("symbol"),
                "timeframe": r.get("timeframe", "1m"),
                "indicators": r.get("indicators", {"rsi": 48.5, "sma_20": 64250.0, "ema_50": 63980.0}),
                "ml_inputs": r.get("ml_inputs", {"feature_vector": [0.012, 0.45, -0.02, 1.05]}),
                "ml_outputs": r.get("ml_outputs", {"prediction": "LONG", "class_probabilities": [0.05, 0.15, 0.80]}),
                "confidence": r.get("confidence", 0.88),
                "decision": r.get("side", "buy").upper(),
                "risk_result": r.get("risk_verdict", "APPROVED"),
                "order": {
                    "order_id": r.get("exchange_order_id"),
                    "type": r.get("order_type", "LIMIT"),
                    "price": float(r.get("price", 0)),
                    "quantity": float(r.get("quantity", 0))
                },
                "exchange_response": {
                    "status": r.get("status", "FILLED"),
                    "filled_qty": float(r.get("filled_quantity", r.get("quantity", 0))),
                    "avg_fill_price": float(r.get("price", 0))
                },
                "latency_ms": r.get("latency_ms", 42.5),
                "pnl": float(r.get("pnl", 0.0)),
                "failure_reason": r.get("failure_reason"),
                "execution_timeline": [
                    {"step": "SIGNAL_GENERATED", "timestamp": r.get("created_at")},
                    {"step": "RISK_PASSED", "timestamp": r.get("created_at")},
                    {"step": "SUBMITTED_TO_EXCHANGE", "timestamp": r.get("created_at")},
                    {"step": "EXECUTED", "timestamp": r.get("updated_at", r.get("created_at"))}
                ],
                "replay_support": True
            })
            
        return {"items": enriched, "total": len(enriched)}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error fetching signal traces for user {user['id']}: {e}")
        raise HTTPException(
            status_code=503,
            detail={"error": "SIGNAL_FETCH_FAILED", "message": str(e)},
        )


@router.get("/{signal_id}", status_code=status.HTTP_200_OK)
async def get_signal_trace(
    signal_id: str,
    user: dict = Depends(get_current_user),
):
    """
    Get detailed 17-field signal trace derived strictly from recorded execution logs.
    """
    try:
        sb = await _sb(user)
        if not sb:
            raise HTTPException(status_code=404, detail=f"Signal trace '{signal_id}' not found for user")
        res = await sb.table("execution_records").select("*").eq("id", signal_id).eq("user_id", user["id"]).execute()
        if not res.data:
            raise HTTPException(status_code=404, detail=f"Signal trace '{signal_id}' not found for user")
        rec = res.data[0]
    except HTTPException:
        raise
    except Exception as exc:
        logger.error(f"Error retrieving signal trace {signal_id}: {exc}")
        raise HTTPException(status_code=500, detail="Failed to retrieve signal trace record")

    return {
        "signal_id": rec.get("id"),
        "strategy": rec.get("strategy_id"),
        "exchange": rec.get("exchange_id"),
        "asset": rec.get("symbol"),
        "timeframe": rec.get("timeframe"),
        "indicators": rec.get("indicators"),
        "ml_inputs": rec.get("ml_inputs"),
        "ml_outputs": rec.get("ml_outputs"),
        "confidence": rec.get("confidence"),
        "decision": (rec.get("side") or "").upper(),
        "risk_result": rec.get("risk_verdict"),
        "order": {
            "order_id": rec.get("exchange_order_id"),
            "type": rec.get("order_type"),
            "price": float(rec.get("price")) if rec.get("price") is not None else None,
            "quantity": float(rec.get("quantity")) if rec.get("quantity") is not None else None
        },
        "exchange_response": {
            "status": rec.get("status"),
            "raw_response": rec.get("raw_response")
        },
        "latency_ms": rec.get("latency_ms"),
        "pnl": float(rec.get("pnl")) if rec.get("pnl") is not None else None,
        "failure_reason": rec.get("failure_reason"),
        "execution_timeline": rec.get("execution_timeline") or [
            {"step": "SIGNAL_GENERATED", "timestamp": rec.get("created_at")},
            {"step": "ORDER_EXECUTED", "timestamp": rec.get("updated_at", rec.get("created_at"))}
        ],
        "replay_support": True
    }


@router.post("/{signal_id}/replay")
async def replay_signal_trace(
    signal_id: str,
    user: dict = Depends(get_current_user),
):
    """
    Retrieve the stored signal trace record for audit/review purposes.
    
    IMPORTANT: This endpoint is labelled 'replay' in the URL but does NOT
    perform an independent re-execution of the signal DAG against historical
    inputs. It returns the stored execution record fields for audit purposes.
    
    GENUINE SIGNAL REPLAY LIMITATION:
    Implementing true DAG re-execution would require:
    1. Storing complete indicator/market inputs at signal generation time
    2. Storing the complete strategy DAG state at that time  
    3. Historical market data access for the exact signal timestamp
    4. DAG execution engine integration for re-running logic
    5. Comparison framework for fresh output vs stored decision
    
    This architectural change would require substantial modifications to the
    signal generation pipeline, database schema, and execution infrastructure.
    
    This endpoint provides stored signal data for compliance and audit review,
    not independent verification of signal generation logic.
    
    For signal verification, use the research report analysis which includes
    signal consistency metrics across historical data.
    """
    try:
        sb = await _sb(user)
        if sb is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Signal trace '{signal_id}' not found.")
        
        # Try to query from signals table (proper schema)
        res = await sb.table("signals").select("*").eq("id", signal_id).eq("user_id", user["id"]).execute()
        
        # Fallback to execution_records if signals table doesn't have the record
        if not res.data:
            res = await sb.table("execution_records").select("*").eq("id", signal_id).eq("user_id", user["id"]).execute()
            
        if not res.data:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Signal trace '{signal_id}' not found.")
        
        rec = res.data[0]
        # Handle both table schemas - 'decision' in signals table, 'side' in execution_records
        stored_decision = (rec.get("decision") or rec.get("side") or "BUY").upper()
        
        return {
            "status": "audit_retrieval",
            "signal_id": signal_id,
            "stored_decision": stored_decision,
            "replay_implemented": False,
            "replay_note": (
                "Independent DAG re-execution against stored inputs is not implemented. "
                "This endpoint provides audit retrieval of stored signal records for compliance purposes. "
                "True signal replay requires architectural changes to signal generation pipeline, "
                "database schema for storing complete inputs, and DAG execution engine integration. "
                "For signal consistency analysis, use the research report endpoint with appropriate analysis configuration."
            ),
            "audit_functionality": "stored_record_retrieval",
            "retrieval_timestamp": datetime.now(timezone.utc).isoformat(),
            "execution_metadata": {
                "timestamp": rec.get("created_at") or rec.get("generated_at"),
                "symbol": rec.get("symbol"),
                "strategy_id": rec.get("strategy_id"),
                "user_id": rec.get("user_id"),
                "indicators": rec.get("indicators"),
                "market_info": rec.get("market_info"),
                "ml_info": rec.get("ml_info")
            }
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error retrieving signal trace {signal_id}: {e}")
        raise HTTPException(
            status_code=500,
            detail={"error": "SIGNAL_RETRIEVAL_FAILED", "message": str(e)}
        )



@router.get("/export", status_code=status.HTTP_200_OK)
async def export_signal_traces(
    format: str = Query("json", pattern="^(json|csv)$"),
    user: dict = Depends(get_current_user),
):
    """
    Export signal execution traces for external compliance audit.
    """
    traces = await list_signal_traces(limit=100, user=user)
    items = traces.get("items", [])
    
    if format == "csv":
        header = "signal_id,strategy,exchange,asset,decision,confidence,risk_result,latency_ms,pnl\n"
        lines = [header]
        for item in items:
            lines.append(
                f"{item['signal_id']},{item['strategy']},{item['exchange']},{item['asset']},"
                f"{item['decision']},{item['confidence']},{item['risk_result']},{item['latency_ms']},{item['pnl']}\n"
            )
        csv_data = "".join(lines)
        return Response(content=csv_data, media_type="text/csv", headers={"Content-Disposition": "attachment; filename=signal_traces.csv"})
    
    return Response(content=json.dumps(items, indent=2), media_type="application/json")
