"""baseline

Revision ID: 4ef23035a692
Revises: 
Create Date: 2026-06-16 21:03:10.680058

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4ef23035a692'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute('DROP INDEX IF EXISTS ix_transaction_rollbacks_tenant_id CASCADE')
        op.execute('DROP INDEX IF EXISTS ix_transaction_rollbacks_transaction_id CASCADE')
        op.execute('DROP TABLE IF EXISTS transaction_rollbacks CASCADE')
        op.execute('DROP INDEX IF EXISTS ix_orders_tenant_id CASCADE')
        op.execute('DROP TABLE IF EXISTS orders CASCADE')
        op.execute('DROP INDEX IF EXISTS ix_transaction_checkpoints_tenant_id CASCADE')
        op.execute('DROP INDEX IF EXISTS ix_transaction_checkpoints_transaction_id CASCADE')
        op.execute('DROP TABLE IF EXISTS transaction_checkpoints CASCADE')
        op.execute('DROP INDEX IF EXISTS ix_transaction_records_tenant_id CASCADE')
        op.execute('DROP TABLE IF EXISTS transaction_records CASCADE')
        op.execute('DROP INDEX IF EXISTS ix_positions_tenant_id CASCADE')
        op.execute('DROP TABLE IF EXISTS positions CASCADE')
        op.execute('DROP TABLE IF EXISTS idempotency_keys CASCADE')
        op.execute('DROP INDEX IF EXISTS ix_fills_tenant_id CASCADE')
        op.execute('DROP TABLE IF EXISTS fills CASCADE')
    else:
        op.execute('DROP INDEX IF EXISTS ix_transaction_rollbacks_tenant_id')
        op.execute('DROP INDEX IF EXISTS ix_transaction_rollbacks_transaction_id')
        op.execute('DROP TABLE IF EXISTS transaction_rollbacks')
        op.execute('DROP INDEX IF EXISTS ix_orders_tenant_id')
        op.execute('DROP TABLE IF EXISTS orders')
        op.execute('DROP INDEX IF EXISTS ix_transaction_checkpoints_tenant_id')
        op.execute('DROP INDEX IF EXISTS ix_transaction_checkpoints_transaction_id')
        op.execute('DROP TABLE IF EXISTS transaction_checkpoints')
        op.execute('DROP INDEX IF EXISTS ix_transaction_records_tenant_id')
        op.execute('DROP TABLE IF EXISTS transaction_records')
        op.execute('DROP INDEX IF EXISTS ix_positions_tenant_id')
        op.execute('DROP TABLE IF EXISTS positions')
        op.execute('DROP TABLE IF EXISTS idempotency_keys')
        op.execute('DROP INDEX IF EXISTS ix_fills_tenant_id')
        op.execute('DROP TABLE IF EXISTS fills')
    
    # Only create index if table exists (dag_tasks doesn't exist either so this would fail)
    # op.execute('CREATE INDEX IF NOT EXISTS ix_dag_tasks_worker_id ON dag_tasks (worker_id)')
    
    # execution_records does not exist, so alter/drop columns will fail.
    # reconciliation_mismatches does not exist.
    # The safest Alembic equivalent is to leave these out since the tables don't exist in PostgreSQL.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reconciliation_mismatches', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('execution_records', sa.Column('signal_id', sa.VARCHAR(length=128), nullable=True))
    op.add_column('execution_records', sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('execution_records', sa.Column('idempotency_key', sa.VARCHAR(length=128), nullable=True))
    op.alter_column('execution_records', 'task_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('execution_records', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_dag_tasks_worker_id'), table_name='dag_tasks')
    op.create_table('fills',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_tenant_id'), 'fills', ['tenant_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('idempotency_key', sa.VARCHAR(length=128), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('idempotency_key', 'tenant_id')
    )
    op.create_table('positions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_tenant_id'), 'positions', ['tenant_id'], unique=False)
    op.create_table('transaction_records',
    sa.Column('transaction_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('state', sa.VARCHAR(length=32), nullable=True),
    sa.Column('operations_count', sa.INTEGER(), nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transaction_records_tenant_id'), 'transaction_records', ['tenant_id'], unique=False)
    op.create_table('transaction_checkpoints',
    sa.Column('checkpoint_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('state_snapshot', sqlite.JSON(), nullable=True),
    sa.Column('operations_snapshot', sqlite.JSON(), nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_index(op.f('ix_transaction_checkpoints_transaction_id'), 'transaction_checkpoints', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transaction_checkpoints_tenant_id'), 'transaction_checkpoints', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('transaction_rollbacks',
    sa.Column('rollback_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('checkpoint_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('rollback_id')
    )
    op.create_index(op.f('ix_transaction_rollbacks_transaction_id'), 'transaction_rollbacks', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transaction_rollbacks_tenant_id'), 'transaction_rollbacks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
