"""execution schema rebuild

Revision ID: d97ffff9c3bb
Revises: 4ef23035a692
Create Date: 2026-06-17 16:07:01.588784

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd97ffff9c3bb'
down_revision: Union[str, Sequence[str], None] = '4ef23035a692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dag_tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='task_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('dag_config', sa.JSON(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('idx_dag_tasks_created_at', 'dag_tasks', ['created_at'], unique=False)
    op.create_index('idx_dag_tasks_priority', 'dag_tasks', ['tenant_id', 'priority', 'created_at'], unique=False)
    op.create_index('idx_dag_tasks_status', 'dag_tasks', ['status'], unique=False)
    op.create_index('idx_dag_tasks_tenant_created', 'dag_tasks', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_dag_tasks_tenant_status', 'dag_tasks', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_dag_tasks_tenant_id'), 'dag_tasks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_dag_tasks_worker_id'), 'dag_tasks', ['worker_id'], unique=False)
    op.create_table('execution_records',
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTING', 'COMPLETED', 'FAILED', 'UNKNOWN', name='executionstatus'), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('filled_size', sa.String(), nullable=True),
    sa.Column('avg_price', sa.String(), nullable=True),
    sa.Column('remaining_size', sa.String(), nullable=True),
    sa.Column('exchange_id', sa.String(), nullable=True),
    sa.Column('last_exchange_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exchange_status', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index('idx_execution_records_active', 'execution_records', ['tenant_id', 'status'], unique=False, postgresql_where=sa.text("status = 'PENDING' OR status = 'EXECUTING'"))
    op.create_index('idx_execution_records_created_at', 'execution_records', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_execution_records_exchange_sync', 'execution_records', ['last_exchange_sync'], unique=False)
    op.create_index('idx_execution_records_order_id', 'execution_records', ['order_id'], unique=False)
    op.create_index('idx_execution_records_status', 'execution_records', ['status'], unique=False)
    op.create_index('idx_execution_records_task_id', 'execution_records', ['task_id'], unique=False)
    op.create_index('idx_execution_records_tenant_status', 'execution_records', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_execution_records_tenant_symbol', 'execution_records', ['tenant_id', 'symbol'], unique=False)
    op.create_index(op.f('ix_execution_records_order_id'), 'execution_records', ['order_id'], unique=False)
    op.create_index(op.f('ix_execution_records_task_id'), 'execution_records', ['task_id'], unique=False)
    op.create_index(op.f('ix_execution_records_tenant_id'), 'execution_records', ['tenant_id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_tenant_id'), 'fills', ['tenant_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idempotency_key', 'tenant_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=False),
    sa.Column('amtUSD', sa.Float(), nullable=False),
    sa.Column('amtINR', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('payment_method_id', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=32), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('expiry_month', sa.Integer(), nullable=False),
    sa.Column('expiry_year', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_user_id'), 'payment_methods', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_tenant_id'), 'positions', ['tenant_id'], unique=False)
    op.create_table('reconciliation_mismatches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mismatch_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('local_value', sa.Text(), nullable=False),
    sa.Column('exchange_value', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', name='mismatch_severity_enum'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ESCALATED', 'RESOLVED', 'SUPPRESSED', name='mismatch_status_enum'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('escalation_count', sa.Integer(), nullable=False),
    sa.Column('last_escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kill_switch_triggered', sa.Boolean(), nullable=False),
    sa.Column('raw_local_state', sa.JSON(), nullable=True),
    sa.Column('raw_exchange_state', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rmm_execution_id', 'reconciliation_mismatches', ['execution_id'], unique=False)
    op.create_index('idx_rmm_kill_switch', 'reconciliation_mismatches', ['kill_switch_triggered'], unique=False)
    op.create_index('idx_rmm_status_detected', 'reconciliation_mismatches', ['status', 'detected_at'], unique=False)
    op.create_index('idx_rmm_tenant_status', 'reconciliation_mismatches', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_reconciliation_mismatches_execution_id'), 'reconciliation_mismatches', ['execution_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_mismatches_mismatch_id'), 'reconciliation_mismatches', ['mismatch_id'], unique=True)
    op.create_index(op.f('ix_reconciliation_mismatches_order_id'), 'reconciliation_mismatches', ['order_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_mismatches_tenant_id'), 'reconciliation_mismatches', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('priceUSD', sa.Float(), nullable=False),
    sa.Column('priceINR', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('nextBillingDate', sa.String(length=64), nullable=True),
    sa.Column('autoRenew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('transaction_checkpoints',
    sa.Column('checkpoint_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('state_snapshot', sa.JSON(), nullable=True),
    sa.Column('operations_snapshot', sa.JSON(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_index(op.f('ix_transaction_checkpoints_tenant_id'), 'transaction_checkpoints', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_transaction_checkpoints_transaction_id'), 'transaction_checkpoints', ['transaction_id'], unique=False)
    op.create_table('transaction_records',
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('operations_count', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transaction_records_tenant_id'), 'transaction_records', ['tenant_id'], unique=False)
    op.create_table('transaction_rollbacks',
    sa.Column('rollback_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('checkpoint_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rollback_id')
    )
    op.create_index(op.f('ix_transaction_rollbacks_tenant_id'), 'transaction_rollbacks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_transaction_rollbacks_transaction_id'), 'transaction_rollbacks', ['transaction_id'], unique=False)
    op.drop_index(op.f('idx_strategies_user_id'), table_name='strategies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.drop_index(op.f('ix_transaction_rollbacks_transaction_id'), table_name='transaction_rollbacks')
    op.drop_index(op.f('ix_transaction_rollbacks_tenant_id'), table_name='transaction_rollbacks')
    op.drop_table('transaction_rollbacks')
    op.drop_index(op.f('ix_transaction_records_tenant_id'), table_name='transaction_records')
    op.drop_table('transaction_records')
    op.drop_index(op.f('ix_transaction_checkpoints_transaction_id'), table_name='transaction_checkpoints')
    op.drop_index(op.f('ix_transaction_checkpoints_tenant_id'), table_name='transaction_checkpoints')
    op.drop_table('transaction_checkpoints')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_reconciliation_mismatches_tenant_id'), table_name='reconciliation_mismatches')
    op.drop_index(op.f('ix_reconciliation_mismatches_order_id'), table_name='reconciliation_mismatches')
    op.drop_index(op.f('ix_reconciliation_mismatches_mismatch_id'), table_name='reconciliation_mismatches')
    op.drop_index(op.f('ix_reconciliation_mismatches_execution_id'), table_name='reconciliation_mismatches')
    op.drop_index('idx_rmm_tenant_status', table_name='reconciliation_mismatches')
    op.drop_index('idx_rmm_status_detected', table_name='reconciliation_mismatches')
    op.drop_index('idx_rmm_kill_switch', table_name='reconciliation_mismatches')
    op.drop_index('idx_rmm_execution_id', table_name='reconciliation_mismatches')
    op.drop_table('reconciliation_mismatches')
    op.drop_index(op.f('ix_positions_tenant_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_payment_methods_user_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_fills_tenant_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_execution_records_tenant_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_task_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_order_id'), table_name='execution_records')
    op.drop_index('idx_execution_records_tenant_symbol', table_name='execution_records')
    op.drop_index('idx_execution_records_tenant_status', table_name='execution_records')
    op.drop_index('idx_execution_records_task_id', table_name='execution_records')
    op.drop_index('idx_execution_records_status', table_name='execution_records')
    op.drop_index('idx_execution_records_order_id', table_name='execution_records')
    op.drop_index('idx_execution_records_exchange_sync', table_name='execution_records')
    op.drop_index('idx_execution_records_created_at', table_name='execution_records')
    op.drop_index('idx_execution_records_active', table_name='execution_records', postgresql_where=sa.text("status = 'PENDING' OR status = 'EXECUTING'"))
    op.drop_table('execution_records')
    op.drop_index(op.f('ix_dag_tasks_worker_id'), table_name='dag_tasks')
    op.drop_index(op.f('ix_dag_tasks_tenant_id'), table_name='dag_tasks')
    op.drop_index('idx_dag_tasks_tenant_status', table_name='dag_tasks')
    op.drop_index('idx_dag_tasks_tenant_created', table_name='dag_tasks')
    op.drop_index('idx_dag_tasks_status', table_name='dag_tasks')
    op.drop_index('idx_dag_tasks_priority', table_name='dag_tasks')
    op.drop_index('idx_dag_tasks_created_at', table_name='dag_tasks')
    op.drop_table('dag_tasks')
    # ### end Alembic commands ###
