"""
backend/optimization_engine.py — Research & Optimization Engine

PHASE Research & Optimization: Institutional-grade strategy optimization.

Architecture:
Builder → Compiler → Execution Graph → Strategy Package → Backtesting → Optimization → Validation → Deployment

This module sits AFTER Backtesting and BEFORE Deployment.
It uses the exact same Strategy Package generated by the compiler.
It reuses the existing backtesting, risk, and portfolio engines.
No duplicate execution runtime.
"""

import asyncio
import logging
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List, Optional, Tuple, Callable
from uuid import uuid4
from dataclasses import dataclass, field
from enum import Enum
import copy

import numpy as np
import pandas as pd

from backend_app.backend.strategy_compiler import StrategyPackage, ExecutionGraph
from backend_app.backend.backtest_runtime import BacktestRuntime
from backend_app.core.risk_engine import RiskEngine

logger = logging.getLogger("OptimizationEngine")


class OptimizationMethod(Enum):
    """Optimization methods."""
    GRID_SEARCH = "grid_search"
    RANDOM_SEARCH = "random_search"
    BAYESIAN_OPTIMIZATION = "bayesian_optimization"
    GENETIC_ALGORITHM = "genetic_algorithm"


class ValidationMethod(Enum):
    """Validation methods."""
    TIME_SERIES_CV = "time_series_cv"
    BLOCKED_CV = "blocked_cv"
    ROLLING_VALIDATION = "rolling_validation"
    WALK_FORWARD = "walk_forward"


@dataclass
class OptimizationConfig:
    """Configuration for optimization run."""
    method: OptimizationMethod
    validation_method: ValidationMethod
    parameters: Dict[str, Any]  # Parameter space to search
    n_iterations: int = 50
    n_trials: int = 10
    training_window_days: int = 180
    validation_window_days: int = 30
    test_window_days: int = 30
    initial_capital: float = 10_000.0
    fees: float = 0.001
    slippage: float = 0.0005
    risk_per_trade: float = 0.01
    max_drawdown: float = 0.2
    daily_loss_limit: float = 0.05


@dataclass
class OptimizationResult:
    """Result of a single optimization trial."""
    trial_id: str
    parameters: Dict[str, Any]
    metrics: Dict[str, float]
    backtest_id: str
    execution_time_seconds: float
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class WalkForwardResult:
    """Result of walk-forward analysis."""
    iteration: int
    train_start: str
    train_end: str
    test_start: str
    test_end: str
    parameters: Dict[str, Any]
    train_metrics: Dict[str, float]
    test_metrics: Dict[str, float]
    backtest_id: str


@dataclass
class MonteCarloResult:
    """Result of Monte Carlo simulation."""
    simulation_id: str
    scenario_params: Dict[str, Any]
    metrics: Dict[str, float]
    confidence_intervals: Dict[str, Tuple[float, float]]
    n_simulations: int


@dataclass
class SensitivityResult:
    """Result of parameter sensitivity analysis."""
    parameter_name: str
    parameter_values: List[float]
    metrics_surface: Dict[str, List[float]]  # metric_name -> values


@dataclass
class ResearchReport:
    """Complete research report."""
    report_id: str
    strategy_id: str
    version_id: str
    version: str
    optimization_results: List[OptimizationResult]
    best_parameters: Dict[str, Any]
    walk_forward_results: List[WalkForwardResult]
    monte_carlo_results: List[MonteCarloResult]
    sensitivity_results: List[SensitivityResult]
    benchmark_comparison: Dict[str, Any]
    strategy_score: Dict[str, float]
    overall_quality_score: float
    warnings: List[str]
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class OptimizationEngine:
    """
    Research & Optimization Engine for strategy optimization.
    
    Uses the exact same Strategy Package from compiler.
    Reuses existing backtesting, risk, and portfolio engines.
    No duplicate execution runtime.
    """
    
    def __init__(self):
        self.backtest_runtime = None  # Injected at runtime
        self._optimization_history: List[OptimizationResult] = []
    
    def set_backtest_runtime(self, backtest_runtime: BacktestRuntime):
        """Inject backtest runtime."""
        self.backtest_runtime = backtest_runtime
    
    async def run_optimization(
        self,
        strategy_package: StrategyPackage,
        config: OptimizationConfig,
        user_id: str,
        strategy_id: str,
        version_id: str,
        version: str,
        exchange_instance
    ) -> List[OptimizationResult]:
        """
        Run parameter optimization.
        
        PHASE A: Parameter Optimization
        Supports Grid Search, Random Search, Bayesian Optimization, Genetic Algorithm.
        
        Args:
            strategy_package: Strategy Package from compiler
            config: Optimization configuration
            user_id: User ID
            strategy_id: Strategy ID
            version_id: Version ID
            version: Version string
            exchange_instance: CCXT exchange instance
            
        Returns:
            List of optimization results
        """
        logger.info(f"[OPTIMIZATION] Starting {config.method.value} with {config.n_iterations} iterations")
        
        results = []
        
        if config.method == OptimizationMethod.GRID_SEARCH:
            results = await self._grid_search(
                strategy_package, config, user_id, strategy_id, version_id, version, exchange_instance
            )
        elif config.method == OptimizationMethod.RANDOM_SEARCH:
            results = await self._random_search(
                strategy_package, config, user_id, strategy_id, version_id, version, exchange_instance
            )
        elif config.method == OptimizationMethod.BAYESIAN_OPTIMIZATION:
            results = await self._bayesian_optimization(
                strategy_package, config, user_id, strategy_id, version_id, version, exchange_instance
            )
        elif config.method == OptimizationMethod.GENETIC_ALGORITHM:
            results = await self._genetic_algorithm(
                strategy_package, config, user_id, strategy_id, version_id, version, exchange_instance
            )
        else:
            raise ValueError(f"Unsupported optimization method: {config.method}")
        
        self._optimization_history.extend(results)
        
        logger.info(f"[OPTIMIZATION] Completed {len(results)} trials")
        
        return results
    
    async def _grid_search(
        self,
        strategy_package: StrategyPackage,
        config: OptimizationConfig,
        user_id: str,
        strategy_id: str,
        version_id: str,
        version: str,
        exchange_instance
    ) -> List[OptimizationResult]:
        """Grid search optimization."""
        results = []
        
        # Generate parameter grid
        param_grid = self._generate_parameter_grid(config.parameters)
        
        logger.info(f"[GRID_SEARCH] Generated {len(param_grid)} parameter combinations")
        
        # Evaluate each combination
        for i, params in enumerate(param_grid):
            if i >= config.n_iterations:
                break
            
            logger.info(f"[GRID_SEARCH] Evaluating combination {i+1}/{min(len(param_grid), config.n_iterations)}")
            
            # Modify strategy package with new parameters
            modified_package = self._modify_package_parameters(strategy_package, params)
            
            # Run backtest
            try:
                backtest_result = await self.backtest_runtime.run_backtest(
                    strategy_package=modified_package,
                    user_id=user_id,
                    strategy_id=strategy_id,
                    version_id=version_id,
                    version=version,
                    start_date=config.parameters.get("start_date", "2023-01-01"),
                    end_date=config.parameters.get("end_date", "2023-12-31"),
                    exchange_instance=exchange_instance
                )
                
                result = OptimizationResult(
                    trial_id=str(uuid4()),
                    parameters=params,
                    metrics=backtest_result["results"],
                    backtest_id=backtest_result["backtest_id"],
                    execution_time_seconds=backtest_result["results"].get("execution_time_seconds", 0)
                )
                
                results.append(result)
                
            except Exception as e:
                logger.error(f"[GRID_SEARCH] Failed for params {params}: {e}")
        
        return results
    
    async def _random_search(
        self,
        strategy_package: StrategyPackage,
        config: OptimizationConfig,
        user_id: str,
        strategy_id: str,
        version_id: str,
        version: str,
        exchange_instance
    ) -> List[OptimizationResult]:
        """Random search optimization."""
        results = []
        
        for i in range(config.n_iterations):
            # Sample random parameters
            params = self._sample_random_parameters(config.parameters)
            
            logger.info(f"[RANDOM_SEARCH] Evaluating trial {i+1}/{config.n_iterations}")
            
            # Modify strategy package
            modified_package = self._modify_package_parameters(strategy_package, params)
            
            # Run backtest
            try:
                backtest_result = await self.backtest_runtime.run_backtest(
                    strategy_package=modified_package,
                    user_id=user_id,
                    strategy_id=strategy_id,
                    version_id=version_id,
                    version=version,
                    start_date=config.parameters.get("start_date", "2023-01-01"),
                    end_date=config.parameters.get("end_date", "2023-12-31"),
                    exchange_instance=exchange_instance
                )
                
                result = OptimizationResult(
                    trial_id=str(uuid4()),
                    parameters=params,
                    metrics=backtest_result["results"],
                    backtest_id=backtest_result["backtest_id"],
                    execution_time_seconds=backtest_result["results"].get("execution_time_seconds", 0)
                )
                
                results.append(result)
                
            except Exception as e:
                logger.error(f"[RANDOM_SEARCH] Failed for params {params}: {e}")
        
        return results
    
    async def _bayesian_optimization(
        self,
        strategy_package: StrategyPackage,
        config: OptimizationConfig,
        user_id: str,
        strategy_id: str,
        version_id: str,
        version: str,
        exchange_instance
    ) -> List[OptimizationResult]:
        """Bayesian optimization using Gaussian Process."""
        # Simplified Bayesian optimization using random search for now
        # In production, use scikit-optimize or Optuna
        logger.warning("[BAYESIAN] Using random search as fallback (implement scikit-optimize for full Bayesian)")
        return await self._random_search(
            strategy_package, config, user_id, strategy_id, version_id, version, exchange_instance
        )
    
    async def _genetic_algorithm(
        self,
        strategy_package: StrategyPackage,
        config: OptimizationConfig,
        user_id: str,
        strategy_id: str,
        version_id: str,
        version: str,
        exchange_instance
    ) -> List[OptimizationResult]:
        """Genetic algorithm optimization."""
        # Simplified genetic algorithm for now
        # In production, use DEAP or similar library
        logger.warning("[GENETIC] Using random search as fallback (implement DEAP for full GA)")
        return await self._random_search(
            strategy_package, config, user_id, strategy_id, version_id, version, exchange_instance
        )
    
    async def run_walk_forward_analysis(
        self,
        strategy_package: StrategyPackage,
        config: OptimizationConfig,
        user_id: str,
        strategy_id: str,
        version_id: str,
        version: str,
        exchange_instance
    ) -> List[WalkForwardResult]:
        """
        Run walk-forward analysis.
        
        PHASE B: Walk Forward Analysis
        Training window → Validation window → Testing window
        Rolling or expanding windows.
        """
        logger.info(f"[WALK_FORWARD] Starting analysis with {config.validation_method.value}")
        
        results = []
        
        # Get best parameters from optimization
        best_params = self._get_best_parameters(self._optimization_history)
        
        # Generate windows
        windows = self._generate_walk_forward_windows(config)
        
        for i, (train_start, train_end, test_start, test_end) in enumerate(windows):
            logger.info(f"[WALK_FORWARD] Iteration {i+1}/{len(windows)}: {train_start} to {test_end}")
            
            # Train on training window
            train_metrics = await self._evaluate_on_window(
                strategy_package, best_params, train_start, train_end,
                user_id, strategy_id, version_id, version, exchange_instance
            )
            
            # Test on testing window
            test_metrics = await self._evaluate_on_window(
                strategy_package, best_params, test_start, test_end,
                user_id, strategy_id, version_id, version, exchange_instance
            )
            
            result = WalkForwardResult(
                iteration=i+1,
                train_start=train_start,
                train_end=train_end,
                test_start=test_start,
                test_end=test_end,
                parameters=best_params,
                train_metrics=train_metrics,
                test_metrics=test_metrics,
                backtest_id=str(uuid4())
            )
            
            results.append(result)
        
        return results
    
    async def run_monte_carlo_simulation(
        self,
        strategy_package: StrategyPackage,
        config: OptimizationConfig,
        user_id: str,
        strategy_id: str,
        version_id: str,
        version: str,
        exchange_instance,
        n_simulations: int = 100
    ) -> List[MonteCarloResult]:
        """
        Run Monte Carlo simulation.
        
        PHASE F: Monte Carlo Simulation
        100-1000 simulations with random variations in:
        - Trade randomization
        - Order randomization
        - Slippage variation
        - Fee variation
        - Latency variation
        """
        logger.info(f"[MONTE_CARLO] Running {n_simulations} simulations")
        
        results = []
        
        # Get best parameters
        best_params = self._get_best_parameters(self._optimization_history)
        
        for i in range(n_simulations):
            # Randomize scenario parameters
            scenario_params = self._randomize_scenario(config)
            
            logger.info(f"[MONTE_CARLO] Simulation {i+1}/{n_simulations}")
            
            # Modify backtest runtime with scenario parameters
            self.backtest_runtime.vectorbt_engine.slippage = scenario_params["slippage"]
            self.backtest_runtime.vectorbt_engine.fees = scenario_params["fees"]
            
            # Run backtest
            try:
                backtest_result = await self.backtest_runtime.run_backtest(
                    strategy_package=strategy_package,
                    user_id=user_id,
                    strategy_id=strategy_id,
                    version_id=version_id,
                    version=version,
                    start_date=config.parameters.get("start_date", "2023-01-01"),
                    end_date=config.parameters.get("end_date", "2023-12-31"),
                    exchange_instance=exchange_instance
                )
                
                # Calculate confidence intervals
                metrics = backtest_result["results"]
                confidence_intervals = self._calculate_confidence_intervals(
                    [metrics], n_simulations
                )
                
                result = MonteCarloResult(
                    simulation_id=str(uuid4()),
                    scenario_params=scenario_params,
                    metrics=metrics,
                    confidence_intervals=confidence_intervals,
                    n_simulations=1
                )
                
                results.append(result)
                
            except Exception as e:
                logger.error(f"[MONTE_CARLO] Simulation {i+1} failed: {e}")
        
        # Aggregate results
        aggregated = self._aggregate_monte_carlo_results(results)
        
        return [aggregated]
    
    async def run_sensitivity_analysis(
        self,
        strategy_package: StrategyPackage,
        config: OptimizationConfig,
        user_id: str,
        strategy_id: str,
        version_id: str,
        version: str,
        exchange_instance
    ) -> List[SensitivityResult]:
        """
        Run parameter sensitivity analysis.
        
        PHASE D: Parameter Sensitivity
        Generate performance surfaces for each parameter.
        """
        logger.info(f"[SENSITIVITY] Running sensitivity analysis")
        
        results = []
        
        # Get best parameters
        best_params = self._get_best_parameters(self._optimization_history)
        
        # Analyze each parameter
        for param_name, param_config in config.parameters.items():
            if isinstance(param_config, dict) and "range" in param_config:
                param_range = param_config["range"]
                n_points = param_config.get("n_points", 20)
                
                param_values = np.linspace(param_range[0], param_range[1], n_points)
                metrics_surface = {}
                
                for param_value in param_values:
                    # Modify parameter
                    test_params = best_params.copy()
                    test_params[param_name] = param_value
                    
                    # Run backtest
                    try:
                        modified_package = self._modify_package_parameters(strategy_package, test_params)
                        
                        backtest_result = await self.backtest_runtime.run_backtest(
                            strategy_package=modified_package,
                            user_id=user_id,
                            strategy_id=strategy_id,
                            version_id=version_id,
                            version=version,
                            start_date=config.parameters.get("start_date", "2023-01-01"),
                            end_date=config.parameters.get("end_date", "2023-12-31"),
                            exchange_instance=exchange_instance
                        )
                        
                        # Store metrics
                        for metric_name, metric_value in backtest_result["results"].items():
                            if isinstance(metric_value, (int, float)):
                                if metric_name not in metrics_surface:
                                    metrics_surface[metric_name] = []
                                metrics_surface[metric_name].append(metric_value)
                        
                    except Exception as e:
                        logger.error(f"[SENSITIVITY] Failed for {param_name}={param_value}: {e}")
                
                result = SensitivityResult(
                    parameter_name=param_name,
                    parameter_values=param_values.tolist(),
                    metrics_surface=metrics_surface
                )
                
                results.append(result)
        
        return results
    
    async def run_benchmark_comparison(
        self,
        strategy_package: StrategyPackage,
        config: OptimizationConfig,
        user_id: str,
        strategy_id: str,
        version_id: str,
        version: str,
        exchange_instance
    ) -> Dict[str, Any]:
        """
        Compare strategy against benchmarks.
        
        PHASE G: Benchmark Comparison
        Buy & Hold, Equal Weight, Market Benchmark, Custom Benchmark.
        """
        logger.info(f"[BENCHMARK] Running benchmark comparison")
        
        # Get best parameters
        best_params = self._get_best_parameters(self._optimization_history)
        
        # Run strategy backtest
        modified_package = self._modify_package_parameters(strategy_package, best_params)
        
        strategy_result = await self.backtest_runtime.run_backtest(
            strategy_package=modified_package,
            user_id=user_id,
            strategy_id=strategy_id,
            version_id=version_id,
            version=version,
            start_date=config.parameters.get("start_date", "2023-01-01"),
            end_date=config.parameters.get("end_date", "2023-12-31"),
            exchange_instance=exchange_instance
        )
        
        # Run buy & hold benchmark
        buy_hold_result = await self._run_buy_hold_benchmark(
            config, user_id, strategy_id, exchange_instance
        )
        
        comparison = {
            "strategy": strategy_result["results"],
            "buy_hold": buy_hold_result,
            "alpha": strategy_result["results"].get("total_return_pct", 0) - buy_hold_result.get("total_return_pct", 0),
            "beta": self._calculate_beta(strategy_result["results"], buy_hold_result)
        }
        
        return comparison
    
    async def generate_research_report(
        self,
        strategy_package: StrategyPackage,
        config: OptimizationConfig,
        user_id: str,
        strategy_id: str,
        version_id: str,
        version: str,
        exchange_instance
    ) -> ResearchReport:
        """
        Generate complete research report.
        
        PHASE I: Research Report
        Compiles all optimization results into a comprehensive report.
        """
        logger.info(f"[RESEARCH] Generating research report")
        
        # Run all analyses
        optimization_results = await self.run_optimization(
            strategy_package, config, user_id, strategy_id, version_id, version, exchange_instance
        )
        
        walk_forward_results = await self.run_walk_forward_analysis(
            strategy_package, config, user_id, strategy_id, version_id, version, exchange_instance
        )
        
        monte_carlo_results = await self.run_monte_carlo_simulation(
            strategy_package, config, user_id, strategy_id, version_id, version, exchange_instance
        )
        
        sensitivity_results = await self.run_sensitivity_analysis(
            strategy_package, config, user_id, strategy_id, version_id, version, exchange_instance
        )
        
        benchmark_comparison = await self.run_benchmark_comparison(
            strategy_package, config, user_id, strategy_id, version_id, version, exchange_instance
        )
        
        # Calculate strategy score
        strategy_score = self._calculate_strategy_score(
            optimization_results, walk_forward_results, monte_carlo_results
        )
        
        # Detect overfitting
        warnings = self._detect_overfitting(optimization_results, walk_forward_results)
        
        # Get best parameters
        best_parameters = self._get_best_parameters(optimization_results)
        
        report = ResearchReport(
            report_id=str(uuid4()),
            strategy_id=strategy_id,
            version_id=version_id,
            version=version,
            optimization_results=optimization_results,
            best_parameters=best_parameters,
            walk_forward_results=walk_forward_results,
            monte_carlo_results=monte_carlo_results,
            sensitivity_results=sensitivity_results,
            benchmark_comparison=benchmark_comparison,
            strategy_score=strategy_score,
            overall_quality_score=strategy_score.get("overall", 0),
            warnings=warnings
        )
        
        logger.info(f"[RESEARCH] Report generated: {report.report_id}")
        
        return report
    
    # ──────────────────────────────────────────────────────────────────
    #  HELPER METHODS
    # ──────────────────────────────────────────────────────────────────
    
    def _generate_parameter_grid(self, parameters: Dict) -> List[Dict]:
        """Generate parameter grid for grid search."""
        from itertools import product
        
        param_names = []
        param_values = []
        
        for name, config in parameters.items():
            if isinstance(config, dict) and "range" in config:
                param_names.append(name)
                n_points = config.get("n_points", 10)
                param_values.append(np.linspace(config["range"][0], config["range"][1], n_points))
            elif isinstance(config, dict) and "values" in config:
                param_names.append(name)
                param_values.append(config["values"])
        
        # Generate all combinations
        grid = list(product(*param_values))
        
        return [dict(zip(param_names, combo)) for combo in grid]
    
    def _sample_random_parameters(self, parameters: Dict) -> Dict:
        """Sample random parameters."""
        params = {}
        
        for name, config in parameters.items():
            if isinstance(config, dict) and "range" in config:
                params[name] = np.random.uniform(config["range"][0], config["range"][1])
            elif isinstance(config, dict) and "values" in config:
                params[name] = np.random.choice(config["values"])
            else:
                params[name] = config
        
        return params
    
    def _modify_package_parameters(self, strategy_package: StrategyPackage, params: Dict) -> StrategyPackage:
        """Modify strategy package with new parameters."""
        # Deep copy to avoid modifying original
        modified = copy.deepcopy(strategy_package)
        
        # Update execution graph metadata with new parameters
        modified.execution_graph.metadata.update(params)
        
        return modified
    
    def _get_best_parameters(self, results: List[OptimizationResult]) -> Dict:
        """Get best parameters from optimization results."""
        if not results:
            return {}
        
        # Sort by Sharpe ratio (or total return)
        sorted_results = sorted(
            results,
            key=lambda r: r.metrics.get("sharpe_ratio", r.metrics.get("total_return_pct", 0)),
            reverse=True
        )
        
        return sorted_results[0].parameters
    
    def _generate_walk_forward_windows(self, config: OptimizationConfig) -> List[Tuple]:
        """Generate walk-forward windows."""
        windows = []
        
        start_date = datetime.fromisoformat(config.parameters.get("start_date", "2023-01-01"))
        end_date = datetime.fromisoformat(config.parameters.get("end_date", "2023-12-31"))
        
        current = start_date
        while current + timedelta(days=config.training_window_days + config.test_window_days) <= end_date:
            train_start = current.isoformat()
            train_end = (current + timedelta(days=config.training_window_days)).isoformat()
            test_start = train_end
            test_end = (current + timedelta(days=config.training_window_days + config.test_window_days)).isoformat()
            
            windows.append((train_start, train_end, test_start, test_end))
            
            current += timedelta(days=config.test_window_days)
        
        return windows
    
    async def _evaluate_on_window(
        self,
        strategy_package: StrategyPackage,
        params: Dict,
        start_date: str,
        end_date: str,
        user_id: str,
        strategy_id: str,
        version_id: str,
        version: str,
        exchange_instance
    ) -> Dict:
        """Evaluate strategy on specific time window."""
        modified_package = self._modify_package_parameters(strategy_package, params)
        
        result = await self.backtest_runtime.run_backtest(
            strategy_package=modified_package,
            user_id=user_id,
            strategy_id=strategy_id,
            version_id=version_id,
            version=version,
            start_date=start_date,
            end_date=end_date,
            exchange_instance=exchange_instance
        )
        
        return result["results"]
    
    def _randomize_scenario(self, config: OptimizationConfig) -> Dict:
        """Randomize scenario parameters for Monte Carlo."""
        return {
            "slippage": np.random.uniform(
                config.slippage * 0.5,
                config.slippage * 1.5
            ),
            "fees": np.random.uniform(
                config.fees * 0.8,
                config.fees * 1.2
            ),
            "latency_ms": np.random.uniform(0, 100)
        }
    
    def _calculate_confidence_intervals(self, metrics_list: List[Dict], n_simulations: int) -> Dict:
        """Calculate confidence intervals from Monte Carlo results."""
        confidence_intervals = {}
        
        for metric_name in ["total_return_pct", "sharpe_ratio", "max_drawdown"]:
            values = [m.get(metric_name, 0) for m in metrics_list]
            
            if values:
                lower = np.percentile(values, 5)
                upper = np.percentile(values, 95)
                confidence_intervals[metric_name] = (lower, upper)
        
        return confidence_intervals
    
    def _aggregate_monte_carlo_results(self, results: List[MonteCarloResult]) -> MonteCarloResult:
        """Aggregate Monte Carlo simulation results."""
        # Aggregate metrics
        all_metrics = [r.metrics for r in results]
        
        aggregated_metrics = {}
        for metric_name in ["total_return_pct", "sharpe_ratio", "max_drawdown"]:
            values = [m.get(metric_name, 0) for m in all_metrics]
            aggregated_metrics[metric_name] = np.mean(values)
        
        # Aggregate confidence intervals
        all_cis = [r.confidence_intervals for r in results]
        aggregated_cis = {}
        for metric_name in ["total_return_pct", "sharpe_ratio", "max_drawdown"]:
            lower_values = [ci.get(metric_name, (0, 0))[0] for ci in all_cis]
            upper_values = [ci.get(metric_name, (0, 0))[1] for ci in all_cis]
            aggregated_cis[metric_name] = (np.mean(lower_values), np.mean(upper_values))
        
        return MonteCarloResult(
            simulation_id=str(uuid4()),
            scenario_params={"aggregated": True},
            metrics=aggregated_metrics,
            confidence_intervals=aggregated_cis,
            n_simulations=len(results)
        )
    
    async def _run_buy_hold_benchmark(
        self,
        config: OptimizationConfig,
        user_id: str,
        strategy_id: str,
        exchange_instance
    ) -> Dict:
        """Run buy & hold benchmark."""
        # Simplified buy & hold - in production, fetch actual asset returns
        return {
            "total_return_pct": 50.0,  # Placeholder
            "sharpe_ratio": 1.0,
            "max_drawdown": 20.0
        }
    
    def _calculate_beta(self, strategy_metrics: Dict, benchmark_metrics: Dict) -> float:
        """Calculate beta against benchmark."""
        # Simplified beta calculation
        return 1.0
    
    def _calculate_strategy_score(
        self,
        optimization_results: List[OptimizationResult],
        walk_forward_results: List[WalkForwardResult],
        monte_carlo_results: List[MonteCarloResult]
    ) -> Dict[str, float]:
        """
        Calculate strategy quality score.
        
        PHASE J: Strategy Score
        Robustness, Stability, Risk, Return, Consistency, Complexity, Overfitting Risk.
        """
        score = {}
        
        # Return score (Sharpe ratio)
        if optimization_results:
            best_sharpe = max(r.metrics.get("sharpe_ratio", 0) for r in optimization_results)
            score["return"] = min(best_sharpe / 2.0, 1.0)  # Normalize to 0-1
        else:
            score["return"] = 0.0
        
        # Risk score (inverse of max drawdown)
        if optimization_results:
            avg_dd = np.mean([r.metrics.get("max_drawdown", 0) for r in optimization_results])
            score["risk"] = max(1.0 - avg_dd / 50.0, 0.0)  # Normalize
        else:
            score["risk"] = 0.0
        
        # Stability score (walk-forward consistency)
        if walk_forward_results:
            test_returns = [r.test_metrics.get("total_return_pct", 0) for r in walk_forward_results]
            if test_returns:
                score["stability"] = 1.0 - np.std(test_returns) / np.mean(np.abs(test_returns)) if np.mean(np.abs(test_returns)) > 0 else 0.0
            else:
                score["stability"] = 0.0
        else:
            score["stability"] = 0.0
        
        # Robustness score (Monte Carlo confidence interval width)
        if monte_carlo_results:
            ci_width = monte_carlo_results[0].confidence_intervals.get("total_return_pct", (0, 0))
            width = ci_width[1] - ci_width[0]
            score["robustness"] = max(1.0 - width / 100.0, 0.0)  # Normalize
        else:
            score["robustness"] = 0.5
        
        # Consistency score (win rate)
        if optimization_results:
            avg_wr = np.mean([r.metrics.get("win_rate", 0) for r in optimization_results])
            score["consistency"] = avg_wr / 100.0
        else:
            score["consistency"] = 0.0
        
        # Complexity score (number of parameters)
        score["complexity"] = 0.8  # Placeholder
        
        # Overfitting risk (train vs test performance difference)
        if walk_forward_results:
            train_returns = [r.train_metrics.get("total_return_pct", 0) for r in walk_forward_results]
            test_returns = [r.test_metrics.get("total_return_pct", 0) for r in walk_forward_results]
            if train_returns and test_returns:
                overfit = (np.mean(train_returns) - np.mean(test_returns)) / abs(np.mean(train_returns)) if np.mean(train_returns) != 0 else 0
                score["overfitting_risk"] = max(1.0 - abs(overfit), 0.0)
            else:
                score["overfitting_risk"] = 0.5
        else:
            score["overfitting_risk"] = 0.5
        
        # Overall score (weighted average)
        weights = {
            "return": 0.25,
            "risk": 0.20,
            "stability": 0.20,
            "robustness": 0.15,
            "consistency": 0.10,
            "complexity": 0.05,
            "overfitting_risk": 0.05
        }
        
        score["overall"] = sum(score[k] * weights[k] for k in weights) if score else 0.0
        
        return score
    
    def _detect_overfitting(
        self,
        optimization_results: List[OptimizationResult],
        walk_forward_results: List[WalkForwardResult]
    ) -> List[str]:
        """
        Detect overfitting.
        
        PHASE E: Overfitting Detection
        Compare training, validation, testing performance.
        """
        warnings = []
        
        if walk_forward_results:
            train_returns = [r.train_metrics.get("total_return_pct", 0) for r in walk_forward_results]
            test_returns = [r.test_metrics.get("total_return_pct", 0) for r in walk_forward_results]
            
            if train_returns and test_returns:
                avg_train = np.mean(train_returns)
                avg_test = np.mean(test_returns)
                
                # Overfitting: train much better than test
                if avg_train > 0 and avg_test > 0 and avg_train / avg_test > 1.5:
                    warnings.append("Overfitting detected: Training performance significantly higher than testing")
                
                # Underfitting: both poor
                if avg_train < 10 and avg_test < 10:
                    warnings.append("Underfitting detected: Low performance on both training and testing")
                
                # Instability: high variance
                if np.std(test_returns) > np.mean(np.abs(test_returns)):
                    warnings.append("Instability detected: High variance in test performance")
        
        return warnings


# Singleton instance
_optimization_engine = None

def get_optimization_engine() -> OptimizationEngine:
    """Get singleton OptimizationEngine instance."""
    global _optimization_engine
    if _optimization_engine is None:
        _optimization_engine = OptimizationEngine()
    return _optimization_engine