/**
 * Unit tests for the client-side edge legality rules (src/lib/connectionLegality.js).
 *
 * The module exists to spare a network round trip while an author drags a connection, and the
 * backend validator stays authoritative. So the tests are organised around the two ways that
 * arrangement can fail:
 *
 * 1. **Divergence.** `tests/fixtures/backend_edge_verdicts.json` is generated by
 *    `scripts/generate_connection_legality_fixture.py`, which runs the real
 *    `validator.is_edge_legal` over the real assembled registry. Every case in it is replayed
 *    through the JS module and the whole issue — code, severity, node, edge, field, expected,
 *    actual — is compared. Verdicts are exported, never hand-copied, so the fixture can only
 *    move by re-running the generator against the backend.
 * 2. **A local rule set.** Several tests alter the *supplied* registry payload (the matrix,
 *    a descriptor's terminality, a descriptor's successor categories) and assert the verdict
 *    follows the alteration. If any rule were answered from a table inside the module, those
 *    tests fail.
 *
 * The fixture's registry section is the descriptors and the compatibility matrix exactly as
 * the backend serves them, so these tests read the same data the backend read.
 */

import { describe, it, expect } from 'vitest';
import {
  isEdgeLegal,
  checkConnection,
  reconcileWithBackend,
  legalTargetsForDrag,
  findCycle,
  createsCycle,
  cyclePathWithEdge,
  buildRegistryIndex,
  buildInboundIndex,
  buildNodeIndex,
  connectionToEdge,
  reactFlowConnectionValidator,
  portKey,
  makeIssue,
  ConnectionLegalityError,
  RULE_ORDER,
  SEVERITY_ERROR,
  AUTHORITY_BACKEND,
  AUTHORITY_CLIENT_PROVISIONAL,
  DRAG_CANDIDATE_EDGE_ID,
  CODE_EDGE_ENDPOINT_UNKNOWN,
  CODE_SELF_LOOP,
  CODE_UNKNOWN_SOURCE_PORT,
  CODE_UNKNOWN_TARGET_PORT,
  CODE_TYPE_MISMATCH,
  CODE_ILLEGAL_CATEGORY_FLOW,
  CODE_TERMINAL_HAS_NO_OUTPUT,
  CODE_PORT_ALREADY_CONNECTED,
  CODE_CYCLE,
} from '../../src/lib/connectionLegality';
import backendFixture from '../fixtures/backend_edge_verdicts.json';

/** The registry exactly as the backend serves it: descriptors plus the compatibility matrix. */
const REGISTRY = backendFixture.registry;
const DESCRIPTORS = new Map(REGISTRY.blocks.map((block) => [block.block_id, block]));

const descriptorFor = (blockId) => {
  const descriptor = DESCRIPTORS.get(blockId);
  if (descriptor === undefined) {
    throw new Error(`fixture registry publishes no '${blockId}'; regenerate the fixture`);
  }
  return descriptor;
};

/**
 * A canonical node declaring **no** ports.
 *
 * Deliberate, and the same choice the fixture generator makes: ports are read from the
 * registry descriptor, never from the node, so a node that declares none proves it. A module
 * reading `node.inputs` would fail every one of these tests.
 */
const node = (id, blockId, extra = {}) => ({
  id,
  block_id: blockId,
  category: descriptorFor(blockId).category,
  params: {},
  inputs: [],
  outputs: [],
  ui: { position: { x: 0, y: 0 } },
  ...extra,
});

const edge = (id, source, sourcePort, target, targetPort) => ({
  id,
  source,
  source_port: sourcePort,
  target,
  target_port: targetPort,
});

const graph = (nodes, edges = []) => ({
  schema_version: 2,
  strategy_id: 'test',
  version: '1',
  name: 'test',
  nodes,
  edges,
  metadata: {},
  validation_state: 'UNVALIDATED',
});

/** A registry payload with one descriptor replaced. Used to prove rules read the payload. */
const registryWith = (blockId, changes) => ({
  ...REGISTRY,
  blocks: REGISTRY.blocks.map((block) =>
    block.block_id === blockId ? { ...block, ...changes } : block,
  ),
});

/** A registry payload with a deliberately altered compatibility matrix. */
const registryWithMatrix = (changes) => ({
  ...REGISTRY,
  compatibility_matrix: { ...REGISTRY.compatibility_matrix, ...changes },
});

/** The fields a client issue and a server issue must agree on, field for field. */
const comparable = (issue) =>
  issue === null
    ? null
    : {
        code: issue.code,
        severity: issue.severity,
        node_id: issue.node_id,
        edge_id: issue.edge_id,
        field: issue.field,
        expected: issue.expected,
        actual: issue.actual,
      };

// ---------------------------------------------------------------------------
// The cross-check: the client must return the backend's verdict, case for case
// ---------------------------------------------------------------------------

describe('cross-check against the backend validator', () => {
  it('replays a fixture generated from the real validator over the real registry', () => {
    expect(backendFixture.generated_by).toBe(
      'scripts/generate_connection_legality_fixture.py',
    );
    expect(REGISTRY.registry_version).toMatch(/^r_/);
    expect(backendFixture.cases.length).toBeGreaterThanOrEqual(30);
    // Both a rejecting and an accepting case exist for every rule.
    for (const rule of ['R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8']) {
      const forRule = backendFixture.cases.filter((entry) => entry.rule === rule);
      expect(forRule.some((entry) => entry.verdict !== null)).toBe(true);
      expect(forRule.some((entry) => entry.verdict === null)).toBe(true);
    }
  });

  for (const testCase of backendFixture.cases) {
    it(`agrees with the backend: ${testCase.name}`, () => {
      const local = isEdgeLegal(testCase.graph, testCase.edge, REGISTRY);
      expect(comparable(local)).toEqual(comparable(testCase.verdict));
    });
  }

  it('reports the same rejection reason as the backend for every rejected case', () => {
    const backendCodes = backendFixture.cases.map((entry) =>
      entry.verdict === null ? 'LEGAL' : entry.verdict.code,
    );
    const clientCodes = backendFixture.cases.map((entry) => {
      const issue = isEdgeLegal(entry.graph, entry.edge, REGISTRY);
      return issue === null ? 'LEGAL' : issue.code;
    });
    expect(clientCodes).toEqual(backendCodes);
  });
});

// ---------------------------------------------------------------------------
// R1–R8, one rejecting and one accepting case each
// ---------------------------------------------------------------------------

describe('R1 endpoints resolve', () => {
  it('rejects an edge naming a block that is not in the graph', () => {
    const g = graph([node('n_data', 'ohlcv_feed'), node('n_ema', 'ema')]);
    const issue = isEdgeLegal(g, edge('e', 'n_ghost', 'close', 'n_ema', 'series'), REGISTRY);
    expect(issue.code).toBe(CODE_EDGE_ENDPOINT_UNKNOWN);
    expect(issue.actual).toEqual({ source: 'n_ghost', target: 'n_ema' });
  });

  it('accepts an edge whose endpoints both resolve', () => {
    const g = graph([node('n_data', 'ohlcv_feed'), node('n_ema', 'ema')]);
    expect(isEdgeLegal(g, edge('e', 'n_data', 'close', 'n_ema', 'series'), REGISTRY)).toBeNull();
  });
});

describe('R2 no self loop', () => {
  it('rejects a node joined to itself and names the node', () => {
    const g = graph([node('n_add', 'add')]);
    const issue = isEdgeLegal(g, edge('e', 'n_add', 'out', 'n_add', 'b'), REGISTRY);
    expect(issue.code).toBe(CODE_SELF_LOOP);
    expect(issue.node_id).toBe('n_add');
    expect(issue.message).toContain('n_add');
  });

  it('accepts two different blocks', () => {
    const g = graph([node('n_ema', 'ema'), node('n_add', 'add')]);
    expect(isEdgeLegal(g, edge('e', 'n_ema', 'value', 'n_add', 'a'), REGISTRY)).toBeNull();
  });
});

describe('R3 ports exist and face the right way', () => {
  const g = graph([node('n_data', 'ohlcv_feed'), node('n_ema', 'ema')]);

  it('rejects an output port the descriptor does not publish, naming the port', () => {
    const issue = isEdgeLegal(g, edge('e', 'n_data', 'nope', 'n_ema', 'series'), REGISTRY);
    expect(issue.code).toBe(CODE_UNKNOWN_SOURCE_PORT);
    expect(issue.actual).toBe('nope');
    expect(issue.expected).toEqual(
      descriptorFor('ohlcv_feed').outputs.map((port) => port.port),
    );
  });

  it('rejects an input port the descriptor does not accept, naming the port', () => {
    const issue = isEdgeLegal(g, edge('e', 'n_data', 'close', 'n_ema', 'nope'), REGISTRY);
    expect(issue.code).toBe(CODE_UNKNOWN_TARGET_PORT);
    expect(issue.actual).toBe('nope');
    expect(issue.expected).toEqual(['series']);
  });

  it('accepts ports both descriptors declare', () => {
    expect(isEdgeLegal(g, edge('e', 'n_data', 'close', 'n_ema', 'series'), REGISTRY)).toBeNull();
  });

  it('reads the port list from the descriptor, not from the node', () => {
    // The node declares a port the descriptor does not, and omits the one it does. The
    // descriptor wins in both directions: a hand-edited payload cannot widen its contract.
    const tampered = graph([
      node('n_data', 'ohlcv_feed', { outputs: [{ port: 'invented', type: 'PRICE_SERIES' }] }),
      node('n_ema', 'ema', { inputs: [{ port: 'invented', type: 'PRICE_SERIES' }] }),
    ]);
    expect(isEdgeLegal(tampered, edge('e', 'n_data', 'invented', 'n_ema', 'series'), REGISTRY).code).toBe(
      CODE_UNKNOWN_SOURCE_PORT,
    );
    expect(isEdgeLegal(tampered, edge('e', 'n_data', 'close', 'n_ema', 'invented'), REGISTRY).code).toBe(
      CODE_UNKNOWN_TARGET_PORT,
    );
    expect(isEdgeLegal(tampered, edge('e', 'n_data', 'close', 'n_ema', 'series'), REGISTRY)).toBeNull();
  });
});

describe('R4 type compatibility', () => {
  const g = graph([node('n_data', 'ohlcv_feed'), node('n_ema', 'ema'), node('n_add', 'add')]);

  it('rejects SCALAR_SERIES feeding a PRICE_SERIES input, stating both types', () => {
    const issue = isEdgeLegal(g, edge('e', 'n_data', 'volume', 'n_ema', 'series'), REGISTRY);
    expect(issue.code).toBe(CODE_TYPE_MISMATCH);
    expect(issue.message).toContain('SCALAR_SERIES');
    expect(issue.message).toContain('PRICE_SERIES');
    expect(issue.fix_hint).toContain('SCALAR_SERIES');
    expect(issue.expected).toEqual(REGISTRY.compatibility_matrix.SCALAR_SERIES);
  });

  it('accepts a pair the served matrix permits', () => {
    expect(isEdgeLegal(g, edge('e', 'n_data', 'frame', 'n_ema', 'series'), REGISTRY)).toBeNull();
    expect(isEdgeLegal(g, edge('e', 'n_ema', 'value', 'n_add', 'a'), REGISTRY)).toBeNull();
  });

  it('follows the supplied matrix, so nothing about R4 is hardcoded', () => {
    const legal = edge('e', 'n_ema', 'value', 'n_add', 'a'); // SCALAR_SERIES -> SCALAR_SERIES
    const illegal = edge('e', 'n_data', 'volume', 'n_ema', 'series'); // SCALAR_SERIES -> PRICE_SERIES

    expect(isEdgeLegal(g, legal, REGISTRY)).toBeNull();
    expect(isEdgeLegal(g, illegal, REGISTRY).code).toBe(CODE_TYPE_MISMATCH);

    // Narrow the matrix: the previously legal pair must now be refused.
    const narrowed = registryWithMatrix({ SCALAR_SERIES: [] });
    expect(isEdgeLegal(g, legal, narrowed).code).toBe(CODE_TYPE_MISMATCH);
    expect(isEdgeLegal(g, legal, narrowed).expected).toEqual([]);

    // Widen the matrix: the previously illegal pair must now be accepted.
    const widened = registryWithMatrix({ SCALAR_SERIES: ['SCALAR_SERIES', 'PRICE_SERIES'] });
    expect(isEdgeLegal(g, illegal, widened)).toBeNull();
  });

  it('treats a port type absent from the supplied matrix as feeding nothing', () => {
    const stripped = { ...REGISTRY, compatibility_matrix: { OHLCV_FRAME: ['OHLCV_FRAME'] } };
    const issue = isEdgeLegal(g, edge('e', 'n_ema', 'value', 'n_add', 'a'), stripped);
    expect(issue.code).toBe(CODE_TYPE_MISMATCH);
    expect(issue.expected).toEqual([]);
  });
});

describe('R5 category adjacency', () => {
  it('rejects INDICATOR feeding ACTION and names both categories', () => {
    const g = graph([node('n_ema', 'ema'), node('n_action', 'action_buy_market')]);
    const issue = isEdgeLegal(g, edge('e', 'n_ema', 'value', 'n_action', 'signal'), REGISTRY);
    expect(issue.code).toBe(CODE_ILLEGAL_CATEGORY_FLOW);
    expect(issue.message).toContain('INDICATOR');
    expect(issue.message).toContain('ACTION');
    expect(issue.expected).toEqual(descriptorFor('ema').allowed_successor_categories);
  });

  it('accepts LOGIC feeding ACTION', () => {
    const g = graph([node('n_and', 'and'), node('n_action', 'action_buy_market')]);
    expect(isEdgeLegal(g, edge('e', 'n_and', 'out', 'n_action', 'signal'), REGISTRY)).toBeNull();
  });

  it("reads the source descriptor's declared successor categories, not a local table", () => {
    const g = graph([node('n_ema', 'ema'), node('n_action', 'action_buy_market')]);
    const candidate = edge('e', 'n_ema', 'value', 'n_action', 'signal');
    expect(isEdgeLegal(g, candidate, REGISTRY).code).toBe(CODE_ILLEGAL_CATEGORY_FLOW);

    // Declare ACTION an allowed successor of `ema` in the served payload. The verdict must
    // move to R4 (SCALAR_SERIES cannot feed SIGNAL), because R5 is answered from the payload.
    const widened = registryWith('ema', {
      allowed_successor_categories: [
        ...descriptorFor('ema').allowed_successor_categories,
        'ACTION',
      ],
    });
    expect(isEdgeLegal(g, candidate, widened).code).toBe(CODE_TYPE_MISMATCH);

    // Withdraw LOGIC from `gt`: a formerly legal LOGIC -> LOGIC edge must now be refused.
    const narrowed = registryWith('gt', { allowed_successor_categories: ['MATH'] });
    const logic = graph([node('n_gt', 'gt'), node('n_and', 'and')]);
    const logicEdge = edge('e', 'n_gt', 'out', 'n_and', 'a');
    expect(isEdgeLegal(logic, logicEdge, REGISTRY)).toBeNull();
    expect(isEdgeLegal(logic, logicEdge, narrowed).code).toBe(CODE_ILLEGAL_CATEGORY_FLOW);
  });
});

describe('R6 terminal source', () => {
  it('rejects an ACTION source and states that the block is terminal', () => {
    const g = graph([node('n_action', 'action_buy_market'), node('n_ema', 'ema')]);
    const issue = isEdgeLegal(g, edge('e', 'n_action', 'signal', 'n_ema', 'series'), REGISTRY);
    expect(issue.code).toBe(CODE_TERMINAL_HAS_NO_OUTPUT);
    expect(issue.message).toContain('terminal');
    expect(issue.actual).toContain('TERMINAL');
  });

  it('accepts a non-terminal source', () => {
    const g = graph([node('n_gt', 'gt'), node('n_and', 'and')]);
    expect(isEdgeLegal(g, edge('e', 'n_gt', 'out', 'n_and', 'a'), REGISTRY)).toBeNull();
  });

  it("reads the descriptor's terminality, not the block's category", () => {
    const g = graph([node('n_action', 'action_buy_market'), node('n_ema', 'ema')]);
    const candidate = edge('e', 'n_action', 'signal', 'n_ema', 'series');
    expect(isEdgeLegal(g, candidate, REGISTRY).code).toBe(CODE_TERMINAL_HAS_NO_OUTPUT);

    // Same ACTION category, but the served descriptor no longer declares TERMINAL: the
    // verdict must move on to the next rule that rejects it (R5, no successors declared).
    const notTerminal = registryWith('action_buy_market', {
      execution_semantics: 'SERIES_MAP',
    });
    expect(isEdgeLegal(g, candidate, notTerminal).code).toBe(CODE_ILLEGAL_CATEGORY_FLOW);
  });
});

describe('R7 single-arity input already occupied', () => {
  const nodes = [node('n_ema', 'ema'), node('n_sma', 'sma'), node('n_add', 'add')];

  it("rejects a second connection into a non-variadic input ('add.b')", () => {
    const g = graph(nodes, [edge('e_first', 'n_ema', 'value', 'n_add', 'b')]);
    const issue = isEdgeLegal(g, edge('e_second', 'n_sma', 'value', 'n_add', 'b'), REGISTRY);
    expect(issue.code).toBe(CODE_PORT_ALREADY_CONNECTED);
    expect(issue.message).toContain('accepts one connection');
    expect(issue.expected).toBe(1);
    expect(issue.actual).toBe(2);
    expect(descriptorFor('add').inputs.find((port) => port.port === 'b').variadic).toBeUndefined();
  });

  it("accepts a second connection into a variadic input ('add.a')", () => {
    const g = graph(nodes, [edge('e_first', 'n_ema', 'value', 'n_add', 'a')]);
    expect(isEdgeLegal(g, edge('e_second', 'n_sma', 'value', 'n_add', 'a'), REGISTRY)).toBeNull();
    expect(descriptorFor('add').inputs.find((port) => port.port === 'a').variadic).toBe(true);
  });

  it('accepts re-judging the edge that already occupies the port', () => {
    const existing = edge('e_first', 'n_ema', 'value', 'n_add', 'b');
    const g = graph(nodes, [existing]);
    expect(isEdgeLegal(g, existing, REGISTRY)).toBeNull();
  });

  it('answers R7 identically with and without the inbound index', () => {
    const g = graph(nodes, [edge('e_first', 'n_ema', 'value', 'n_add', 'b')]);
    const candidate = edge('e_second', 'n_sma', 'value', 'n_add', 'b');
    const scanned = isEdgeLegal(g, candidate, REGISTRY);
    const indexed = isEdgeLegal(g, candidate, REGISTRY, {
      inbound: buildInboundIndex(g),
      nodeIndex: buildNodeIndex(g),
    });
    expect(indexed).toEqual(scanned);
  });
});

describe('R8 cycle', () => {
  it('rejects an edge that closes a loop and names the closed path', () => {
    const g = graph(
      [node('n_add', 'add'), node('n_mul', 'multiply')],
      [edge('e_fwd', 'n_add', 'out', 'n_mul', 'a')],
    );
    const issue = isEdgeLegal(g, edge('e_back', 'n_mul', 'out', 'n_add', 'b'), REGISTRY);
    expect(issue.code).toBe(CODE_CYCLE);
    expect(issue.actual).toEqual(['n_add', 'n_mul', 'n_add']);
    expect(issue.edge_id).toBe('e_back');
    expect(issue.message).toBe('Connection would create a loop: n_add -> n_mul -> n_add');
  });

  it('accepts a fan-out that closes nothing', () => {
    const g = graph(
      [node('n_add', 'add'), node('n_mul', 'multiply')],
      [edge('e_fwd', 'n_add', 'out', 'n_mul', 'a')],
    );
    expect(isEdgeLegal(g, edge('e2', 'n_add', 'out', 'n_mul', 'b'), REGISTRY)).toBeNull();
  });

  it('suppresses only R8 when checkCycle is false', () => {
    const g = graph(
      [node('n_add', 'add'), node('n_mul', 'multiply')],
      [edge('e_fwd', 'n_add', 'out', 'n_mul', 'a')],
    );
    const candidate = edge('e_back', 'n_mul', 'out', 'n_add', 'b');
    expect(isEdgeLegal(g, candidate, REGISTRY).code).toBe(CODE_CYCLE);
    expect(isEdgeLegal(g, candidate, REGISTRY, { checkCycle: false })).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// The rule order, which is what makes the client's reason the backend's reason
// ---------------------------------------------------------------------------

describe('rule order matches the backend (R1 R2 R6 R5 R3 R4 R7 R8)', () => {
  it('declares the backend order as data', () => {
    // R3 contributes two codes (source port, target port); the rule sequence is what matters.
    const rules = RULE_ORDER.map((entry) => entry.rule).filter(
      (rule, position, all) => position === 0 || all[position - 1] !== rule,
    );
    expect(rules).toEqual(['R1', 'R2', 'R6', 'R5', 'R3', 'R4', 'R7', 'R8']);
    expect(RULE_ORDER.map((entry) => entry.code)).toEqual([
      CODE_EDGE_ENDPOINT_UNKNOWN,
      CODE_SELF_LOOP,
      CODE_TERMINAL_HAS_NO_OUTPUT,
      CODE_ILLEGAL_CATEGORY_FLOW,
      CODE_UNKNOWN_SOURCE_PORT,
      CODE_UNKNOWN_TARGET_PORT,
      CODE_TYPE_MISMATCH,
      CODE_PORT_ALREADY_CONNECTED,
      CODE_CYCLE,
    ]);
  });

  it('blames terminality, not an unknown port, for an ACTION source', () => {
    // An ACTION descriptor declares no output ports at all, so R3 evaluated before R6 would
    // report UNKNOWN_SOURCE_PORT and tell the author to pick a different port — which cannot
    // be done. The backend puts R6 first for exactly this reason.
    expect(descriptorFor('action_buy_market').outputs).toEqual([]);
    const g = graph([node('n_action', 'action_buy_market'), node('n_ema', 'ema')]);
    for (const sourcePort of ['signal', 'out', 'anything']) {
      const issue = isEdgeLegal(g, edge('e', 'n_action', sourcePort, 'n_ema', 'series'), REGISTRY);
      expect(issue.code).toBe(CODE_TERMINAL_HAS_NO_OUTPUT);
      expect(issue.code).not.toBe(CODE_UNKNOWN_SOURCE_PORT);
    }
  });

  it('refuses ACTION -> DATA, ACTION -> INDICATOR and ACTION -> ML_DL through R6', () => {
    const cases = [
      ['n_data', 'ohlcv_feed', 'series'],
      ['n_ema', 'ema', 'series'],
      ['n_ml', 'xgboost', 'features'],
    ];
    for (const [targetId, blockId, targetPort] of cases) {
      const g = graph([node('n_action', 'action_buy_market'), node(targetId, blockId)]);
      const issue = isEdgeLegal(g, edge('e', 'n_action', 'out', targetId, targetPort), REGISTRY);
      expect(issue.code).toBe(CODE_TERMINAL_HAS_NO_OUTPUT);
    }
  });

  it('refuses ML_DL -> DATA through R5, not through an unknown port', () => {
    // A DATA block declares no inputs, so R3 would blame the port. R5 first says the real
    // thing: an ML_DL block may not feed a DATA block.
    expect(descriptorFor('ohlcv_feed').inputs).toEqual([]);
    const g = graph([node('n_ml', 'xgboost'), node('n_data', 'ohlcv_feed')]);
    const issue = isEdgeLegal(g, edge('e', 'n_ml', 'prediction', 'n_data', 'series'), REGISTRY);
    expect(issue.code).toBe(CODE_ILLEGAL_CATEGORY_FLOW);
    expect(issue.code).not.toBe(CODE_UNKNOWN_TARGET_PORT);
  });

  it('blames the self loop before the type mismatch', () => {
    const g = graph([node('n_ema', 'ema')]);
    // ema.value is SCALAR_SERIES and ema.series wants PRICE_SERIES: both R2 and R4 reject.
    const issue = isEdgeLegal(g, edge('e', 'n_ema', 'value', 'n_ema', 'series'), REGISTRY);
    expect(issue.code).toBe(CODE_SELF_LOOP);
  });

  it('blames the type mismatch before the cycle', () => {
    const g = graph(
      [node('n_add', 'add'), node('n_mul', 'multiply'), node('n_gt', 'gt')],
      [
        edge('e_1', 'n_add', 'out', 'n_mul', 'a'),
        edge('e_2', 'n_mul', 'out', 'n_gt', 'left'),
      ],
    );
    // gt.out is BOOLEAN_SERIES into add.b which wants SCALAR_SERIES, and the edge would also
    // close a loop. R4 runs first, so the author is told about the type.
    const issue = isEdgeLegal(g, edge('e_back', 'n_gt', 'out', 'n_add', 'b'), REGISTRY);
    expect(issue.code).toBe(CODE_TYPE_MISMATCH);
  });
});

// ---------------------------------------------------------------------------
// Cycle detection: the path, and the stack
// ---------------------------------------------------------------------------

describe('findCycle', () => {
  it('returns the true closed path, not a visited set', () => {
    const nodes = ['a', 'b', 'c', 'd'];
    const edges = [
      edge('e1', 'a', 'out', 'b', 'in'),
      edge('e2', 'b', 'out', 'c', 'in'),
      edge('e3', 'c', 'out', 'a', 'in'),
      edge('e4', 'a', 'out', 'd', 'in'), // visited, but not on the cycle
    ];
    expect(findCycle(nodes, edges)).toEqual(['a', 'b', 'c', 'a']);
  });

  it('excludes nodes that were visited on the way in but are not on the cycle', () => {
    const nodes = ['root', 'a', 'b', 'c'];
    const edges = [
      edge('e1', 'root', 'out', 'a', 'in'),
      edge('e2', 'a', 'out', 'b', 'in'),
      edge('e3', 'b', 'out', 'c', 'in'),
      edge('e4', 'c', 'out', 'a', 'in'),
    ];
    // The cycle starts at 'a'; 'root' feeds it but is not part of it.
    expect(findCycle(nodes, edges)).toEqual(['a', 'b', 'c', 'a']);
  });

  it('returns an empty list for a DAG, including a diamond', () => {
    const nodes = ['a', 'b', 'c', 'd'];
    const edges = [
      edge('e1', 'a', 'out', 'b', 'in'),
      edge('e2', 'a', 'out', 'c', 'in'),
      edge('e3', 'b', 'out', 'd', 'in'),
      edge('e4', 'c', 'out', 'd', 'in'),
    ];
    expect(findCycle(nodes, edges)).toEqual([]);
  });

  it('ignores edge endpoints that are not in the node list', () => {
    expect(findCycle(['a'], [edge('e', 'a', 'out', 'ghost', 'in')])).toEqual([]);
  });

  it('walks a 5000-node chain without exhausting the call stack', () => {
    const nodes = [];
    const edges = [];
    for (let i = 0; i < 5000; i += 1) {
      nodes.push(`n${i}`);
      if (i > 0) edges.push(edge(`e${i}`, `n${i - 1}`, 'out', `n${i}`, 'in'));
    }
    expect(findCycle(nodes, edges)).toEqual([]);

    // Close the chain into one 5000-node loop: the whole path comes back, closed.
    edges.push(edge('e_close', 'n4999', 'out', 'n0', 'in'));
    const cycle = findCycle(nodes, edges);
    expect(cycle).toHaveLength(5001);
    expect(cycle[0]).toBe('n0');
    expect(cycle[5000]).toBe('n0');
    expect(cycle[1]).toBe('n1');
    expect(cycle[4999]).toBe('n4999');
  });

  it('answers R8 on a 5000-node chain without exhausting the call stack', () => {
    const nodes = [];
    const edges = [];
    for (let i = 0; i < 5000; i += 1) {
      nodes.push(node(`n${i}`, 'multiply'));
      if (i > 0) edges.push(edge(`e${i}`, `n${i - 1}`, 'out', `n${i}`, 'a'));
    }
    const g = graph(nodes, edges);

    const closing = edge('e_close', 'n4999', 'out', 'n0', 'b');
    expect(createsCycle(g, closing)).toBe(true);
    expect(cyclePathWithEdge(g, closing)).toHaveLength(5001);

    const issue = isEdgeLegal(g, closing, REGISTRY);
    expect(issue.code).toBe(CODE_CYCLE);
    expect(issue.actual[0]).toBe('n0');
    expect(issue.actual[issue.actual.length - 1]).toBe('n0');

    // A forward edge on the same deep chain stays legal.
    expect(isEdgeLegal(g, edge('e_fwd', 'n0', 'out', 'n4999', 'b'), REGISTRY)).toBeNull();
  });

  it('treats a self loop as a cycle without consulting the graph', () => {
    expect(createsCycle(graph([]), edge('e', 'x', 'out', 'x', 'in'))).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Drag-time dimming (Requirement 6.1)
// ---------------------------------------------------------------------------

describe('legalTargetsForDrag', () => {
  const canvas = () =>
    graph([
      node('n_data', 'ohlcv_feed'),
      node('n_ema', 'ema'),
      node('n_add', 'add'),
      node('n_feat', 'feat_lag'),
      node('n_ml', 'xgboost'),
      node('n_action', 'action_buy_market'),
    ]);

  it('marks exactly the compatible target ports legal when dragging a PRICE_SERIES output', () => {
    const result = legalTargetsForDrag(canvas(), { node_id: 'n_data', port: 'close' }, REGISTRY);

    expect(result.origin).toEqual({ node_id: 'n_data', port: 'close', type: 'PRICE_SERIES' });
    expect([...result.legalPortKeys].sort()).toEqual(
      [
        portKey('n_ema', 'series'),
        portKey('n_add', 'a'),
        portKey('n_add', 'b'),
        portKey('n_feat', 'series'),
      ].sort(),
    );
    expect([...result.illegalPortKeys].sort()).toEqual(
      [portKey('n_ml', 'features'), portKey('n_action', 'signal')].sort(),
    );

    expect(result.isPortLegal('n_ema', 'series')).toBe(true);
    expect(result.isPortLegal('n_ml', 'features')).toBe(false);
    expect(result.isNodeLegal('n_add')).toBe(true);
    expect(result.isNodeLegal('n_action')).toBe(false);
  });

  it('carries the rejecting reason for each dimmed port, so the tooltip agrees with the drop', () => {
    const g = canvas();
    const result = legalTargetsForDrag(g, { node_id: 'n_data', port: 'close' }, REGISTRY);

    expect(result.verdictFor('n_ml', 'features').code).toBe(CODE_TYPE_MISMATCH);
    expect(result.verdictFor('n_action', 'signal').code).toBe(CODE_ILLEGAL_CATEGORY_FLOW);
    expect(result.verdictFor('n_data', 'anything')).toBeNull();

    // The dim-time verdict is the drop-time verdict, evaluated by the same function.
    for (const verdict of result.verdicts) {
      const onDrop = isEdgeLegal(
        g,
        edge(DRAG_CANDIDATE_EDGE_ID, 'n_data', 'close', verdict.node_id, verdict.port),
        REGISTRY,
      );
      expect(onDrop === null).toBe(verdict.legal);
      if (onDrop !== null) expect(onDrop.code).toBe(verdict.code);
    }
  });

  it('reports a self-connection as a self loop rather than dimming it silently', () => {
    const result = legalTargetsForDrag(canvas(), { node_id: 'n_ema', port: 'value' }, REGISTRY);
    expect(result.verdictFor('n_ema', 'series').code).toBe(CODE_SELF_LOOP);
    expect(result.isPortLegal('n_ema', 'series')).toBe(false);
  });

  it('dims a non-variadic port that is already occupied and leaves a variadic one open', () => {
    const g = graph(
      [node('n_ema', 'ema'), node('n_sma', 'sma'), node('n_add', 'add')],
      [
        edge('e_a', 'n_ema', 'value', 'n_add', 'a'),
        edge('e_b', 'n_ema', 'value', 'n_add', 'b'),
      ],
    );
    const result = legalTargetsForDrag(g, { node_id: 'n_sma', port: 'value' }, REGISTRY);
    expect(result.isPortLegal('n_add', 'a')).toBe(true);
    expect(result.isPortLegal('n_add', 'b')).toBe(false);
    expect(result.verdictFor('n_add', 'b').code).toBe(CODE_PORT_ALREADY_CONNECTED);
  });

  it('enumerates the descriptors\u2019 input ports, never the nodes\u2019 declared ones', () => {
    const g = graph([
      node('n_data', 'ohlcv_feed'),
      node('n_ema', 'ema', { inputs: [{ port: 'invented', type: 'PRICE_SERIES' }] }),
    ]);
    const result = legalTargetsForDrag(g, { node_id: 'n_data', port: 'close' }, REGISTRY);
    expect(result.verdicts.map((verdict) => verdict.port)).toEqual(['series']);
  });

  it('accepts React Flow\u2019s onConnectStart payload as the drag origin', () => {
    const result = legalTargetsForDrag(
      canvas(),
      { nodeId: 'n_data', handleId: 'close', handleType: 'source' },
      REGISTRY,
    );
    expect(result.isPortLegal('n_ema', 'series')).toBe(true);
  });

  it('refuses to guess a drag origin', () => {
    expect(() => legalTargetsForDrag(canvas(), { nodeId: 'n_data' }, REGISTRY)).toThrow(
      ConnectionLegalityError,
    );
    expect(() => legalTargetsForDrag(canvas(), null, REGISTRY)).toThrow(ConnectionLegalityError);
  });

  it('follows the supplied matrix, so the dimming cannot drift from the served rules', () => {
    const widened = registryWithMatrix({ PRICE_SERIES: ['PRICE_SERIES', 'SCALAR_SERIES', 'FEATURE_MATRIX'] });
    const result = legalTargetsForDrag(canvas(), { node_id: 'n_data', port: 'close' }, widened);
    expect(result.isPortLegal('n_ml', 'features')).toBe(true);
  });

  it('is marked provisional: the backend still decides', () => {
    const result = legalTargetsForDrag(canvas(), { node_id: 'n_data', port: 'close' }, REGISTRY);
    expect(result.provisional).toBe(true);
    expect(result.authority).toBe(AUTHORITY_CLIENT_PROVISIONAL);
  });
});

// ---------------------------------------------------------------------------
// The backend stays authoritative
// ---------------------------------------------------------------------------

describe('the local verdict is provisional and the backend wins', () => {
  const g = graph([node('n_data', 'ohlcv_feed'), node('n_ema', 'ema')]);
  const legal = edge('e', 'n_data', 'close', 'n_ema', 'series');

  it('marks every accepted local verdict provisional', () => {
    const verdict = checkConnection(g, legal, REGISTRY);
    expect(verdict.accepted).toBe(true);
    expect(verdict.provisional).toBe(true);
    expect(verdict.authority).toBe(AUTHORITY_CLIENT_PROVISIONAL);
    expect(verdict.issue).toBeNull();
  });

  it('carries the rejecting reason on a refusal', () => {
    const verdict = checkConnection(g, edge('e', 'n_data', 'volume', 'n_ema', 'series'), REGISTRY);
    expect(verdict.accepted).toBe(false);
    expect(verdict.code).toBe(CODE_TYPE_MISMATCH);
    expect(verdict.message).toContain('cannot feed');
  });

  it('cannot suppress a backend rejection with a local pass', () => {
    const local = checkConnection(g, legal, REGISTRY);
    expect(local.accepted).toBe(true);

    const backendIssue = makeIssue('SOME_BACKEND_RULE', SEVERITY_ERROR, 'The server said no', {
      edgeId: 'e',
    });
    const reconciled = reconcileWithBackend(local, [backendIssue]);
    expect(reconciled.accepted).toBe(false);
    expect(reconciled.authority).toBe(AUTHORITY_BACKEND);
    expect(reconciled.provisional).toBe(false);
    expect(reconciled.issue).toEqual(backendIssue);
    expect(reconciled.local.accepted).toBe(true);
  });

  it('lets the backend accept an edge the client refused', () => {
    const local = checkConnection(g, edge('e', 'n_data', 'volume', 'n_ema', 'series'), REGISTRY);
    expect(local.accepted).toBe(false);
    const reconciled = reconcileWithBackend(local, []);
    expect(reconciled.accepted).toBe(true);
    expect(reconciled.authority).toBe(AUTHORITY_BACKEND);
  });

  it('stays provisional until a backend answer is in hand', () => {
    const reconciled = reconcileWithBackend(checkConnection(g, legal, REGISTRY), null);
    expect(reconciled.provisional).toBe(true);
    expect(reconciled.authority).toBe(AUTHORITY_CLIENT_PROVISIONAL);
  });

  it('does not treat a backend warning as a rejection', () => {
    const local = checkConnection(g, legal, REGISTRY);
    const warning = makeIssue('PORT_CONTRACT_RECOMPUTED', 'warning', 'Stale ports', {
      edgeId: 'e',
    });
    const reconciled = reconcileWithBackend(local, [warning]);
    expect(reconciled.accepted).toBe(true);
    expect(reconciled.issues).toEqual([warning]);
  });

  it('ignores backend issues about a different edge', () => {
    const local = checkConnection(g, legal, REGISTRY);
    const other = makeIssue('CYCLE', SEVERITY_ERROR, 'Another edge', { edgeId: 'e_other' });
    expect(reconcileWithBackend(local, [other]).accepted).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Fail closed
// ---------------------------------------------------------------------------

describe('fail closed rather than assume legality', () => {
  it('throws when there is no registry payload', () => {
    const g = graph([node('n_data', 'ohlcv_feed'), node('n_ema', 'ema')]);
    const candidate = edge('e', 'n_data', 'close', 'n_ema', 'series');
    for (const bad of [undefined, null, 'registry', 42]) {
      expect(() => isEdgeLegal(g, candidate, bad)).toThrow(ConnectionLegalityError);
    }
  });

  it('throws when the payload carries no block list or no compatibility matrix', () => {
    expect(() => buildRegistryIndex({ compatibility_matrix: {} })).toThrow(
      /carries no 'blocks'/,
    );
    expect(() => buildRegistryIndex({ blocks: [] })).toThrow(/compatibility_matrix/);
  });

  it('throws on a malformed graph or edge instead of returning a verdict', () => {
    expect(() => isEdgeLegal(null, {}, REGISTRY)).toThrow(ConnectionLegalityError);
    expect(() => isEdgeLegal(graph([]), null, REGISTRY)).toThrow(ConnectionLegalityError);
  });

  it('reports an unresolved block as an unknown port rather than as legal', () => {
    const g = graph([
      { ...node('n_ema', 'ema'), block_id: 'no_such_block' },
      node('n_add', 'add'),
    ]);
    const issue = isEdgeLegal(g, edge('e', 'n_ema', 'value', 'n_add', 'a'), REGISTRY);
    expect(issue.code).toBe(CODE_UNKNOWN_SOURCE_PORT);
    expect(issue.message).toContain('no descriptor');
  });

  it('is idempotent over an already-built registry index', () => {
    const index = buildRegistryIndex(REGISTRY);
    expect(buildRegistryIndex(index)).toBe(index);
    const g = graph([node('n_data', 'ohlcv_feed'), node('n_ema', 'ema')]);
    expect(isEdgeLegal(g, edge('e', 'n_data', 'close', 'n_ema', 'series'), index)).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// React Flow adapters (wired into the canvas by a later task, not this one)
// ---------------------------------------------------------------------------

describe('React Flow adapters', () => {
  const g = graph([node('n_data', 'ohlcv_feed'), node('n_ema', 'ema')]);

  it('maps a React Flow connection onto a candidate edge without guessing a port', () => {
    expect(
      connectionToEdge({
        source: 'n_data',
        sourceHandle: 'close',
        target: 'n_ema',
        targetHandle: 'series',
      }),
    ).toEqual({
      id: DRAG_CANDIDATE_EDGE_ID,
      source: 'n_data',
      source_port: 'close',
      target: 'n_ema',
      target_port: 'series',
    });

    expect(
      connectionToEdge({ source: 'n_data', sourceHandle: null, target: 'n_ema', targetHandle: null }),
    ).toMatchObject({ source_port: null, target_port: null });
  });

  it('answers isValidConnection and hands the reason to onReject', () => {
    const rejections = [];
    const isValidConnection = reactFlowConnectionValidator({
      graph: g,
      registry: REGISTRY,
      onReject: (issue) => rejections.push(issue),
    });

    expect(
      isValidConnection({
        source: 'n_data',
        sourceHandle: 'close',
        target: 'n_ema',
        targetHandle: 'series',
      }),
    ).toBe(true);
    expect(rejections).toHaveLength(0);

    expect(
      isValidConnection({
        source: 'n_data',
        sourceHandle: 'volume',
        target: 'n_ema',
        targetHandle: 'series',
      }),
    ).toBe(false);
    expect(rejections).toHaveLength(1);
    expect(rejections[0].code).toBe(CODE_TYPE_MISMATCH);

    // A connection with no handle is refused, not guessed.
    expect(
      isValidConnection({ source: 'n_data', sourceHandle: null, target: 'n_ema', targetHandle: null }),
    ).toBe(false);
    expect(rejections[1].code).toBe(CODE_UNKNOWN_SOURCE_PORT);
  });

  it('re-reads the graph through a getter, so canvas edits are picked up', () => {
    let current = graph([node('n_add', 'add'), node('n_mul', 'multiply')]);
    const isValidConnection = reactFlowConnectionValidator({
      graph: () => current,
      registry: REGISTRY,
    });
    const connection = {
      source: 'n_mul',
      sourceHandle: 'out',
      target: 'n_add',
      targetHandle: 'b',
    };
    expect(isValidConnection(connection)).toBe(true);

    // The author draws add -> mul; the same connection now closes a loop.
    current = graph(current.nodes, [edge('e_fwd', 'n_add', 'out', 'n_mul', 'a')]);
    expect(isValidConnection(connection)).toBe(false);
  });
});
