"""Test script for strategy event worker."""

import asyncio
import sys
import os

# Add backend to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "backend"))

from backend.services.event_bus import (
    event_bus,
    MARKET_EVENTS_CHANNEL,
    ORDER_EVENTS_CHANNEL,
)
from backend.services.cache import redis_manager


async def test_order_callback(event):
    """Callback to capture order events generated by strategy."""
    print(f"📦 Order Event Received: {event.get('type')} - {event.get('order_id')}")
    if event.get("type") == "ORDER_REQUEST":
        signal = event.get("signal", {})
        print(f"   Action: {signal.get('action')}")
        print(f"   Symbol: {event.get('symbol')}")
        print(f"   Amount: {event.get('amount')}")
        print(f"   Confidence: {signal.get('confidence')}")
        print(f"   Reason: {signal.get('reason')}")


async def test_strategy_worker():
    """Test the strategy event worker."""
    print("=" * 60)
    print("Testing Strategy Event Worker")
    print("=" * 60)

    # Connect to Redis
    await redis_manager.connect()

    # Subscribe to order events (to capture generated orders)
    await event_bus.subscribe(ORDER_EVENTS_CHANNEL, test_order_callback)
    # Subscribe to events (listener starts automatically)
    await event_bus.subscribe(
        ORDER_EVENTS_CHANNEL, lambda e: print(f"Order event: {e}")
    )
    await event_bus.subscribe(
        MARKET_EVENTS_CHANNEL, lambda e: print(f"Market event: {e}")
    )

    await asyncio.sleep(0.5)

    # Import strategy worker after Redis is connected
    from backend.services.workers.strategy_event_worker import strategy_event_worker

    # Start strategy worker
    await strategy_event_worker.start()

    # Register a test strategy (MA crossover)
    print("\nRegistering MA crossover strategy...")
    await strategy_event_worker.register_strategy(
        "test_user",
        {
            "type": "simple_ma_crossover",
            "symbol": "BTC/USDT",
            "short_period": 5,
            "long_period": 10,
            "amount": 0.1,
        },
    )

    # Simulate price updates to trigger signals
    print("\nSimulating price updates...")

    # Generate price history that will trigger a golden cross
    base_price = 50000.0
    for i in range(30):
        # Create a trend that will cause MA crossover
        if i < 15:
            price = base_price - (i * 100)  # Downtrend
        else:
            price = base_price - 1500 + ((i - 15) * 200)  # Uptrend

        price_event = {
            "type": "price_update",
            "symbol": "BTC/USDT",
            "price": price,
            "timestamp": 1234567890000 + i * 1000,
        }

        await event_bus.publish(MARKET_EVENTS_CHANNEL, price_event)
        await asyncio.sleep(0.1)

    # Wait for signal generation
    await asyncio.sleep(2)

    # Test RSI strategy
    print("\nRegistering RSI strategy...")
    await strategy_event_worker.unregister_strategy("test_user")
    await strategy_event_worker.register_strategy(
        "test_user",
        {
            "type": "rsi",
            "symbol": "ETH/USDT",
            "period": 14,
            "oversold": 30,
            "overbought": 70,
            "amount": 1.0,
        },
    )

    # Simulate price drops to trigger oversold
    print("\nSimulating price drops for RSI oversold...")
    for i in range(20):
        price = 3000.0 - (i * 50)  # Sharp drop

        price_event = {
            "type": "price_update",
            "symbol": "ETH/USDT",
            "price": price,
            "timestamp": 1234567890000 + i * 1000,
        }

        await event_bus.publish(MARKET_EVENTS_CHANNEL, price_event)
        await asyncio.sleep(0.1)

    # Wait for signal generation
    await asyncio.sleep(2)

    # Cleanup
    await strategy_event_worker.stop()
    await event_bus.close()
    await redis_manager.close()

    print("\n" + "=" * 60)
    print("✅ Strategy worker tests completed")
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(test_strategy_worker())
