"""
Signal Deduplication - Phase 6 Correctness Fix

This module implements signal deduplication to prevent duplicate signal generation
and race conditions. This is a critical correctness fix for the strict algo trading
platform.

Key Features:
- Deterministic signal ID generation
- Distributed signal deduplication
- Signal sequence number management
- Race condition prevention
- Signal state persistence

Author: Principal Institutional Algo Execution Validation Engineer
"""

import hashlib
import logging
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from backend_app.core.cache.redis_manager import redis_manager

logger = logging.getLogger("signal_deduplication")


class SignalDeduplicator:
    """
    Signal deduplicator for preventing duplicate signal generation.
    
    Prevents duplicate signals from being generated by concurrent workers
    and prevents race conditions in signal generation.
    """
    
    def __init__(self):
        """Initialize signal deduplicator."""
        self.redis = redis_manager
        
        # Configuration
        self.signal_id_ttl = 86400  # 24 hours
        self.sequence_ttl = 3600  # 1 hour
        self.lock_ttl = 60  # 1 minute
    
    async def generate_signal_id(
        self,
        tenant_id: str,
        strategy_id: str,
        timestamp: datetime,
        market_data_hash: str
    ) -> str:
        """
        Generate deterministic signal ID for deduplication.
        
        Args:
            tenant_id: Tenant ID
            strategy_id: Strategy ID
            timestamp: Signal timestamp
            market_data_hash: Hash of market data
            
        Returns:
            Signal ID string
        """
        # Create deterministic signal ID
        signal_id_str = f"{tenant_id}:{strategy_id}:{timestamp.isoformat()}:{market_data_hash}"
        
        # Hash for consistency
        signal_id_hash = hashlib.sha256(signal_id_str.encode()).hexdigest()[:16]
        
        return f"signal_{signal_id_hash}"
    
    async def check_duplicate_signal(
        self,
        signal_id: str,
        tenant_id: str
    ) -> bool:
        """
        Check if signal has already been generated.
        
        Args:
            signal_id: Signal ID
            tenant_id: Tenant ID
            
        Returns:
            True if duplicate, False otherwise
        """
        try:
            # Check Redis for existing signal
            key = f"signal_id:{tenant_id}:{signal_id}"
            exists = await self.redis.exists(key)
            
            if exists:
                logger.warning(f"Duplicate signal detected: {signal_id}")
                return True
            
            return False
            
        except Exception as e:
            logger.error(f"Duplicate signal check failed: {e}")
            # Fail safe: assume not duplicate to prevent blocking
            return False
    
    async def record_signal(
        self,
        signal_id: str,
        tenant_id: str,
        signal_data: Dict[str, Any]
    ) -> bool:
        """
        Record signal generation for deduplication.
        
        Args:
            signal_id: Signal ID
            tenant_id: Tenant ID
            signal_data: Signal data
            
        Returns:
            True if recorded successfully, False otherwise
        """
        try:
            # Store in Redis
            key = f"signal_id:{tenant_id}:{signal_id}"
            await self.redis.setex(
                key,
                self.signal_id_ttl,
                "generated"
            )
            
            # Store signal data
            data_key = f"signal_data:{tenant_id}:{signal_id}"
            await self.redis.setex(
                data_key,
                self.signal_id_ttl,
                str(signal_data)
            )
            
            logger.info(f"Signal recorded: {signal_id}")
            return True
            
        except Exception as e:
            logger.error(f"Signal recording failed: {e}")
            return False
    
    async def acquire_signal_lock(
        self,
        signal_id: str,
        tenant_id: str
    ) -> bool:
        """
        Acquire distributed lock for signal generation.
        
        Args:
            signal_id: Signal ID
            tenant_id: Tenant ID
            
        Returns:
            True if lock acquired, False otherwise
        """
        try:
            lock_key = f"signal_lock:{tenant_id}:{signal_id}"
            
            # Try to acquire lock
            acquired = await self.redis.set(
                lock_key,
                "locked",
                ex=self.lock_ttl,
                nx=True
            )
            
            if acquired:
                logger.debug(f"Signal lock acquired: {signal_id}")
                return True
            else:
                logger.warning(f"Signal lock already held: {signal_id}")
                return False
            
        except Exception as e:
            logger.error(f"Signal lock acquisition failed: {e}")
            return False
    
    async def release_signal_lock(
        self,
        signal_id: str,
        tenant_id: str
    ) -> bool:
        """
        Release distributed lock for signal generation.
        
        Args:
            signal_id: Signal ID
            tenant_id: Tenant ID
            
        Returns:
            True if lock released, False otherwise
        """
        try:
            lock_key = f"signal_lock:{tenant_id}:{signal_id}"
            await self.redis.delete(lock_key)
            
            logger.debug(f"Signal lock released: {signal_id}")
            return True
            
        except Exception as e:
            logger.error(f"Signal lock release failed: {e}")
            return False
    
    async def generate_signal_deduplicated(
        self,
        tenant_id: str,
        strategy_id: str,
        timestamp: datetime,
        market_data_hash: str,
        signal_data: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Generate signal with deduplication and race condition prevention.
        
        Args:
            tenant_id: Tenant ID
            strategy_id: Strategy ID
            timestamp: Signal timestamp
            market_data_hash: Hash of market data
            signal_data: Signal data
            
        Returns:
            Signal generation result
        """
        try:
            # Generate signal ID
            signal_id = await self.generate_signal_id(
                tenant_id,
                strategy_id,
                timestamp,
                market_data_hash
            )
            
            # Check for duplicate
            is_duplicate = await self.check_duplicate_signal(
                signal_id,
                tenant_id
            )
            
            if is_duplicate:
                logger.warning(f"Duplicate signal generation blocked: {signal_id}")
                return {
                    "success": False,
                    "error": "duplicate_signal",
                    "signal_id": signal_id,
                    "message": "Signal already generated with this ID"
                }
            
            # Acquire lock for race condition prevention
            lock_acquired = await self.acquire_signal_lock(
                signal_id,
                tenant_id
            )
            
            if not lock_acquired:
                logger.warning(f"Signal generation blocked by lock: {signal_id}")
                return {
                    "success": False,
                    "error": "signal_lock_held",
                    "signal_id": signal_id,
                    "message": "Signal generation in progress by another worker"
                }
            
            try:
                # Double-check for duplicate after acquiring lock
                is_duplicate = await self.check_duplicate_signal(
                    signal_id,
                    tenant_id
                )
                
                if is_duplicate:
                    logger.warning(f"Duplicate signal detected after lock: {signal_id}")
                    return {
                        "success": False,
                        "error": "duplicate_signal",
                        "signal_id": signal_id,
                        "message": "Signal already generated while waiting for lock"
                    }
                
                # Record signal
                recorded = await self.record_signal(
                    signal_id,
                    tenant_id,
                    signal_data
                )
                
                if not recorded:
                    logger.error(f"Failed to record signal: {signal_id}")
                    return {
                        "success": False,
                        "error": "signal_recording_failed",
                        "signal_id": signal_id,
                        "message": "Failed to record signal for deduplication"
                    }
                
                result = {
                    "success": True,
                    "signal_id": signal_id,
                    "generated_at": datetime.now(timezone.utc).isoformat(),
                    "signal_data": signal_data
                }
                
                logger.info(f"Signal generated deduplicated: {signal_id}")
                return result
                
            finally:
                # Release lock
                await self.release_signal_lock(signal_id, tenant_id)
            
        except Exception as e:
            logger.error(f"Deduplicated signal generation failed: {e}")
            return {
                "success": False,
                "error": "deduplicated_generation_failed",
                "message": str(e)
            }
    
    async def get_signal_status(
        self,
        signal_id: str,
        tenant_id: str
    ) -> Optional[Dict[str, Any]]:
        """
        Get signal status for signal ID.
        
        Args:
            signal_id: Signal ID
            tenant_id: Tenant ID
            
        Returns:
            Signal status or None if not found
        """
        try:
            key = f"signal_id:{tenant_id}:{signal_id}"
            exists = await self.redis.exists(key)
            
            if not exists:
                return None
            
            data_key = f"signal_data:{tenant_id}:{signal_id}"
            data = await self.redis.get(data_key)
            
            return {
                "signal_id": signal_id,
                "status": "generated",
                "data": data
            }
            
        except Exception as e:
            logger.error(f"Failed to get signal status: {e}")
            return None
    
    async def cleanup_old_signals(self, tenant_id: str, hours: int = 24):
        """
        Clean up old signal records.
        
        Args:
            tenant_id: Tenant ID
            hours: Hours to keep
        """
        try:
            # This would scan and delete old signal records
            # For now, rely on Redis TTL
            logger.info(f"Signal cleanup relies on TTL for tenant: {tenant_id}")
            
        except Exception as e:
            logger.error(f"Signal cleanup failed: {e}")


# Global instance
_signal_deduplicator: Optional[SignalDeduplicator] = None


def get_signal_deduplicator() -> SignalDeduplicator:
    """Get or create signal deduplicator instance."""
    global _signal_deduplicator
    if _signal_deduplicator is None:
        _signal_deduplicator = SignalDeduplicator()
    return _signal_deduplicator
